using KHSave.Attributes;

namespace KHSave.Lib2.Types
{
    public enum EquipmentType : short
    {
        [Info] Empty,
        [Consumable("Potion")] Potion,
        [Consumable("Hi-Potion")] HiPotion,
        [Consumable("Ether")] Ether,
        [Consumable("Elixir")] Elixir,
        [Consumable("Mega-Potion")] MegaPotion,
        [Consumable("Mega-Ether")] MegaEther,
        [Consumable("Megalixir")] Megalixir,
        [Accessory("Ability Ring")] AbilityRing,
        [Accessory("Engineer´s Ring")] EngineersRing,
        [Accessory("Technician´s Ring")] TechniciansRing,
        [Accessory("Expert´s Ring")] ExpertsRing,
        [Accessory("Sardonyx Ring")] SardonyxRing,
        [Accessory("Tourmaline Ring")] TourmalineRing,
        [Accessory("Aquamarine Ring")] AquamarineRing,
        [Accessory("Garnet Ring")] GarnetRing,
        [Accessory("Diamond Ring")] DiamondRing,
        [Accessory("Silver Ring")] SilverRing,
        [Accessory("Gold Ring")] GoldRing,
        [Accessory("Platinum Ring")] PlatinumRing,
        [Accessory("Mythril Ring")] MythrilRing,
        [Magic("Fire Element")] FireElement,
        [Magic("Blizzard Element")] BlizzardElement,
        [Magic("Thunder Element")] ThunderElement,
        [Magic("Cure Element")] CureElement,
        [Summon("Ukulele Charm")] UkuleleCharm,
        [Form("Valor Form")] ValorForm,
        [Form("Wisdom Form")] WisdomForm,
        [Accessory("Orichalcum Ring")] OrichalcumRing,
        [Form("Final Form")] FinalForm,
        [Form("Antiform")] Antiform,
        [Form("Master Form")] MasterForm,
        [Recipe("Torn Pages")] TornPages,
        [Unused] Unused021,
        [Accessory("Master´s Ring")] MastersRing,
        [Accessory("Moon Amulet")] MoonAmulet,
        [Accessory("Star Charm")] StarCharm,
        [Unused] Unused025,
        [Accessory("Skill Ring")] SkillRing,
        [Accessory("Skillful Ring")] SkillfulRing,
        [Accessory("Soldier Earring")] SoldierEarring,
        [Keyblade("Kingdom Key")] KingdomKey,
        [Keyblade("Oathkeeper")] Oathkeeper,
        [Keyblade("Oblivion")] Oblivion,
        [Keyblade("Detection Saber")] DetectionSaber,
        [Keyblade("Frontier of Ultima")] FrontierOfUltima,
        [Accessory("Fencer Earring")] FencerEarring,
        [Accessory("Mage Earring")] MageEarring,
        [Accessory("Slayer Earring")] SlayerEarring,
        [Shield("Knight´s Shield")] KnightsShield,
        [Shield("Detection Shield")] DetectionShield,
        [Shield("Test the King")] TestTheKing,
        [Accessory("Cosmic Ring")] CosmicRing,
        [Accessory("Medal")] Medal,
        [Weapon("Battlefields of War")] BattlefieldsOfWar,
        [Weapon("Sword of the Ancestor")] SwordOfTheAncestor,
        [Accessory("Cosmic Arts")] CosmicArts,
        [Accessory("Shadow Archive")] ShadowArchive,
        [Accessory("Shadow Archive+")] ShadowArchivePlus,
        [Weapon("Beast´s Claw")] BeastsClaw,
        [Weapon("Bone Fist")] BoneFist,
        [Weapon("Proud Fang")] ProudFang,
        [Weapon("Skill and Crossbones")] SkillAndCrossbones,
        [Accessory("Lucky Ring")] LuckyRing,
        [Accessory("Full Bloom")] FullBloom,
        [Accessory("Draw Ring")] DrawRing,
        [Accessory("Full Bloom+")] FullBloomPlus,
        [Armor("Elven Bandanna")] ElvenBandanna,
        [Armor("Divine Bandanna")] DivineBandanna,
        [Armor("Power Band")] PowerBand,
        [Armor("Buster Band")] BusterBand,
        [Keyblade("Antiform Dummy")] AntiformDummy,
        [Weapon("Scimitar")] Scimitar,
        [Weapon("Way to the Dawn")] WayToTheDawn,
        [Weapon("Identity Disk")] IdentityDisk,
        [Staff("Mage´s Staff")] MagesStaff,
        [Unused] Unused04C,
        [Unused] Unused04D,
        [Armor("Protect Belt")] ProtectBelt,
        [Armor("Gaia Belt")] GaiaBelt,
        [Weapon("Unused Weapon")] Unused050,
        [Keyblade("Kingdom Key W")] KingdomKeyW,
        [Ability("Guard")] Guard,
        [Unused] Unused053,
        [Unused] Unused054,
        [Unused] Unused055,
        [Unused] Unused056,
        [Magic("Magnet Element")] MagnetElement,
        [Magic("Reflect Element")] ReflectElement,
        [Map("Navigational Map")] NavigationalMap,
        [Map("Castle Map")] CastleMap,
        [Map("Basement Map")] BasementMap,
        [Map("Castle Walls Map")] CastleWallsMap,
        [Unused] Unused05D,
        [Ability("High Jump LV1")] HighJumpLV1,
        [Ability("High Jump LV2")] HighJumpLV2,
        [Ability("High Jump LV3")] HighJumpLV3,
        [Ability("High Jump MAX")] HighJumpMAX,
        [Ability("Quick Run LV1")] QuickRunLV1,
        [Ability("Quick Run LV2")] QuickRunLV2,
        [Ability("Quick Run LV3")] QuickRunLV3,
        [Ability("Quick Run MAX")] QuickRunMAX,
        [Ability("Aerial Dodge LV1")] AerialDodgeLV1,
        [Ability("Aerial Dodge LV2")] AerialDodgeLV2,
        [Ability("Aerial Dodge LV3")] AerialDodgeLV3,
        [Ability("Aerial Dodge MAX")] AerialDodgeMAX,
        [Ability("Glide LV1")] GlideLV1,
        [Ability("Glide LV2")] GlideLV2,
        [Ability("Glide LV3")] GlideLV3,
        [Ability("Glide MAX")] GlideMAX,
        [Unused] Unused06E,
        [Armor("Cosmic Belt")] CosmicBelt,
        [Map("Encampment Area Map")] EncampmentAreaMap,
        [Map("Village Area Map")] VillageAreaMap,
        [Map("Cornerstone Hill Map")] CornerstoneHillMap,
        [Map("Window of Time Map 2")] WindowOfTimeMap2,
        [Map("Lilliput Map")] LilliputMap,
        [Map("Building Site Map")] BuildingSiteMap,
        [Map("Mickey´s House Map")] MickeysHouseMap,
        [Map("Disney Castle Map")] DisneyCastleMap,
        [Map("Agrabah Map")] AgrabahMap,
        [Map("Cave of Wonders Map")] CaveOfWondersMap,
        [Map("Ruins Map")] RuinsMap,
        [Map("Undersea Kingdom Map")] UnderseaKingdomMap,
        [Map("Starry Hill")] StarryHill,
        [Map("100 Acre Wood Map")] HundredAcreWoodMap,
        [Map("Rabbit´s Howse Map")] RabbitsHowseMap,
        [Map("Piglet´s Howse Map")] PigletsHowseMap,
        [Map("Kanga´s Howse Map")] KangasHowseMap,
        [Map("Spooky Cave Map")] SpookyCaveMap,
        [Map("Palace Map")] PalaceMap,
        [Boost("Tent")] Tent,
        [Armor("Shock Charm")] ShockCharm,
        [Armor("Shock Charm+")] ShockCharmPlus,
        [Map("Coliseum Map")] ColiseumMap,
        [Map("Underworld Map")] UnderworldMap,
        [Map("Caverns Map")] CavernsMap,
        [Ability("Upper Slash")] UpperSlash,
        [Ability("Scan")] Scan,
        [Shield("Adamant Shield")] AdamantShield,
        [Shield("Chain Gear")] ChainGear,
        [Shield("Ogre Shield")] OgreShield,
        [Shield("Falling Star")] FallingStar,
        [Shield("Dreamcloud")] Dreamcloud,
        [Shield("Knight Defender")] KnightDefender,
        [Shield("Genji Shield")] GenjiShield,
        [Shield("Akashic Record")] AkashicRecord,
        [Shield("Nobody Guard")] NobodyGuard,
        [Staff("Hammer Staff")] HammerStaff,
        [Staff("Victory Bell")] VictoryBell,
        [Staff("Meteor Staff")] MeteorStaff,
        [Staff("Comet Staff")] CometStaff,
        [Staff("Lord´s Broom")] LordsBroom,
        [Staff("Wisdom Wand")] WisdomWand,
        [Staff("Rising Dragon")] RisingDragon,
        [Staff("Nobody Lance")] NobodyLance,
        [Staff("Shaman´s Relic")] ShamansRelic,
        [Armor("Grand Ribbon")] GrandRibbon,
        [Ability("Aerial Recovery")] AerialRecovery,
        [Summon("Lamp Charm")] LampCharm,
        [Summon("Feather Charm")] FeatherCharm,
        [Staff("Staff of Detection")] StaffOfDetection,
        [Ability("Combo Plus")] ComboPlus,
        [Ability("Air Combo Plus")] AirComboPlus,
        [Unused] Unused0A4,
        [Ability("Donald Fire")] DonaldFire,
        [Ability("Donald Blizzard")] DonaldBlizzard,
        [Ability("Donald Thunder")] DonaldThunder,
        [Ability("Donald Cure")] DonaldCure,
        [Unused] Unused0A9,
        [Unused] Unused0AA,
        [Unused] Unused0AB,
        [Unused] Unused0AC,
        [Armor("Fire Bangle")] FireBangle,
        [Armor("Fira Bangle")] FiraBangle,
        [Unused] Unused0AF,
        [Ability("Healing Water")] HealingWater,
        [Ability("Furious Shout")] FuriousShout,
        [Unused] Unused0B2,
        [Unused] Unused0B3,
        [Unused] Unused0B4,
        [Unused] Unused0B5,
        [Unused] Unused0B6,
        [Unused] Unused0B7,
        [Unused] Unused0B8,
        [Unused] Unused0B9,
        [Unused] Unused0BA,
        [Ability("Cure Potion")] CurePotion,
        [Unused] Unused0BC,
        [Unused] Unused0BD,
        [Ability("Healing Herb")] HealingHerb,
        [Unused] Unused0BF,
        [Unused] Unused0C0,
        [Unused] Unused0C1,
        [Unused] Unused0C2,
        [Ability("Slow 3")] Slow3,
        [Unused] Unused0C4,
        [Armor("Firaga Bangle")] FiragaBangle,
        [Ability("Trinity Limit")] TrinityLimit,
        [Ability("Fantasia")] Fantasia,
        [Ability("Flare Force")] FlareForce,
        [Ability("Tornado Fusion")] TornadoFusion,
        [Ability("Teamwork")] Teamwork,
        [Ability("Trick Fantasy")] TrickFantasy,
        [Ability("Overdrive")] Overdrive,
        [Ability("Howling Moon")] HowlingMoon,
        [Ability("Applause, Applause")] ApplauseApplause,
        [Ability("Dragonblaze")] Dragonblaze,
        [Ability("Eternal Session")] EternalSession,
        [Ability("King´s Pride")] KingsPride,
        [Ability("Treasure Isle")] TreasureIsle,
        [Ability("Complete Compilement")] CompleteCompilement,
        [Unused] Unused0D4,
        [Unused] Unused0D5,
        [Unused] Unused0D6,
        [Ability("Pulsing Thunder")] PulsingThunder,
        [Ability("Brave Shot")] BraveShot,
        [Ability("Brave Beat")] BraveBeat,
        [Ability("Sonic Strike")] SonicStrike,
        [Ability("Sonic End")] SonicEnd,
        [Ability("Wisdom Shot")] WisdomShot,
        [Ability("Mobile Action")] MobileAction,
        [Unused] Unused0DE,
        [Ability("Synch Blade")] SynchBlade,
        [Ability("Magic Haste")] MagicHaste,
        [Ability("Magic Spice")] MagicSpice,
        [Report("Secret Ansem Report 1")] SecretAnsemReport1,
        [Report("Secret Ansem Report 2")] SecretAnsemReport2,
        [Report("Secret Ansem Report 3")] SecretAnsemReport3,
        [Report("Secret Ansem Report 4")] SecretAnsemReport4,
        [Report("Secret Ansem Report 5")] SecretAnsemReport5,
        [Report("Secret Ansem Report 6")] SecretAnsemReport6,
        [Report("Secret Ansem Report 7")] SecretAnsemReport7,
        [Report("Secret Ansem Report 8")] SecretAnsemReport8,
        [Report("Secret Ansem Report 9")] SecretAnsemReport9,
        [Report("Secret Ansem Report 10")] SecretAnsemReport10,
        [Report("Secret Ansem Report 11")] SecretAnsemReport11,
        [Report("Secret Ansem Report 12")] SecretAnsemReport12,
        [Report("Secret Ansem Report 13")] SecretAnsemReport13,
        [Unused] Unused0EF,
        [Unused] Unused0F0,
        [Unused] Unused0F1,
        [Unused] Unused0F2,
        [Unused] Unused0F3,
        [Unused] Unused0F4,
        [Unused] Unused0F5,
        [Ability("Over the Horizon")] OverTheHorizon,
        [Ability("Omega Finale")] OmegaFinale,
        [Ability("Reflect Dummy")] ReflectDummy,
        [Ability("Upper Dummy")] UpperDummy,
        [Map("Halloween Town Map")] HalloweenTownMap,
        [Map("Naval Map")] NavalMap,
        [Map("Pride Rock Map")] PrideRockMap,
        [Map("Marketplace Map")] MarketplaceMap,
        [Map("Pit Cell Area Map")] PitCellAreaMap,
        [Map("Twilight Town Map")] TwilightTownMap,
        [Map("Dark City Map")] DarkCityMap,
        [Ability("Master Strike")] MasterStrike,
        [Ability("Disaster")] Disaster,
        [Ability("Endless Magic")] EndlessMagic,
        [Unused] Unused104,
        [Ability("Master Magic")] MasterMagic,
        [Ability("Slapshot")] Slapshot,
        [Ability("Dodge Slash")] DodgeSlash,
        [Ability("Slide Dash")] SlideDash,
        [Ability("Guard Break")] GuardBreak,
        [Ability("Explosion")] Explosion,
        [Ability("Finishing Leap")] FinishingLeap,
        [Ability("Counterguard")] Counterguard,
        [Ability("Aerial Sweep")] AerialSweep,
        [Ability("Aerial Spiral")] AerialSpiral,
        [Ability("Horizontal Slash")] HorizontalSlash,
        [Ability("Aerial Finish")] AerialFinish,
        [Ability("Retaliating Slash")] RetaliatingSlash,
        [Boost("Drive Recovery")] DriveRecovery,
        [Boost("High Drive Recovery")] HighDriveRecovery,
        [Boost("Power Boost")] PowerBoost,
        [Boost("Magic Boost")] MagicBoost,
        [Boost("Defense Boost")] DefenseBoost,
        [Boost("AP Boost")] APBoost,
        [Synthesis("Dark Shard")] DarkShard,
        [Synthesis("Dark Stone")] DarkStone,
        [Synthesis("Dark Gem")] DarkGem,
        [Synthesis("Dark Crystal")] DarkCrystal,
        [Armor("Firagun Bangle")] FiragunBangle,
        [Unused] Unused11D,
        [Armor("Blizzard Armlet")] BlizzardArmlet,
        [Armor("Blizzara Armlet")] BlizzaraArmlet,
        [Armor("Blizzaga Armlet")] BlizzagaArmlet,
        [Armor("Blizzagun Armlet")] BlizzagunArmlet,
        [Unused] Unused122,
        [Armor("Thunder Trinket")] ThunderTrinket,
        [Armor("Thundara Trinket")] ThundaraTrinket,
        [Armor("Thundaga Trinket")] ThundagaTrinket,
        [Armor("Thundagun Trinket")] ThundagunTrinket,
        [Unused] Unused127,
        [Armor("Shadow Anklet")] ShadowAnklet,
        [Armor("Dark Anklet")] DarkAnklet,
        [Armor("Midnight Anklet")] MidnightAnklet,
        [Armor("Chaos Anklet")] ChaosAnklet,
        [Unused] Unused12C,
        [Armor("Abas Chain")] AbasChain,
        [Armor("Aegis Chain")] AegisChain,
        [Armor("Acrisius")] Acrisius,
        [Armor("Ribbon")] Ribbon,
        [Armor("Champion Belt")] ChampionBelt,
        [Armor("Petite Ribbon")] PetiteRibbon,
        [Armor("Acrisius+")] AcrisiusPlus,
        [Armor("Cosmic Chain")] CosmicChain,
        [Unused] Unused135,
        [Unused] Unused136,
        [Unused] Unused137,
        [Unused] Unused138,
        [Unused] Unused139,
        [Unused] Unused13A,
        [Unused] Unused13B,
        [Unused] Unused13C,
        [Synthesis("Blazing Shard")] BlazingShard,
        [Synthesis("Blazing Stone")] BlazingStone,
        [Synthesis("Blazing Gem")] BlazingGem,
        [Synthesis("Blazing Crystal")] BlazingCrystal,
        [Unused] Unused141,
        [Unused] Unused142,
        [Unused] Unused143,
        [Unused] Unused144,
        [Synthesis("Lightning Shard")] LightningShard,
        [Synthesis("Lightning Stone")] LightningStone,
        [Synthesis("Lightning Gem")] LightningGem,
        [Synthesis("Lightning Crystal")] LightningCrystal,
        [Synthesis("Power Shard")] PowerShard,
        [Synthesis("Power Stone")] PowerStone,
        [Synthesis("Power Gem")] PowerGem,
        [Synthesis("Power Crystal")] PowerCrystal,
        [Synthesis("Lucid Shard")] LucidShard,
        [Synthesis("Lucid Stone")] LucidStone,
        [Synthesis("Lucid Gem")] LucidGem,
        [Synthesis("Lucid Crystal")] LucidCrystal,
        [Synthesis("Dense Shard")] DenseShard,
        [Synthesis("Dense Stone")] DenseStone,
        [Synthesis("Dense Gem")] DenseGem,
        [Synthesis("Dense Crystal")] DenseCrystal,
        [Synthesis("Twilight Shard")] TwilightShard,
        [Synthesis("Twilight Stone")] TwilightStone,
        [Synthesis("Twilight Gem")] TwilightGem,
        [Synthesis("Twilight Crystal")] TwilightCrystal,
        [Synthesis("Mythril Shard")] MythrilShard,
        [Synthesis("Mythril Stone")] MythrilStone,
        [Synthesis("Mythril Gem")] MythrilGem,
        [Synthesis("Mythril Crystal")] MythrilCrystal,
        [Synthesis("Bright Shard")] BrightShard,
        [Synthesis("Bright Stone")] BrightStone,
        [Synthesis("Bright Gem")] BrightGem,
        [Synthesis("Bright Crystal")] BrightCrystal,
        [Synthesis("Energy Shard")] EnergyShard,
        [Synthesis("Energy Stone")] EnergyStone,
        [Synthesis("Energy Gem")] EnergyGem,
        [Synthesis("Energy Crystal")] EnergyCrystal,
        [Synthesis("Serenity Shard")] SerenityShard,
        [Synthesis("Serenity Stone")] SerenityStone,
        [Synthesis("Serenity Gem")] SerenityGem,
        [Synthesis("Serenity Crystal")] SerenityCrystal,
        [Synthesis("Orichalcum+")] OrichalcumPlus,
        [Recipe("Munny Pouch")] MunnyPouch,
        [Recipe("Crystal Orb")] CrystalOrb,
        [Recipe("Seifer´s Trophy")] SeifersTrophy,
        [Recipe("Tournament Poster")] TournamentPoster,
        [Recipe("Poster")] Poster,
        [Recipe("Letter")] Letter,
        [Recipe("Naminé´s Sketches")] NaminésSketches,
        [Recipe("Membership Card")] MembershipCard,
        [Recipe("Olympus Stone")] OlympusStone,
        [Recipe("Auron´s Statue")] AuronsStatue,
        [Recipe("Cursed Medallion")] CursedMedallion,
        [Recipe("Present")] Present,
        [Recipe("Decoy Presents")] DecoyPresents,
        [Recipe("Ice Cream")] IceCream,
        [Recipe("Picture")] Picture,
        [Synthesis("Orichalcum")] Orichalcum,
        [Synthesis("Frost Shard")] FrostShard,
        [Synthesis("Frost Stone")] FrostStone,
        [Synthesis("Frost Gem")] FrostGem,
        [Synthesis("Frost Crystal")] FrostCrystal,
        [Recipe("Mega-Recipe")] MegaRecipe,
        [Summon("Baseball Charm")] BaseballCharm,
        [Keyblade("Struggle Sword")] StruggleSword,
        [Ability("Auto Valor")] AutoValor,
        [Ability("Auto Wisdom")] AutoWisdom,
        [Ability("Auto Master")] AutoMaster,
        [Ability("Auto Final")] AutoFinal,
        [Ability("Auto Summon")] AutoSummon,
        [Ability("Combo Boost")] ComboBoost,
        [Ability("Air Combo Boost")] AirComboBoost,
        [Ability("Reaction Boost")] ReactionBoost,
        [Ability("Finishing Plus")] FinishingPlus,
        [Ability("Negative Combo")] NegativeCombo,
        [Ability("Berserk Charge")] BerserkCharge,
        [Ability("Damage Drive")] DamageDrive,
        [Ability("Drive Boost")] DriveBoost,
        [Ability("Form Boost")] FormBoost,
        [Ability("Summon Boost")] SummonBoost,
        [Ability("Combination Boost")] CombinationBoost,
        [Ability("Experience Boost")] ExperienceBoost,
        [Ability("Leaf Bracer")] LeafBracer,
        [Ability("Magic Lock-On")] MagicLockOn,
        [Ability("No Experience")] NoExperience,
        [Ability("Draw")] Draw,
        [Ability("Jackpot")] Jackpot,
        [Ability("Lucky Lucky")] LuckyLucky,
        [Ability("Fire Boost")] FireBoost,
        [Ability("Blizzard Boost")] BlizzardBoost,
        [Ability("Thunder Boost")] ThunderBoost,
        [Ability("Item Boost")] ItemBoost,
        [Ability("MP Rage")] MPRage,
        [Ability("MP Haste")] MPHaste,
        [Ability("Defender")] Defender,
        [Ability("Second Chance")] SecondChance,
        [Ability("Once More")] OnceMore,
        [Ability("Auto Limit")] AutoLimit,
        [Ability("Auto Change")] AutoChange,
        [Ability("Hyper Healing")] HyperHealing,
        [Ability("Auto Healing")] AutoHealing,
        [Ability("MP Hastera")] MPHastera,
        [Ability("MP Hastega")] MPHastega,
        [Ability("Goofy Tornado")] GoofyTornado,
        [Unused] Unused1A8,
        [Ability("Goofy Turbo")] GoofyTurbo,
        [Ability("Slash Frenzy")] SlashFrenzy,
        [Ability("Quickplay")] Quickplay,
        [Ability("Divider")] Divider,
        [Ability("Goofy Bash")] GoofyBash,
        [Ability("Ferocious Rush")] FerociousRush,
        [Ability("Blazing Fury")] BlazingFury,
        [Ability("Icy Terror")] IcyTerror,
        [Ability("Bolts of Sorrow")] BoltsOfSorrow,
        [Ability("Mushu Fire")] MushuFire,
        [Ability("Flametongue")] Flametongue,
        [Ability("Dark Shield")] DarkShield,
        [Unused] Unused1B5,
        [Ability("Dark Aura")] DarkAura,
        [Ability("Fierce Claw")] FierceClaw,
        [Ability("Groundshaker")] Groundshaker,
        [Unused] Unused1B9,
        [Unused] Unused1BA,
        [Unused] Unused1BB,
        [Ability("Scouting Disk")] ScoutingDisk,
        [Ability("Slow 2")] Slow2,
        [Ability("No Mercy")] NoMercy,
        [Ability("Rain Storm")] RainStorm,
        [Ability("Bone Smash")] BoneSmash,
        [Recipe("Star Recipe")] StarRecipe,
        [Recipe("Recovery Recipe")] RecoveryRecipe,
        [Recipe("Skill Recipe")] SkillRecipe,
        [Recipe("Guard Recipe")] GuardRecipe,
        [Recipe("Dummy 06")] Dummy06,
        [Recipe("Dummy 07")] Dummy07,
        [Recipe("Dummy 08")] Dummy08,
        [Recipe("Dummy 09")] Dummy09,
        [Recipe("Dummy 10")] Dummy10,
        [Recipe("Dummy 11")] Dummy11,
        [Recipe("Dummy 12")] Dummy12,
        [Recipe("Dummy 13")] Dummy13,
        [Recipe("Dummy 14")] Dummy14,
        [Recipe("Dummy 15")] Dummy15,
        [Recipe("Dummy 16")] Dummy16,
        [Recipe("Road to Discovery")] RoadToDiscovery,
        [Recipe("Strength Beyond Strength")] StrengthBeyondStrength,
        [Recipe("Book of Shadows")] BookOfShadows,
        [Recipe("Cloaked Thunder")] CloakedThunder,
        [Recipe("Eternal Blossom")] EternalBlossom,
        [Recipe("Rare Document")] RareDocument,
        [Recipe("Dummy 23")] Dummy23,
        [Recipe("Dummy 24")] Dummy24,
        [Recipe("Dummy 25")] Dummy25,
        [Recipe("Dummy 26")] Dummy26,
        [Recipe("Dummy 27")] Dummy27,
        [Recipe("Style Recipe")] StyleRecipe,
        [Recipe("Moon Recipe")] MoonRecipe,
        [Recipe("Queen Recipe")] QueenRecipe,
        [Recipe("King Recipe")] KingRecipe,
        [Recipe("Ultimate Recipe")] UltimateRecipe,
        [Keyblade("Star Seeker")] StarSeeker,
        [Keyblade("Hidden Dragon")] HiddenDragon,
        [Staff("Save the Queen")] SaveTheQueen,
        [Shield("Save the King")] SaveTheKing,
        [Keyblade("Hero´s Crest")] HerosCrest,
        [Keyblade("Monochrome")] Monochrome,
        [Keyblade("Follow the Wind")] FollowTheWind,
        [Keyblade("Circle of Life")] CircleOfLife,
        [Keyblade("Photon Debugger")] PhotonDebugger,
        [Keyblade("Gull Wing")] GullWing,
        [Keyblade("Rumbling Rose")] RumblingRose,
        [Keyblade("Guardian Soul")] GuardianSoul,
        [Keyblade("Wishing Lamp")] WishingLamp,
        [Keyblade("Decisive Pumpkin")] DecisivePumpkin,
        [Keyblade("Sleeping Lion")] SleepingLion,
        [Keyblade("Sweet Memories")] SweetMemories,
        [Keyblade("Mysterious Abyss")] MysteriousAbyss,
        [Keyblade("Fatal Crest")] FatalCrest,
        [Keyblade("Bond of Flame")] BondOfFlame,
        [Keyblade("Fenrir")] Fenrir,
        [Keyblade("Ultima Weapon")] UltimaWeapon,
        [Keyblade("Struggle Wand")] StruggleWand,
        [Keyblade("Struggle Hammer")] StruggleHammer,
        [Staff("Save the Queen+")] SaveTheQueenPlus,
        [Shield("Save the King+")] SaveTheKingPlus,
        [Map("The Interceptor Map")] TheInterceptorMap,
        [Map("The Black Pearl Map")] TheBlackPearlMap,
        [Map("Isla de Muerta Map")] IslaDeMuertaMap,
        [Map("Ship Graveyard Map")] ShipGraveyardMap,
        [Map("Christmas Town Map")] ChristmasTownMap,
        [Map("Curly Hill Map")] CurlyHillMap,
        [Map("Oasis Map")] OasisMap,
        [Map("Savannah Map")] SavannahMap,
        [Map("Castle Perimeter Map")] CastlePerimeterMap,
        [Map("The Great Maw Map")] TheGreatMawMap,
        [Map("I/O Tower Map")] IOTowerMap,
        [Map("Central Computer Core Map")] CentralComputerCoreMap,
        [Map("Solar Sailer Simulation Map")] SolarSailerSimulationMap,
        [Map("Window of Time Map")] WindowOfTimeMap,
        [Ability("Auto Assault")] AutoAssault,
        [Ability("Finishing Blast")] FinishingBlast,
        [Ability("Combo Upper")] ComboUpper,
        [Ability("Aerial Impulse")] AerialImpulse,
        [Ability("Retaliating Smash")] RetaliatingSmash,
        [Recipe("Promise Charm")] PromiseCharm,
        [Ability("Running Tackle")] RunningTackle,
        [Ability("Dash")] Dash,
        [Ability("Final Arcana")] FinalArcana,
        [Ability("Final Strike")] FinalStrike,
        [Ability("Final Arts")] FinalArts,
        [Ability("Crime & Punishment")] CrimeAndPunishment,
        [Map("Sunset Hill Map")] SunsetHillMap,
        [Map("Mansion Map")] MansionMap,
        [Map("Tower Map")] TowerMap,
        [Map("DH Map")] DHMap,
        [Recipe("Munny Pouch")] MunnyPouch2,
        [Map("Castle That Never Was Map")] CastleThatNeverWasMap,
        [Recipe("Hades Cup Trophy")] HadesCupTrophy,
        [Recipe("The Struggle Trophy")] TheStruggleTrophy,
        [Ability("Combo Master")] ComboMaster,
        [Ability("Drive Converter")] DriveConverter,
        [Ability("Light & Darkness")] LightAndDarkness,
        [Ability("Damage Control")] DamageControl,
        [Keyblade("Two Become One")] TwoBecomeOne,
        [Keyblade("Winner's Proof")] WinnersProof,
        [Staff("Centurion")] Centurion,
        [Staff("Centurion+")] CenturionPlus,
        [Staff("Plain Mushroom")] PlainMushroom,
        [Staff("Plain Mushroom+")] PlainMushroomPlus,
        [Staff("Precious Mushroom")] PreciousMushroom,
        [Staff("Precious Mushroom+")] PreciousMushroomPlus,
        [Staff("Premium Mushroom")] PremiumMushroom,
        [Shield("Frozen Pride")] FrozenPride,
        [Shield("Frozen Pride+")] FrozenPridePlus,
        [Shield("Joyous Mushroom")] JoyousMushroom,
        [Shield("Joyous Mushroom+")] JoyousMushroomPlus,
        [Shield("Majestic Mushroom")] MajesticMushroom,
        [Shield("Majestic Mushroom+")] MajesticMushroomPlus,
        [Shield("Ultimate Mushroom")] UltimateMushroom,
        [Ability("Flash Step")] FlashStep,
        [Ability("Aerial Dive")] AerialDive,
        [Ability("Magnet Burst")] MagnetBurst,
        [Ability("Vicinity Break")] VicinityBreak,
        [Form("Limit Form")] LimitForm,
        [Ability("Dodge Roll LV 1")] DodgeRollLV1,
        [Ability("Dodge Roll LV 2")] DodgeRollLV2,
        [Ability("Dodge Roll LV 3")] DodgeRollLV3,
        [Ability("Dodge Roll MAX")] DodgeRollMAX,
        [Ability("Auto Limit")] AutoLimit2,
        [Ability("Sonic Rave")] SonicRave,
        [Ability("Last Arcanum")] LastArcanum,
        [Ability("Strike Raid")] StrikeRaid,
        [Ability("Infinity")] Infinity,
        [Ability("Zantetsuken")] Zantetsuken,
        [Ability("Ripple Drive")] RippleDrive,
        [Ability("Hurricane Period")] HurricanePeriod,
        [Synthesis("Remembrance Shard")] RemembranceShard,
        [Synthesis("Remembrance Stone")] RemembranceStone,
        [Synthesis("Remembrance Gem")] RemembranceGem,
        [Synthesis("Remembrance Crystal")] RemembranceCrystal,
        [Synthesis("Tranquility Shard")] TranquilityShard,
        [Synthesis("Tranquility Stone")] TranquilityStone,
        [Synthesis("Tranquility Gem")] TranquilityGem,
        [Synthesis("Tranquility Crystal")] TranquilityCrystal,
        [Synthesis("Lost Illusion")] LostIllusion,
        [Synthesis("Manifest Illusion")] ManifestIllusion,
        [Map("Dark Remembrance Map")] DarkRemembranceMap,
        [Ability("Zantetsu Counter")] ZantetsuCounter,
        [Ability("Reflect Combo")] ReflectCombo,
        [Ability("HP Gain")] HPGain,
        [Map("Depths of Remembrance Map")] DepthsOfRemembranceMap,
        [Unused] Unused24F,
        [Map("Garden of Assemblage Map")] GardenOfAssemblageMap,
        [Recipe("Proof of Connection")] ProofOfConnection,
        [Recipe("Proof of Nonexistence")] ProofOfNonexistence,
        [Recipe("Proof of Peace")] ProofOfPeace,
        [Ability("Protect")] Protect,
        [Ability("Protectra")] Protectra,
        [Ability("Protectga")] Protectga,
        [Accessory("Executive's Ring")] ExecutivesRing,
        [Staff("Shaman's Relic+")] ShamansRelicPlus,
        [Shield("Akashic Record+")] AkashicRecordPlus,
    }
}

