/*
    Kingdom Save Editor
    Copyright (C) 2020 Luciano Ciccariello

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using KHSave.Attributes;

namespace KHSave.Lib2.Types
{
    public enum InventoryType : int
    {
        [Consumable("Potion")] Potion,
        [Consumable("Hi-Potion")] HiPotion,
        [Consumable("Ether")] Ether,
        [Consumable("Elixir")] Elixir,
        [Consumable("Mega-Potion")] MegaPotion,
        [Consumable("Mega-Ether")] MegaEther,
        [Consumable("Megalixir")] Megalixir,
        [Accessory("Ability Ring")] AbilityRing,
        [Accessory("Engineer's Ring")] EngineerRing,
        [Accessory("Technician's Ring")] TechnicianRing,
        [Accessory("Expert Ring")] ExpertRing,
        [Accessory("Sardonyx Ring")] SardonyxRing,
        [Accessory("Tourmaline Ring")] TourmalineRing,
        [Accessory("Aquamarine Ring")] AquamarineRing,
        [Accessory("Garnet Ring")] GarnetRing,
        [Accessory("Diamond Ring")] DiamondRing,
        [Accessory("Silver Ring")] SilverRing,
        [Accessory("Gold Ring")] GoldRing,
        [Accessory("Platinum Ring")] PlatinumRing,
        [Accessory("Mythril Ring")] MythrilRing,
        [Unused] Unused20,
        [Unused] Unused21,
        [Unused] Unused22,
        [Unused] Unused23,
        [KeyItem("Torn Pages")] TornPages,
        [Unused] Unused25,
        [Accessory("Orichalcum Ring")] OrichalcumRing,
        [Accessory("Master's Ring")] MasterRing,
        [Accessory("Moon Amulet")] MoonAmulet,
        [Unused] Unused29,
        [Accessory("Star Charm")] StarCharm,
        [Accessory("Skill Ring")] SkillRing,
        [Accessory("Skillful Ring")] SkillfulRing,
        [Keyblade("Kingdom Key")] KingdomKey,
        [Keyblade("Oathkeeper")] Oathkeeper,
        [Keyblade("Oblivion")] Oblivion,
        [Keyblade("Detection Saber")] DetectionSaber,
        [Keyblade("Frontier of Ultima")] FrontierOfUltima,
        [Accessory("Soldier Earring")] SoldierEarring,
        [Accessory("Fencer Earring")] FencerEarring,
        [Accessory("Mage Earring")] MageEarring,
        [Shield("Knight's Shield")] KnightShield,
        [Shield("Detection Shield")] DetectionShield,
        [Shield("Test the King")] TestTheKing,
        [Accessory("Slayer Earring")] SlayerEarring,
        [Accessory("Cosmic Ring")] CosmicRing,
        [Weapon("Battlefields of War")] BattlefieldsOfWar,
        [Weapon("Sword of the Ancestor")] SwordOfTheAncestor,
        [Accessory("Medal")] Medal,
        [Accessory("Cosmic Arts")] CosmicArts,
        [Accessory("Shadow Archive")] ShadowArchive,
        [Weapon("Beast's Claw")] BeastClaw,
        [Weapon("Bone Fist")] BoneFist,
        [Weapon("Proud Fang")] ProudFang,
        [Weapon("Skill and Crossbones")] SkillAndCrossbones,
        [Accessory("Shadow Archive+")] ShadowArchivePlus,
        [Accessory("Lucky Ring")] LuckyRing,
        [Accessory("Full Bloom")] FullBloom,
        [Accessory("Draw Ring")] DrawRing,
        [Accessory("Full Bloom+")] FullBloomPlus,
        [Armor("ElvenBandanna")] ElvenBandanna,
        [Armor("Divine Bandanna")] DivineBandanna,
        [Armor("Power Band")] PowerBand,
        [Keyblade("Antiform Dummy")] AntiformDummy,
        [Weapon("Scimitar")] Scimitar,
        [Weapon("Way to the Dawn")] WayToTheDawn,
        [Weapon("Identity Disk")] IdentityDisk,
        [Staff("Mage's Staff")] MageStaff,
        [Unused] Unused68,
        [Unused] Unused69,
        [Armor("Buster Band")] BusterBand,
        [Armor("Protect Belt")] ProtectBelt,
        [Weapon("ID not found")] Unused72,
        [Keyblade("ID not found")] Unused73,
        [Armor("Gaia Belt")] GaiaBelt,
        [Unused] Unused75,
        [Unused] Unused76,
        [Unused] Unused77,
        [Unused] Unused78,
        [Unused] Unused79,
        [Unused] Unused80,
        [Armor("Cosmic Belt")] CosmicBelt,
        [Armor("Shock Charm")] ShockCharm,
        [Armor("Shock Charm+")] ShockCharmPlus,
        [Armor("Grand Ribbon")] GrandRibbon,
        [Unused] Unused85,
        [Unused] Unused86,
        [Armor("Fire Bangle")] FireBangle,
        [Armor("Fira Bangle")] FiraBangle,
        [Armor("Firaga Bangle")] FiragaBangle,
        [Armor("Firagun Bangle")] FiragunBangle,
        [Unused] Unused91,
        [Armor("Blizzard Armlet")] BlizzardArmlet,
        [Armor("Blizzara Armlet")] BlizzaraArmlet,
        [Armor("Blizzaga Armlet")] BlizzagaArmlet,
        [Armor("Blizzagun Armlet")] BlizzagunArmlet,
        [Unused] Unused96,
        [Tent("Tent")] Tent,
        [Armor("Thunder Trinket")] ThunderTrinket,
        [Armor("Thundara Trinket")] ThundaraTrinket,
        [Armor("Thundaga Trinket")] ThundagaTrinket,
        [Armor("Thundagun Trinket")] ThundagunTrinket,
        [Shield("Adamant Shield")] AdamantShield,
        [Shield("Chain Gear")] ChainGear,
        [Shield("Ogre Shield")] OgreShield,
        [Shield("Falling Star")] FallingStar,
        [Shield("Dreamcloud")] Dreamcloud,
        [Shield("Knight Defender")] KnightDefender,
        [Shield("Genji Shield")] GenjiShield,
        [Shield("Akashic Record")] AkashicRecord,
        [Shield("Nobody Guard")] NobodyGuard,
        [Staff("Hammer Staff")] HammerStaff,
        [Staff("Victory Bell")] VictoryBell,
        [Staff("Meteor Staff")] MeteorStaff,
        [Staff("CometStuff")] CometStuff,
        [Staff("Lord's Broom")] LordBroom,
        [Staff("Wisdom Wand")] WisdomWand,
        [Staff("Rising Dragon")] RisingDragon,
        [Staff("Nobody Lance")] NobodyLance,
        [Staff("Shaman's Relic")] ShamanRelic,
        [Unused] Unused120,
        [Armor("Shadow Anklet")] ShadowAnklet,
        [Staff("Staff of Detection")] StaffOfDetection,
        [Armor("Dark Anklet")] DarkAnklet,
        [Armor("Midnight Anklet")] MidnightAnklet,
        [Armor("Chaos Anklet")] ChaosAnklet,
        [Unused] Unused126,
        [Armor("Abas Chain")] AbasChain,
        [Armor("Aegis Chain")] AegisChain,
        [Armor("Arcisius")] Arcisius,
        [Armor("Ribbon")] Ribbon,
        [Armor("Champion Belt")] ChampionBelt,
        [Armor("Petite Ribbon")] PetiteRibbon,
        [Armor("Arcisius+")] ArcisiusPlus,
        [Armor("Cosmic Chain")] CosmicChain,
        [Unused] Unused135,
        [Unused] Unused136,
        [Unused] Unused137,
        [Unused] Unused138,
        [Unused] Unused139,
        [Unused] Unused140,
        [Unused] Unused141,
        [Unused] Unused142,
        [Synthesis("Blazing Shard")] BlazingShard,
        [Synthesis("Blazing Stone")] BlazingStone,
        [Synthesis("Blazing Gem")] BlazingGem,
        [Synthesis("Blazing Crystal")] BlazingCrystal,
        [Unused] Unused147,
        [Unused] Unused148,
        [Unused] Unused149,
        [Unused] Unused150,
        [Synthesis("Lightning Shard")] LightningShard,
        [Synthesis("Lightning Stone")] LightningStone,
        [Synthesis("Lightning Gem")] LightningGem,
        [Synthesis("Lightning Crystal")] LightningCrystal,
        [Synthesis("Power Shard")] PowerShard,
        [Synthesis("Power Stone")] PowerStone,
        [Synthesis("Power Gem")] PowerGem,
        [Synthesis("Power Crystal")] PowerCrystal,
        [Synthesis("Lucid Shard")] LucidShard,
        [Synthesis("Lucid Stone")] LucidStone,
        [Synthesis("Lucid Gem")] LucidGem,
        [Synthesis("Lucid Crystal")] LucidCrystal,
        [Synthesis("Dense Shard")] DenseShard,
        [Synthesis("Dense Stone")] DenseStone,
        [Synthesis("Dense Gem")] DenseGem,
        [Synthesis("Dense Crystal")] DenseCrystal,
        [Synthesis("Twilight Shard")] TwilightShard,
        [Synthesis("Twilight Stone")] TwilightStone,
        [Synthesis("Twilight Gem")] TwilightGem,
        [Synthesis("Twilight Crystal")] TwilightCrystal,
        [Synthesis("Mythril Shard")] MythrilShard,
        [Synthesis("Mythril Stone")] MythrilStone,
        [Synthesis("Mythril Gem")] MythrilGem,
        [Synthesis("Mythril Crystal")] MythrilCrystal,
        [Synthesis("Bright Shard")] BrightShard,
        [Synthesis("Bright Stone")] BrightStone,
        [Synthesis("Bright Gem")] BrightGem,
        [Synthesis("Bright Crystal")] BrightCrystal,
        [Synthesis("Energy Shard")] EnergyShard,
        [Synthesis("Energy Stone")] EnergyStone,
        [Synthesis("Energy Gem")] EnergyGem,
        [Synthesis("Energy Crystal")] EnergyCrystal,
        [Synthesis("Serenity Shard")] SerenityShard,
        [Synthesis("Serenity Stone")] SerenityStone,
        [Synthesis("Serenity Gem")] SerenityGem,
        [Synthesis("Serenity Crystal")] SerenityCrystal,
        [Synthesis("Orichalcum+")] OrichalcumPlus,
        [KeyItem("Munny Pouch")] MunnyPouch,
        [KeyItem("Crystal Orb")] CrystalOrb,
        [KeyItem("Seifer's Trophy")] SeiferTrophy,
        [KeyItem("Tournament Poster")] TournamentPoster,
        [KeyItem("Poster")] Poster,
        [KeyItem("Letter")] Letter,
        [KeyItem("Naminé's Sketches")] NamineSketches,
        [KeyItem("Membership Card")] MembershipCard,
        [KeyItem("Olympus Stone")] OlympusStone,
        [KeyItem("Auron's Statue")] AuronStatue,
        [KeyItem("Cursed Medallion")] CursedMedallion,
        [KeyItem("Present")] Present,
        [KeyItem("Decoy Presents")] DecoyPresents,
        [KeyItem("Ice Cream")] IceCream,
        [KeyItem("Picture")] Picture,
        [Synthesis("Orichalcum")] Orichalcum,
        [Synthesis("Frost Shard")] FrostShard,
        [Synthesis("Frost Stone")] FrostStone,
        [Synthesis("Frost Gem")] FrostGem,
        [Synthesis("Frost Crystal")] FrostCrystal,
        [KeyItem("Mega-Recipe")] MegaRecipe,
        [Unused] Unused209,
        [KeyItem("Star Recipe")] StarRecipe,
        [KeyItem("Recovery Recipe")] RecoveryRecipe,
        [KeyItem("Skill Recipe")] SkillRecipe,
        [KeyItem("Guard Recipe")] GuardRecipe,
        [KeyItem("Dummy 06")] Dummy06,
        [KeyItem("Dummy 07")] Dummy07,
        [KeyItem("Dummy 08")] Dummy08,
        [KeyItem("Dummy 09")] Dummy09,
        [KeyItem("Dummy 10")] Dummy10,
        [KeyItem("Dummy 11")] Dummy11,
        [KeyItem("Dummy 12")] Dummy12,
        [KeyItem("Dummy 13")] Dummy13,
        [KeyItem("Dummy 14")] Dummy14,
        [KeyItem("Dummy 15")] Dummy15,
        [KeyItem("Dummy 16")] Dummy16,
        [KeyItem("Road to Discovery")] RoadToDiscovery,
        [KeyItem("Strength Beyond Strength")] StrengthBeyondStrength,
        [KeyItem("Book of Shadows")] BookOfShadows,
        [Tent("Drive Recovery")] DriveRecovery,
        [Tent("High Drive Recovery")] HighDriveRecovery,
        [Tent("Power Boost")] PowerBoost,
        [Tent("Magic Boost")] MagicBoost,
        [Tent("Defense Boost")] DefenseBoost,
        [Tent("AP Boost")] APBoost,
        [Synthesis("Dark Shard")] DarkShard,
        [Synthesis("Dark Stone")] DarkStone,
        [Synthesis("Dark Gem")] DarkGem,
        [Synthesis("Dark Crystal")] DarkCrystal,
        [KeyItem("Cloaked Thunder")] CloakedThunder,
        [KeyItem("Eternal Blossom")] EternalBlossom,
        [KeyItem("Rare Document")] RareDocument,
        [KeyItem("Dummy 23")] Dummy23,
        [KeyItem("Dummy 24")] Dummy24,
        [KeyItem("Dummy 25")] Dummy25,
        [KeyItem("Dummy 26")] Dummy26,
        [KeyItem("Dummy 27")] Dummy27,
        [KeyItem("Style Recipe")] StyleRecipe,
        [KeyItem("Moon Recipe")] MoonRecipe,
        [KeyItem("Queen Recipe")] QueenRecipe,
        [KeyItem("King Recipe")] KingRecipe,
        [KeyItem("Ultimate Recipe")] UltimateRecipe,
        [Keyblade("StarSeeker")] StarSeeker,
        [Keyblade("Hidden Dragon")] HiddenDragon,
        [Staff("Save the Queen")] SaveTheQueen,
        [Shield("Save the King")] SaveTheKing,
        [Keyblade("Hero's Crest")] HeroCrest,
        [Keyblade("Monochrome")] Monochrome,
        [Keyblade("Follow the Wind")] FollowTheWind,
        [Keyblade("Circle of Life")] CircleOfLife,
        [Keyblade("Photon Debugger")] PhotonDebugger,
        [Keyblade("Gull Wing")] GullWing,
        [Keyblade("Rumbling Rose")] RumblingRose,
        [Keyblade("Guardian Soul")] GuardianSoul,
        [Keyblade("Wishing Lamp")] WishingLamp,
        [Keyblade("Decisive Pumpkin")] DecisivePumpkin,
        [Keyblade("Sleeping Lion")] SleepingLion,
        [Keyblade("Sweet Memories")] SweetMemories,
        [Keyblade("Mysterious Abyss")] MysteriousAbyss,
        [Keyblade("Fatal Crest")] FatalCrest,
        [Keyblade("Bond of Flame")] BondOfFlame,
        [Keyblade("Fenrir")] Fenrir,
        [Keyblade("Ultima Weapon")] UltimaWeapon,
        [Unused] Unused272,
        [Unused] Unused273,
        [Keyblade("Save the Queen+")] SaveTheQueenPlys,
        [Shield("Save the King+")] SaveTheKingPlus,
        [KeyItem("Promise Charm")] PromiseCharm,
        [KeyItem("Munny Pouch")] MunnyPouch2,
        [KeyItem("Hades Cup Trophy")] HadesCupTrophy,
        [KeyItem("\"The Struggle\" Trophy")] TheStruggleTrophy,
        [Unused] Unused280,
        [Keyblade("Winner's Proof")] WinnerProof,
        [Staff("Centurion")] Centurion,
        [Staff("Centurion+")] CenturionPlus,
        [Staff("Plain Mushroom")] PlainMushroom,
        [Staff("Plain Mushroom+")] PlainMushroomPlus,
        [Staff("Precious Mushroom")] PreciousMushroom,
        [Staff("Precious Mushroom+")] PreciousMushroomPlus,
        [Staff("Premium Mushroom")] PremiumMushroom,
        [Shield("Frozen Pride")] FrozenPride,
        [Shield("Frozen Pride+")] FrozenPridePlus,
        [Shield("Joyous Mushroom")] JoyousMushroom,
        [Shield("Joyous Mushroom+")] JoyousMushroomPlus,
        [Shield("Majestic Mushroom")] MajesticMushroom,
        [Shield("Majestic Mushroom+")] MajesticMushroomPlus,
        [Shield("Ultimate Mushroom")] UltimateMushroom,
        [Synthesis("Remembrance Shard")] RemembranceShard,
        [Synthesis("Remembrance Stone")] RemembranceStone,
        [Synthesis("Remembrance Gem")] RemembranceGem,
        [Synthesis("Remembrance Crystal")] RemembranceCrystal,
        [Synthesis("Tranquility Shard")] TranquilityShard,
        [Synthesis("Tranquility Stone")] TranquilityStone,
        [Synthesis("Tranquility Gem")] TranquilityGem,
        [Synthesis("Tranquility Crystal")] TranquilityCrystalss,
        [Synthesis("Lost Illusion")] LostIllusion,
        [Synthesis("Manifest Illusion")] ManifestIllusion,
        [KeyItem("Proof of Connection")] ProofOfConnection,
        [KeyItem("Proof of Nonexistence")] ProofOfNonexistence,
        [KeyItem("Proof of Peace")] ProofOfPeace,
        [Accessory("Executive's Ring")] ExecutiveRing,
        [Staff("Shaman's Relic+")] ShamanRelicPlus,
        [Shield("Akashic Record+")] AkashicRecordPlus,
    }
}
