using KHSave.Attributes;

namespace KHSave.LibBbs.Types
{
    public enum WeaponType : ushort
    {
        [Keyblade("Wayward Wind")] WaywardWind = 0x0001,
        [Keyblade("Rainfell")] Rainfell = 0x0002,
        [Keyblade("Earthshaker")] Earthshaker = 0x0003,
        [Keyblade("Treasure Trove (Ventus)")] TreasureTroveVentus = 0x0004,
        [Keyblade("Treasure Trove (Aqua)")] TreasureTroveAqua = 0x0005,
        [Keyblade("Treasure Trove (Terra)")] TreasureTroveTerra = 0x0006,
        [Keyblade("Stroke of Midnight (Ventus)")] StrokeofMidnightVentus = 0x0007,
        [Keyblade("Stroke of Midnight (Aqua)")] StrokeofMidnightAqua = 0x0008,
        [Keyblade("Stroke of Midnight (Terra)")] StrokeofMidnightTerra = 0x0009,
        [Keyblade("Fairy Stars (Ventus)")] FairyStarsVentus = 0x000A,
        [Keyblade("Fairy Stars (Aqua)")] FairyStarsAqua = 0x000B,
        [Keyblade("Fairy Stars (Terra)")] FairyStarsTerra = 0x000C,
        [Keyblade("Victory Line (Ventus)")] VictoryLineVentus = 0x000D,
        [Keyblade("Victory Line (Aqua)")] VictoryLineAqua = 0x000E,
        [Keyblade("Victory Line (Terra)")] VictoryLineTerra = 0x000F,
        [Keyblade("Mark of a Hero (Ventus)")] MarkofaHeroVentus = 0x0010,
        [Keyblade("Mark of a Hero (Aqua)")] MarkofaHeroAqua = 0x0011,
        [Keyblade("Mark of a Hero (Terra)")] MarkofaHeroTerra = 0x0012,
        [Keyblade("Hyperdrive (Ventus)")] HyperdriveVentus = 0x0013,
        [Keyblade("Hyperdrive (Aqua)")] HyperdriveAqua = 0x0014,
        [Keyblade("Hyperdrive (Terra)")] HyperdriveTerra = 0x0015,
        [Keyblade("Pixie Petal (Ventus)")] PixiePetalVentus = 0x0016,
        [Keyblade("Pixie Petal (Aqua)")] PixiePetalAqua = 0x0017,
        [Keyblade("Pixie Petal (Terra)")] PixiePetalTerra = 0x0018,
        [Keyblade("Ultima Weapon (Ventus)")] UltimaWeaponVentus = 0x0019,
        [Keyblade("Ultima Weapon (Aqua)")] UltimaWeaponAqua = 0x001A,
        [Keyblade("Ultima Weapon (Terra)")] UltimaWeaponTerra = 0x001B,
        [Keyblade("Sweetstack (Ventus)")] SweetstackVentus = 0x001C,
        [Keyblade("Sweetstack (Aqua)")] SweetstackAqua = 0x001D,
        [Keyblade("Sweetstack (Terra)")] SweetstackTerra = 0x001E,
        [Keyblade("Frolic Flame")] FrolicFlame = 0x0021,
        [Keyblade("Lost Memory")] LostMemory = 0x0022,
        [Keyblade("Destiny's Embrace")] DestinysEmbrace = 0x0023,
        [Keyblade("Stormfall")] Stormfall = 0x0024,
        [Keyblade("Brightcrest")] Brightcrest = 0x0025,
        [Keyblade("Darkgnaw")] Darkgnaw = 0x0026,
        [Keyblade("Ends of the Earth")] EndsoftheEarth = 0x0027,
        [Keyblade("Chaos Ripper")] ChaosRipper = 0x0028,
        [Keyblade("Void Gear (Ventus)")] VoidGearVentus = 0x0029,
        [Keyblade("Void Gear (Aqua)")] VoidGearAqua = 0x002A,
        [Keyblade("Void Gear (Terra)")] VoidGearTerra = 0x002B,
        [Keyblade("No Name (Ventus)")] NoNameVentus = 0x002C,
        [Keyblade("No Name (Aqua)")] NoNameAqua = 0x002D,
        [Keyblade("No Name (Terra)")] NoNameTerra = 0x002E,
        [Keyblade("Royal Radiance (Ventus)")] RoyalRadianceVentus = 0x002F,
        [Keyblade("Royal Radiance (Aqua)")] RoyalRadianceAqua = 0x0030,
        [Keyblade("Royal Radiance (Terra)")] RoyalRadianceTerra = 0x0031,
        [Keyblade("Master's Defender")] MastersDefender = 0x0032,
        [Keyblade("Ultima Cannon")] UltimaCannon = 0x0033,

    }
}
