using KHSave.LibRecom.Types;
using Xe.BinaryMapper;

namespace KHSave.LibRecom
{
    public class DataRecomTable1
    {
        [Data] public byte Unknown00 { get; set; }
        [Data] public byte Unknown01 { get; set; }
        [Data] public byte Unknown02 { get; set; }
        [Data] public byte Unknown03 { get; set; }
        [Data] public byte Unknown04 { get; set; }
        [Data] public byte Unknown05 { get; set; }
        [Data] public byte Unknown06 { get; set; }
        [Data] public byte Unknown07 { get; set; }
        [Data] public byte Unknown08 { get; set; }
        [Data] public byte Unknown09 { get; set; }
        [Data] public byte Unknown0a { get; set; }
        [Data] public byte Unknown0b { get; set; }
        [Data] public byte Unknown0c { get; set; }
        [Data] public byte Unknown0d { get; set; }
        [Data] public byte Unknown0e { get; set; }
        [Data] public byte Unknown0f { get; set; }
        [Data] public byte Unknown10 { get; set; }
        [Data] public byte Unknown11 { get; set; }
        [Data] public byte Unknown12 { get; set; }
        [Data] public byte Unknown13 { get; set; }
        [Data] public byte Unknown14 { get; set; }
        [Data] public byte Unknown15 { get; set; }
        [Data] public byte Unknown16 { get; set; }
        [Data] public byte Unknown17 { get; set; }
        [Data] public byte Unknown18 { get; set; }
        [Data] public byte Unknown19 { get; set; }
        [Data] public byte Unknown1a { get; set; }
        [Data] public byte Unknown1b { get; set; }
        [Data] public byte Unknown1c { get; set; }
        [Data] public byte Unknown1d { get; set; }
        [Data] public byte Unknown1e { get; set; }
        [Data] public byte Unknown1f { get; set; }
        [Data] public byte Unknown20 { get; set; }
        [Data] public byte Unknown21 { get; set; }
        [Data] public byte Unknown22 { get; set; }
        [Data] public byte Unknown23 { get; set; }
        [Data] public byte Unknown24 { get; set; }
        [Data] public byte Unknown25 { get; set; }
        [Data] public byte Unknown26 { get; set; }
        [Data] public byte Unknown27 { get; set; }
        [Data] public byte Unknown28 { get; set; }
        [Data] public byte Unknown29 { get; set; }
        [Data] public byte Unknown2a { get; set; }
        [Data] public byte Unknown2b { get; set; }
        [Data] public byte Unknown2c { get; set; }
        [Data] public byte Unknown2d { get; set; }
        [Data] public byte Unknown2e { get; set; }
        [Data] public byte Unknown2f { get; set; }
        [Data] public byte Unknown30 { get; set; }
        [Data] public byte Unknown31 { get; set; }
        [Data] public byte Unknown32 { get; set; }
        [Data] public byte Unknown33 { get; set; }
        [Data] public byte Unknown34 { get; set; }
        [Data] public byte Unknown35 { get; set; }
        [Data] public byte Unknown36 { get; set; }
        [Data] public byte Unknown37 { get; set; }
        [Data] public byte Unknown38 { get; set; }
        [Data] public byte Unknown39 { get; set; }
        [Data] public byte Unknown3a { get; set; }
        [Data] public byte Unknown3b { get; set; }
        [Data] public byte Unknown3c { get; set; }
        [Data] public byte Unknown3d { get; set; }
        [Data] public byte Unknown3e { get; set; }
        [Data] public byte Unknown3f { get; set; }
        [Data] public byte Unknown40 { get; set; }
        [Data] public byte Unknown41 { get; set; }
        [Data] public byte Unknown42 { get; set; }
        [Data] public byte Unknown43 { get; set; }
        [Data] public byte Unknown44 { get; set; }
        [Data] public byte Unknown45 { get; set; }
        [Data] public byte Unknown46 { get; set; }
        [Data] public byte Unknown47 { get; set; }
        [Data] public byte Unknown48 { get; set; }
        [Data] public byte Unknown49 { get; set; }
        [Data] public byte Unknown4a { get; set; }
        [Data] public byte Unknown4b { get; set; }
        [Data] public byte Unknown4c { get; set; }
        [Data] public byte Unknown4d { get; set; }
        [Data] public byte Unknown4e { get; set; }
        [Data] public byte Unknown4f { get; set; }
        [Data] public byte Unknown50 { get; set; }
        [Data] public byte Unknown51 { get; set; }
        [Data] public byte Unknown52 { get; set; }
        [Data] public byte Unknown53 { get; set; }
        [Data] public byte Unknown54 { get; set; }
        [Data] public byte Unknown55 { get; set; }
        [Data] public byte Unknown56 { get; set; }
        [Data] public byte Unknown57 { get; set; }
        [Data] public byte Unknown58 { get; set; }
        [Data] public byte Unknown59 { get; set; }
        [Data] public byte Unknown5a { get; set; }
        [Data] public byte Unknown5b { get; set; }
        [Data] public byte Unknown5c { get; set; }
        [Data] public byte Unknown5d { get; set; }
        [Data] public byte Unknown5e { get; set; }
        [Data] public byte Unknown5f { get; set; }
        [Data] public PlayMode PlayMode { get; set; }
        [Data] public Difficulty Difficulty { get; set; }
        [Data] public SoundMode SoundMode { get; set; }
        [Data] public bool NoVibration { get; set; }
        [Data] public byte Unknown64 { get; set; }
        [Data] public byte Unknown65 { get; set; }
        [Data] public byte Unknown66 { get; set; }
        [Data] public byte Unknown67 { get; set; }
        [Data] public byte Unknown68 { get; set; }
        [Data] public byte Unknown69 { get; set; }
        [Data] public byte Unknown6a { get; set; }
        [Data] public byte Unknown6b { get; set; }
        [Data] public byte Unknown6c { get; set; }
        [Data] public byte Unknown6d { get; set; }
        [Data] public byte Unknown6e { get; set; }
        [Data] public byte Unknown6f { get; set; }
        [Data] public byte Unknown70 { get; set; }
        [Data] public byte Unknown71 { get; set; }
        [Data] public byte Unknown72 { get; set; }
        [Data] public byte Unknown73 { get; set; }
        [Data] public byte Unknown74 { get; set; }
        [Data] public byte Unknown75 { get; set; }
        [Data] public byte Unknown76 { get; set; }
        [Data] public byte Unknown77 { get; set; }
        [Data] public byte Unknown78 { get; set; }
        [Data] public byte Unknown79 { get; set; }
        [Data] public byte Unknown7a { get; set; }
        [Data] public byte Unknown7b { get; set; }
        [Data] public byte Unknown7c { get; set; }
        [Data] public byte Unknown7d { get; set; }
        [Data] public byte Unknown7e { get; set; }
        [Data] public byte Unknown7f { get; set; }
    }
}
