using KHSave.LibRecom.Models;
using Xe.BinaryMapper;

namespace KHSave.LibRecom
{
    public class DataRecomTable0
    {
        [Data(0)] public int Unknown00 { get; set; }
        [Data] public int Unknown01 { get; set; }
        [Data] public int Unknown02 { get; set; }
        [Data] public int Unknown03 { get; set; }
        [Data] public int Unknown04 { get; set; }
        [Data] public int Unknown05 { get; set; }
        [Data] public int Unknown06 { get; set; }
        [Data] public int Unknown07 { get; set; }
        [Data] public int Unknown08 { get; set; }
        [Data] public int Unknown09 { get; set; }
        [Data] public int Unknown0a { get; set; }
        [Data] public int Unknown0b { get; set; }
        [Data] public int Unknown0c { get; set; }
        [Data] public int Unknown0d { get; set; }
        [Data] public int Unknown0e { get; set; }
        [Data] public int Unknown0f { get; set; }
        [Data] public int Unknown10 { get; set; }
        [Data] public int Unknown11 { get; set; }
        [Data] public int Unknown12 { get; set; }
        [Data] public int Unknown13 { get; set; }
        [Data] public int Unknown14 { get; set; }
        [Data] public int Unknown15 { get; set; }
        [Data] public int Unknown16 { get; set; }
        [Data] public int Unknown17 { get; set; }
        [Data] public int Unknown18 { get; set; }
        [Data] public int Unknown19 { get; set; }
        [Data] public int Unknown1a { get; set; }
        [Data] public int Unknown1b { get; set; }
        [Data] public int Unknown1c { get; set; }
        [Data] public int Unknown1d { get; set; }
        [Data] public int Unknown1e { get; set; }
        [Data] public int Unknown1f { get; set; }
        [Data] public int Unknown20 { get; set; }
        [Data] public int Unknown21 { get; set; }
        [Data] public int Unknown22 { get; set; }
        [Data] public int Unknown23 { get; set; }
        [Data] public int Unknown24 { get; set; }
        [Data] public int Unknown25 { get; set; }
        [Data] public int Unknown26 { get; set; }
        [Data] public int Unknown27 { get; set; }
        [Data] public int Unknown28 { get; set; }
        [Data] public int Unknown29 { get; set; }
        [Data] public int Unknown2a { get; set; }
        [Data] public int Unknown2b { get; set; }
        [Data] public int Unknown2c { get; set; }
        [Data] public int Unknown2d { get; set; }
        [Data] public int Unknown2e { get; set; }
        [Data] public int Unknown2f { get; set; }
        [Data] public int Unknown30 { get; set; }
        [Data] public int Unknown31 { get; set; }
        [Data] public int Unknown32 { get; set; }
        [Data] public int Unknown33 { get; set; }
        [Data] public int Unknown34 { get; set; }
        [Data] public int Unknown35 { get; set; }
        [Data] public int Unknown36 { get; set; }
        [Data] public int Unknown37 { get; set; }
        [Data] public int Unknown38 { get; set; }
        [Data] public int Unknown39 { get; set; }
        [Data] public int Unknown3a { get; set; }
        [Data] public int Unknown3b { get; set; }
        [Data] public int Unknown3c { get; set; }
        [Data] public int Unknown3d { get; set; }
        [Data] public int Unknown3e { get; set; }
        [Data] public int Unknown3f { get; set; }
        [Data] public int Unknown40 { get; set; }
        [Data] public int Unknown41 { get; set; }
        [Data] public int Unknown42 { get; set; }
        [Data] public int Unknown43 { get; set; }
        [Data] public int Unknown44 { get; set; }
        [Data] public int Unknown45 { get; set; }
        [Data] public int Unknown46 { get; set; }
        [Data] public int Unknown47 { get; set; }
        [Data] public int Unknown48 { get; set; }
        [Data] public int Unknown49 { get; set; }
        [Data] public int Unknown4a { get; set; }
        [Data] public int Unknown4b { get; set; }
        [Data] public int Unknown4c { get; set; }
        [Data] public int Unknown4d { get; set; }
        [Data] public int Unknown4e { get; set; }
        [Data] public int Unknown4f { get; set; }
        [Data] public int Unknown50 { get; set; }
        [Data] public int Unknown51 { get; set; }
        [Data] public int Unknown52 { get; set; }
        [Data] public int Unknown53 { get; set; }
        [Data] public int Unknown54 { get; set; }
        [Data] public int Unknown55 { get; set; }
        [Data] public int Unknown56 { get; set; }
        [Data] public int Unknown57 { get; set; }
        [Data] public int Unknown58 { get; set; }
        [Data] public int Unknown59 { get; set; }
        [Data] public int Unknown5a { get; set; }
        [Data] public int Unknown5b { get; set; }
        [Data] public int Unknown5c { get; set; }
        [Data] public int Unknown5d { get; set; }
        [Data] public int Unknown5e { get; set; }
        [Data] public int Unknown5f { get; set; }
        [Data] public int Unknown60 { get; set; }
        [Data] public int Unknown61 { get; set; }
        [Data] public int Unknown62 { get; set; }
        [Data] public int Unknown63 { get; set; }
        [Data] public int Unknown64 { get; set; }
        [Data] public int Unknown65 { get; set; }
        [Data] public int Unknown66 { get; set; }
        [Data] public int Unknown67 { get; set; }
        [Data] public int Unknown68 { get; set; }
        [Data] public int Unknown69 { get; set; }
        [Data] public int Unknown6a { get; set; }
        [Data] public int Unknown6b { get; set; }
        [Data] public int Unknown6c { get; set; }
        [Data] public int Unknown6d { get; set; }
        [Data] public int Unknown6e { get; set; }
        [Data] public int Unknown6f { get; set; }
        [Data] public int Unknown70 { get; set; }
        [Data] public int Unknown71 { get; set; }
        [Data] public int Unknown72 { get; set; }
        [Data] public int Unknown73 { get; set; }
        [Data] public int Unknown74 { get; set; }
        [Data] public int Unknown75 { get; set; }
        [Data] public int Unknown76 { get; set; }
        [Data] public int Unknown77 { get; set; }
        [Data] public int Unknown78 { get; set; }
        [Data] public int Unknown79 { get; set; }
        [Data] public int Unknown7a { get; set; }
        [Data] public int Unknown7b { get; set; }
        [Data] public int Unknown7c { get; set; }
        [Data] public int Unknown7d { get; set; }
        [Data] public int Unknown7e { get; set; }
        [Data] public int Unknown7f { get; set; }
        [Data] public int Unknown80 { get; set; }
        [Data] public int Unknown81 { get; set; }
        [Data] public int Unknown82 { get; set; }
        [Data] public int Unknown83 { get; set; }
        [Data] public int Unknown84 { get; set; }
        [Data] public int Unknown85 { get; set; }
        [Data] public int Unknown86 { get; set; }
        [Data] public int Unknown87 { get; set; }
        [Data] public int Unknown88 { get; set; }
        [Data] public int Unknown89 { get; set; }
        [Data] public int Unknown8a { get; set; }
        [Data] public int Unknown8b { get; set; }
        [Data] public int Unknown8c { get; set; }
        [Data] public int Unknown8d { get; set; }
        [Data] public int Unknown8e { get; set; }
        [Data] public int Unknown8f { get; set; }
        [Data] public int Unknown90 { get; set; }
        [Data] public int Unknown91 { get; set; }
        [Data] public int Unknown92 { get; set; }
        [Data] public int Unknown93 { get; set; }
        [Data] public int Unknown94 { get; set; }
        [Data] public int Unknown95 { get; set; }
        [Data] public int Unknown96 { get; set; }
        [Data] public int Unknown97 { get; set; }
        [Data] public int Unknown98 { get; set; }
        [Data] public int Unknown99 { get; set; }
        [Data] public int Unknown9a { get; set; }
        [Data] public int Unknown9b { get; set; }
        [Data] public int Unknown9c { get; set; }
        [Data] public int Unknown9d { get; set; }
        [Data] public int Unknown9e { get; set; }
        [Data] public int Unknown9f { get; set; }
        [Data] public int UnknownA0 { get; set; }
        [Data] public int UnknownA1 { get; set; }
        [Data] public int UnknownA2 { get; set; }
        [Data] public int UnknownA3 { get; set; }
        [Data] public int UnknownA4 { get; set; }
        [Data] public int UnknownA5 { get; set; }
        [Data] public int UnknownA6 { get; set; }
        [Data] public int UnknownA7 { get; set; }
        [Data] public int UnknownA8 { get; set; }
        [Data] public int UnknownA9 { get; set; }
        [Data] public int UnknownAa { get; set; }
        [Data] public int UnknownAb { get; set; }
        [Data] public int UnknownAc { get; set; }
        [Data] public int UnknownAd { get; set; }
        [Data] public int UnknownAe { get; set; }
        [Data] public int UnknownAf { get; set; }
        [Data] public int UnknownB0 { get; set; }
        [Data] public int UnknownB1 { get; set; }
        [Data] public int UnknownB2 { get; set; }
        [Data] public int UnknownB3 { get; set; }
        [Data] public int UnknownB4 { get; set; }
        [Data] public int UnknownB5 { get; set; }
        [Data] public int UnknownB6 { get; set; }
        [Data] public int UnknownB7 { get; set; }
        [Data] public int UnknownB8 { get; set; }
        [Data] public int UnknownB9 { get; set; }
        [Data] public int UnknownBa { get; set; }
        [Data] public int UnknownBb { get; set; }
        [Data] public int UnknownBc { get; set; }
        [Data] public int UnknownBd { get; set; }
        [Data] public int UnknownBe { get; set; }
        [Data] public int UnknownBf { get; set; }
        [Data] public int UnknownC0 { get; set; }
        [Data] public StoryFlag SoraStoryFlag { get; set; }
        [Data] public StoryFlag RikuStoryFlag { get; set; }
        [Data] public TutorialFlags Tutorial { get; set; }
        [Data] public CardFlags UnlockedCards { get; set; }
        [Data] public Kh2CardFlags UnlockedKh2Cards { get; set; }
        [Data] public FriendsFlags UnlockedFriends { get; set; }
        [Data] public PoohFlags PoohFlags { get; set; }
        [Data] public int UnknownC7 { get; set; }
        [Data] public int UnknownC8 { get; set; }
        [Data] public int UnknownC9 { get; set; }
        [Data] public int UnknownCa { get; set; }
        [Data] public int UnknownCb { get; set; }
        [Data] public int UnknownCc { get; set; }
        [Data] public int UnknownCd { get; set; }
        [Data] public int UnknownCe { get; set; }
        [Data] public int UnknownCf { get; set; }
        [Data] public int UnknownD0 { get; set; }
        [Data] public int UnknownD1 { get; set; }
        [Data] public int UnknownD2 { get; set; }
        [Data] public int UnknownD3 { get; set; }
        [Data] public int UnknownD4 { get; set; }
        [Data] public int UnknownD5 { get; set; }
        [Data] public int UnknownD6 { get; set; }
        [Data] public int UnknownD7 { get; set; }
        [Data] public int UnknownD8 { get; set; }
        [Data] public int UnknownD9 { get; set; }
        [Data] public int UnknownDa { get; set; }
        [Data] public int UnknownDb { get; set; }
        [Data] public int UnknownDc { get; set; }
        [Data] public int UnknownDd { get; set; }
        [Data] public int UnknownDe { get; set; }
        [Data] public int UnknownDf { get; set; }
        [Data] public int UnknownE0 { get; set; }
        [Data] public int UnknownE1 { get; set; }
        [Data] public int UnknownE2 { get; set; }
        [Data] public int UnknownE3 { get; set; }
        [Data] public int UnknownE4 { get; set; }
        [Data] public int UnknownE5 { get; set; }
        [Data] public int UnknownE6 { get; set; }
        [Data] public int UnknownE7 { get; set; }
        [Data] public int UnknownE8 { get; set; }
        [Data] public int UnknownE9 { get; set; }
        [Data] public int UnknownEa { get; set; }
        [Data] public int UnknownEb { get; set; }
        [Data] public int UnknownEc { get; set; }
        [Data] public int UnknownEd { get; set; }
        [Data] public int UnknownEe { get; set; }
        [Data] public int UnknownEf { get; set; }
        [Data] public int UnknownF0 { get; set; }
        [Data] public int UnknownF1 { get; set; }
        [Data] public int UnknownF2 { get; set; }
        [Data] public int UnknownF3 { get; set; }
        [Data] public int UnknownF4 { get; set; }
        [Data] public int UnknownF5 { get; set; }
        [Data] public int UnknownF6 { get; set; }
        [Data] public int UnknownF7 { get; set; }
        [Data] public int UnknownF8 { get; set; }
        [Data] public int UnknownF9 { get; set; }
        [Data] public int UnknownFa { get; set; }
        [Data] public int UnknownFb { get; set; }
        [Data] public int UnknownFc { get; set; }
        [Data] public int UnknownFd { get; set; }
        [Data] public int UnknownFe { get; set; }
        [Data] public int UnknownFf { get; set; }
    }
}
