using KHSave.Attributes;
using KHSave.LibRecom.Attributes;

namespace KHSave.LibRecom.Types
{
    public enum CardType
    {
        [Info] Empty,
        [Unused] Unused,

        [CardWeapon("Kingdom Key")] KingdomKey,
        [CardWeapon("Three Wishes")] ThreeWishes,
        [CardWeapon("Crabclaw")] Crabclaw,
        [CardWeapon("Pumpkinhead")] Pumpkinhead,
        [CardWeapon("Fairy Harp")] FairyHarp,
        [CardWeapon("Wishing Star")] WishingStar,
        [CardWeapon("Spellbinder")] Spellbinder,
        [CardWeapon("Metal Chocobo")] MetalChocobo,
        [CardWeapon("Olympia")] Olympia,
        [CardWeapon("Lionheart")] Lionheart,
        [CardWeapon("Lady Luck")] LadyLuck,
        [CardWeapon("Divine Rose")] DivineRose,
        [CardWeapon("Oathkeeper")] Oathkeeper,
        [CardWeapon("Oblivion")] Oblivion,
        [CardWeapon("Ultima Weapon")] UltimaWeapon,
        [CardWeapon("Diamond Dust")] DiamondDust,
        [CardWeapon("One-Winged Angel")] OneWingedAngel,
        [CardWeapon("Soul Eater")] SoulEater,
        [CardWeapon("Star Seeker")] StarSeeker,
        [CardWeapon("Monochrome")] Monochrome,
        [CardWeapon("Follow the Wind")] FollowTheWind,
        [CardWeapon("Hidden Dragon")] HiddenDragon,
        [CardWeapon("Photon Debugger")] PhotonDebugger,
        [CardWeapon("Bond of Flame")] BondOfFlame,

        [CardMagic] Fire,
        [CardMagic] Blizzard,
        [CardMagic] Thunder,
        [CardMagic] Cure,
        [CardMagic] Gravity,
        [CardMagic] Stop,
        [CardMagic] Aero,

        [Unused] [CardMagic("-")] DummyMagic1,
        [Unused] [CardMagic("-")] DummyMagic2,

        [CardSummon("Simba")] Simba,
        [CardSummon("Genie")] Genie,
        [CardSummon("Bambi")] Bambi,
        [CardSummon("Dumbo")] Dumbo,
        [CardSummon("Tinker Bell")] TinkerBell,
        [CardSummon("Mushu")] Mushu,
        [CardSummon("Cloud")] Cloud,

        [CardItem("Potion")] Potion,
        [CardItem("Hi-Potion")] HiPotion,
        [CardItem("Mega-Potion")] MegaPotion,
        [CardItem("Ether")] Ether,
        [CardItem("Mega-Ether")] MegaEther,
        [CardItem("Elixir")] Elixir,
        [CardItem("Megalixir")] Megalixir,

        [CardMapRed("Tranquil Darkness")] TranquilDarkness,
        [CardMapRed("Teeming Darkness")] TeemingDarkness,
        [CardMapRed("Feeble Darkness")] FeebleDarkness,
        [CardMapRed("Almighty Darkness")] AlmightyDarkness,
        [CardMapRed("Sleeping Darkness")] SleepingDarkness,
        [CardMapRed("Looming Darkness")] LoomingDarkness,
        [CardMapRed("Premium Room")] PremiumRoom,
        [CardMapRed("White Room")] WhiteRoom,
        [CardMapRed("Black Room")] BlackRoom,
        [CardMapRed("Bottomless Darkness")] BottomlessDarkness,
        [CardMapRed("Roulette Darkness")] RouletteDarkness,

        [CardMapGreen("Martial Waking")] MartialWaking,
        [CardMapGreen("Sorcerous Waking")] SorcerousWaking,
        [CardMapGreen("Alchemic Waking")] AlchemicWaking,
        [CardMapGreen("Meeting Ground")] MeetingGround,
        [CardMapGreen("Stagnant Space")] StagnantSpace,
        [CardMapGreen("Strong Initiative")] StrongInitiative,
        [CardMapGreen("Lasting Daze")] LastingDaze,

        [CardMapBlue("Calm Bounty")] CalmBounty,
        [CardMapBlue("Guarded Trove")] GuardedTrove,
        [CardMapBlue("False Bounty")] FalseBounty,
        [CardMapBlue("Moment's Reprieve")] MomentsReprieve,
        [CardMapBlue("Mingling Worlds")] MinglingWorlds,
        [CardMapBlue("Moogle Room")] MoogleRoom,

        [CardMapSpecial("Random Joker")] RandomJoker,

        [CardEnemy("Shadow")] Shadow,
        [CardEnemy("Soldier")] Soldier,
        [CardEnemy("Large Body")] LargeBody,
        [CardEnemy("Red Nocturne")] RedNocturne,
        [CardEnemy("Blue Rhapsody")] BlueRhapsody,
        [CardEnemy("Yellow Opera")] YellowOpera,
        [CardEnemy("Green Requiem")] GreenRequiem,
        [CardEnemy("Powerwild")] Powerwild,
        [CardEnemy("Bouncywild")] Bouncywild,
        [CardEnemy("Air Soldier")] AirSoldier,
        [CardEnemy("Bandit")] Bandit,
        [CardEnemy("Fat Bandit")] FatBandit,
        [CardEnemy("Barrel Spider")] BarrelSpider,
        [CardEnemy("Search Ghost")] SearchGhost,
        [CardEnemy("Sea Neon")] SeaNeon,
        [CardEnemy("Screwdiver")] Screwdiver,
        [CardEnemy("Aquatank")] Aquatank,
        [CardEnemy("Wight Knight")] WightKnight,
        [CardEnemy("Gargoyle")] Gargoyle,
        [CardEnemy("Pirate")] Pirate,
        [CardEnemy("Air Pirate")] AirPirate,
        [CardEnemy("Darkball")] Darkball,
        [CardEnemy("Defender")] Defender,
        [CardEnemy("Wyvern")] Wyvern,
        [CardEnemy("Wizard")] Wizard,
        [CardEnemy("Neoshadow")] Neoshadow,
        [CardEnemy("White Mushroom")] WhiteMushroom,
        [CardEnemy("Black Fungus")] BlackFungus,
        [CardEnemy("Creeper Plant")] CreeperPlant,
        [CardEnemy("Tornado Step")] TornadoStep,
        [CardEnemy("Crescendo")] Crescendo,
        [CardEnemy("Guard Armor")] GuardArmor,
        [CardEnemy("Parasite Cage")] ParasiteCage,
        [CardEnemy("Trickmaster")] Trickmaster,
        [CardEnemy("Darkside")] Darkside,
        [CardEnemy("Card Soldier")] CardSoldier,
        [CardEnemy("Hades")] Hades,
        [CardEnemy("Jafar")] Jafar,
        [CardEnemy("Oogie Boogie")] OogieBoogie,
        [CardEnemy("Ursula")] Ursula,
        [CardEnemy("Hook")] Hook,
        [CardEnemy("Dragon Maleficient")] DragonMaleficient,
        [CardEnemy("Riku")] Riku,
        [CardEnemy("Axel")] Axel,
        [CardEnemy("Larxene")] Larxene,
        [CardEnemy("Vexen")] Vexen,
        [CardEnemy("Marluxia")] Marluxia,
        [CardEnemy("Lexaeus")] Lexaeus,
        [CardEnemy("Ansem")] Ansem,
        [CardEnemy("Zexion")] Zexion,
        [CardEnemy("Xemnas")] Xemnas,
        [CardEnemy("Xigbar")] Xigbar,
        [CardEnemy("Xaldin")] Xaldin,
        [CardEnemy("Saïx")] Saix,
        [CardEnemy("Demyx")] Demyx,
        [CardEnemy("Luxord")] Luxord,
        [CardEnemy("Roxas")] Roxas,
        [CardSpecial("Gold Card")] GoldCard,
        [CardSpecial("Platinum Card")] PlatinumCard,
    }
}
