using KHSave.Attributes;

namespace KHSave.LibPersona3.Types
{
    public enum ExpendableItems
    {
        [Consumable] Dummy,
        [Consumable] Medicine,
        [Consumable("Medical Powder")] MedicalPowder,
        [Consumable("Bead")] Bead,
        [Consumable("Snuff Soul")] SnuffSoul,
        [Consumable("Chewing Soul")] ChewingSoul,
        [Consumable("Precious Egg")] PreciousEgg,
        [Consumable("Soma")] Soma,
        [Consumable("Dis-Poison")] DisPoison,
        [Consumable("Revival Bead")] RevivalBead,
        [Consumable("Balm of Life")] BalmOfLife,
        [Consumable("Me Patra Gem")] MePatraGem,
        [Consumable("Muscle Drink")] MuscleDrink,
        [Consumable("Odd Morsel")] OddMorsel,
        [Consumable("Rancid Gravy")] RancidGravy,
        [Consumable("Powerful Drug")] PowerfulDrug,
        [Unused] Consumable4010,
        [Unused] Consumable4011,
        [Unused] Consumable4012,
        [Consumable("Dis-Rage")] DisRage,
        [Consumable("Dis-Charm")] DisCharm,
        [Unused] Consumable4015,
        [Unused] Consumable4016,
        [Unused] Consumable4017,
        [Unused] Consumable4018,
        [Unused] Consumable4019,
        [Unused] Consumable401A,
        [Unused] Consumable401B,
        [Unused] Consumable401C,
        [Unused] Consumable401D,
        [Unused] Consumable401E,
        [Unused] Consumable401F,
        [Consumable("Patra Gem")] PatraGem,
        [Consumable("Traesto Gem")] TraestoGem,
        [Consumable("Bead Chain")] BeadChain,
        [Consumable("Magic Mirror")] MagicMirror,
        [Consumable("Attack Mirror")] AttackMirror,
        [Consumable("Dekaja Gem")] DekajaGem,
        [Consumable("Dekunda Gem")] DekundaGem,
        [Consumable("Homunculus")] Homunculus,
        [Consumable("Plume of Dusk")] PlumeOfDusk,
        [Consumable("Agilao Gem")] AgilaoGem,
        [Consumable("Maragi Gem")] MaragiGem,
        [Consumable("Bufula Gem")] BufulaGem,
        [Consumable("Mabufu Gem")] MabufuGem,
        [Consumable("Garula Gem")] GarulaGem,
        [Consumable("Magaru Gem")] MagaruGem,
        [Consumable("Zionga Gem")] ZiongaGem,
        [Consumable("Mazio Gem")] MazioGem,
        [Consumable("Megido Gem")] MegidoGem,
    }
}
