using KHSave.Attributes;

namespace KHSave.LibPersona3.Types
{
    public class SkillAttribute : InfoAttribute
    {
        public SkillAttribute(string name = null) : base(name) { }
    }
    public class HitSkillAttribute : SkillAttribute
    {
        public HitSkillAttribute(string name = null) : base(name) { }
    }
    public class GunSkillAttribute : SkillAttribute
    {
        public GunSkillAttribute(string name = null) : base(name) { }
    }
    public class FireSkillAttribute : SkillAttribute
    {
        public FireSkillAttribute(string name = null) : base(name) { }
    }
    public class IceSkillAttribute : SkillAttribute
    {
        public IceSkillAttribute(string name = null) : base(name) { }
    }
    public class WindSkillAttribute : SkillAttribute
    {
        public WindSkillAttribute(string name = null) : base(name) { }
    }
    public class ThunderSkillAttribute : SkillAttribute
    {
        public ThunderSkillAttribute(string name = null) : base(name) { }
    }
    public class BlessSkillAttribute : SkillAttribute
    {
        public BlessSkillAttribute(string name = null) : base(name) { }
    }
    public class DeathSkillAttribute : SkillAttribute
    {
        public DeathSkillAttribute(string name = null) : base(name) { }
    }
    public class AlmightySkillAttribute : SkillAttribute
    {
        public AlmightySkillAttribute(string name = null) : base(name) { }
    }
    public class SupportSkillAttribute : SkillAttribute
    {
        public SupportSkillAttribute(string name = null) : base(name) { }
    }
    public class AutoSkillAttribute : SkillAttribute
    {
        public AutoSkillAttribute(string name = null) : base(name) { }
    }
    public class PoisonSkillAttribute : SkillAttribute
    {
        public PoisonSkillAttribute(string name = null) : base(name) { }
    }
    public class HealSkillAttribute : SkillAttribute
    {
        public HealSkillAttribute(string name = null) : base(name) { }
    }

    public enum Skill : short
    {
        [Skill("-")] Empty,
        [FireSkill("Agi")] Agi,
        [FireSkill("Agilao")] Agilao,
        [FireSkill("Agidyne")] Agidyne,
        [FireSkill("Maragi")] Maragi,
        [FireSkill("Maragion")] Maragion,
        [FireSkill("Maragidyne")] Maragidyne,
        [FireSkill("Maralagidyne")] Maralagidyne, // FES, P3P
        [Unused] Skill008,
        [FireSkill("Ragnarok")] Ragnarok,
        [WindSkill("Garu")] Garu,
        [WindSkill("Garula")] Garula,
        [WindSkill("Garudyne")] Garudyne,
        [WindSkill("Magaru")] Magaru,
        [WindSkill("Magarula")] Magarula,
        [WindSkill("Magarudyne")] Magarudyne,
        [Unused] Skill010,
        [Unused] Skill011,
        [WindSkill("Panta Rhei")] PantaRhei,
        [IceSkill("Bufu")] Bufu,
        [IceSkill("Bufula")] Bufula,
        [IceSkill("Bufudyne")] Bufudyne,
        [IceSkill("Mabufu")] Mabufu,
        [IceSkill("Mabufula")] Mabufula,
        [IceSkill("Mabufudyne")] Mabufudyne,
        [Unused] Skill019,
        [Unused] Skill01A,
        [IceSkill("Niflheim")] Niflheim,
        [ThunderSkill("Zio")] Zio,
        [ThunderSkill("Zionga")] Zionga,
        [ThunderSkill("Ziodyne")] Ziodyne,
        [ThunderSkill("Mazio")] Mazio,
        [ThunderSkill("Mazionga")] Mazionga,
        [ThunderSkill("Maziodyne")] Maziodyne,
        [Unused] Skill022,
        [Unused] Skill023,
        [ThunderSkill("Thunder Reign")] ThunderReign,
        [AlmightySkill("Megido")] Megido,
        [AlmightySkill("Megidola")] Megidola,
        [AlmightySkill("Megidolaon")] Megidolaon,
        [AlmightySkill("Last Resort")] LastResort,
        [Unused] Skill029,
        [Unused] Skill02A,
        [AlmightySkill("Black Viper")] BlackViper,
        [AlmightySkill("Morning Star")] MorningStar,
        [BlessSkill("Hama")] Hama,
        [BlessSkill("Mahama")] Mahama,
        [BlessSkill("Hamaon")] Hamaon,
        [BlessSkill("Mahamaon")] Mahamaon,
        [Unused] Skill031,
        [BlessSkill("Samsara")] Samsara,
        [DeathSkill("Mudo")] Mudo,
        [DeathSkill("Mamudo")] Mamudo,
        [DeathSkill("Mudoon")] Mudoon,
        [DeathSkill("Mamudoon")] Mamudoon,
        [Unused] Skill037,
        [DeathSkill("Die for Me!")] DieforMe,
        [PoisonSkill("Marin Karin")] MarinKarin,
        [PoisonSkill("Sexy Dance")] SexyDance,
        [PoisonSkill("Bewilder")] Bewilder,
        [PoisonSkill("Eerie Sound")] EerieSound,
        [PoisonSkill("Pulinpa")] Pulinpa,
        [PoisonSkill("Tentarafoo")] Tentarafoo,
        [PoisonSkill("Evil Touch")] EvilTouch,
        [PoisonSkill("Evil Smile")] EvilSmile,
        [PoisonSkill("Ghastly Wail")] GhastlyWail,
        [PoisonSkill("Provoke")] Provoke,
        [PoisonSkill("Infuriate")] Infuriate,
        [PoisonSkill("Poisma")] Poisma,
        [PoisonSkill("Poison Mist")] PoisonMist,
        [PoisonSkill("Virus Breath")] VirusBreath,
        [Unused] Skill047,
        [Unused] Skill048,
        [AlmightySkill("Foul Breath")] FoulBreath,
        [AlmightySkill("Stagnant Air")] StagnantAir,
        [AlmightySkill("Life Drain")] LifeDrain,
        [AlmightySkill("Spirit Drain")] SpiritDrain,
        [Unused] Skill04D,
        [Unused] Skill04E,
        [Unused] Skill04F,
        [FireSkill("Maragidyne (Velvet)")] MaragidyneVelvet,
        [WindSkill("Magarudyne (Velvet)")] MagarudyneVelvet,
        [IceSkill("Mabufudyne (Velvet)")] MabufudyneVelvet,
        [ThunderSkill("Maziodyne (Velvet)")] MaziodyneVelvet,
        [AlmightySkill("Megidolaon (Velvet)")] MegidolaonVelvet,
        [BlessSkill("Mahamaon (Velvet)")] MahamaonVelvet,
        [DeathSkill("Mamudoon (Velvet)")] MamudoonVelvet,
        [PoisonSkill("Sexy Dance")] SexyDance2,
        [PoisonSkill("Eerie Sound")] EerieSound2,
        [PoisonSkill("Tentarafoo")] Tentarafoo2,
        [PoisonSkill("Evil Smile")] EvilSmile2,
        [PoisonSkill("Poison Mist")] PoisonMist2,
        [PoisonSkill("Holy Arrow")] HolyArrow,
        [PoisonSkill("Life Drain")] LifeDrain2,
        [PoisonSkill("Spirit Drain")] SpiritDrain2,
        [Unused] Skill05F,
        [Skill("Death")] Death,
        [Skill("Yell")] Yell,
        [Skill("Yell")] Yell2,
        [Skill("Death")] Death3,
        [Skill("Death")] Death4,
        [Skill("Death")] Death5,
        [Skill("Moonless Gown")] MoonlessGown,
        [Skill("Moonless Gown")] MoonlessGown2,
        [Skill("Summon")] Summon,
        [Skill("Slash Attack")] SlashAttack,
        [Skill("Pierce Attack")] PierceAttack,
        [Skill("Strike Attack")] StrikeAttack,
        [Skill("Yell")] Yell3,
        [GunSkill("Pierce Attack")] PierceAttack3, // FES, P3P
        [FireSkill("Fire Attack")] FireAttack, // FES, P3P
        [AlmightySkill("Almighty Attack")] AlmightyAttack, // FES, P3P
        [HitSkill("Bash")] Bash,
        [HitSkill("Assault Dive")] AssaultDive,
        [HitSkill("Kill Rush")] KillRush,
        [HitSkill("Swift Strike")] SwiftStrike,
        [HitSkill("Sonic Punch")] SonicPunch,
        [HitSkill("Heat Wave")] HeatWave,
        [HitSkill("Gigantic Fist")] GiganticFist,
        [HitSkill("Akasha Arts")] AkashaArts,
        [HitSkill("God's Hand")] GodsHand,
        [HitSkill("Cleave")] Cleave,
        [HitSkill("Fatal End")] FatalEnd,
        [HitSkill("Getsu-ei")] Getsuei,
        [HitSkill("Zan-ei")] Zanei,
        [HitSkill("Mighty Swing")] MightySwing,
        [HitSkill("Double Fangs")] DoubleFangs,
        [HitSkill("Blade of Fury")] BladeofFury,
        [HitSkill("Deathbound")] Deathbound,
        [HitSkill("Tempest Slash")] TempestSlash,
        [HitSkill("Heaven's Blade")] HeavensBlade,
        [GunSkill("Pralaya")] Pralaya,
        [HitSkill("Power Slash")] PowerSlash, // FES, P3P
        [HitSkill("Gale Slash")] GaleSlash, // FES, P3P
        [HitSkill("Brave Blade")] BraveBlade, // FES, P3P
        [HitSkill("Herculean Strike")] HerculeanStrike, // FES, P3P
        [HitSkill("Vicious Strike")] ViciousStrike, // FES, P3P
        [GunSkill("Single Shot")] SingleShot, // FES, P3P
        [GunSkill("Twin Shot")] TwinShot,
        [GunSkill("Holy Arrow")] HolyArrow2,
        [GunSkill("Torrent Shot")] TorrentShot,
        [GunSkill("Arrow Rain")] ArrowRain,
        [GunSkill("Myriad Arrows")] MyriadArrows,
        [GunSkill("Primal Force")] PrimalForce,
        [HitSkill("Vorpal Blade")] VorpalBlade,
        [HitSkill("Weary Thrust")] WearyThrust,
        [GunSkill("Cruel Attack")] CruelAttack,
        [GunSkill("Vile Assault")] VileAssault,
        [GunSkill("Poison Arrow")] PoisonArrow, // FES, P3P
        [HitSkill("Weary Thrust")] WearyThrust2, // FES, P3P
        [HitSkill("Vorpal Blade")] VorpalBlade2, // FES, P3P
        [Skill("Junpei Co-Op")] JunpeiCoOp, // P3P
        [Skill("Yukari Co-Op")] YukariCoOp, // P3P
        [Skill("Akihiko Co-Op")] AkihikoCoOp, // P3P
        [Skill("Mitsuru Co-Op")] MitsuruCoOp, // P3P
        [Skill("Aigis Co-Op")] AigisCoOp, // P3P
        [Skill("Ken Co-Op")] KenCoOp, // P3P
        [Skill("Shinjiro Co-Op")] ShinjiroCoOp, // P3P
        [Skill("Koromaru Co-Op")] KoromaruCoOp, // P3P
        [Unused] Skill09F,
        [Skill("+charm(low)")] SkillcharmLow,
        [Skill("+charm(med)")] SkillcharmMed,
        [Skill("+charm(high)")] SkillcharmHigh,
        [Skill("+distress(low)")] SkilldistressLow,
        [Skill("+distress(med)")] SkilldistressMed,
        [Skill("+distress(high)")] SkilldistressHigh,
        [Skill("+panic(low)")] SkillpanicLow,
        [Skill("+panic(med)")] SkillpanicMed,
        [Skill("+panic(high)")] SkillpanicHigh,
        [Skill("+fear(low)")] SkillfearLow,
        [Skill("+fear(med)")] SkillfearMed,
        [Skill("+fear(high)")] SkillfearHigh,
        [Skill("+rage(low)")] SkillrageLow,
        [Skill("+rage(med)")] SkillrageMed,
        [Skill("+rage(high)")] SkillrageHigh,
        [Skill("+poison(low)")] SkillpoisonLow,
        [Unused] Skill0B0,
        [Unused] Skill0B1,
        [Unused] Skill0B2,
        [Unused] Skill0B3,
        [Unused] Skill0B4,
        [Unused] Skill0B5,
        [Unused] Skill0B6,
        [Unused] Skill0B7,
        [Unused] Skill0B8,
        [Unused] Skill0B9,
        [Unused] Skill0BA,
        [Unused] Skill0BB,
        [Unused] Skill0BC,
        [Unused] Skill0BD,
        [Unused] Skill0BE,
        [Unused] Skill0BF,
        [HealSkill("Dia")] Dia,
        [HealSkill("Diarama")] Diarama,
        [HealSkill("Diarahan")] Diarahan,
        [HealSkill("Media")] Media,
        [HealSkill("Mediarama")] Mediarama,
        [HealSkill("Mediarahan")] Mediarahan,
        [HealSkill("Salvation")] Salvation,
        [HealSkill("Patra")] Patra,
        [HealSkill("Me Patra")] MePatra,
        [HealSkill("Re Patra")] RePatra,
        [HealSkill("Posumudi")] Posumudi,
        [HealSkill("Amrita")] Amrita,
        [HealSkill("Recarm")] Recarm,
        [HealSkill("Samarecarm")] Samarecarm,
        [SupportSkill("Tarunda")] Tarunda,
        [SupportSkill("Matarunda")] Matarunda,
        [SupportSkill("Sukunda")] Sukunda,
        [SupportSkill("Masukunda")] Masukunda,
        [SupportSkill("Rakunda")] Rakunda,
        [SupportSkill("Marakunda")] Marakunda,
        [SupportSkill("Dekunda")] Dekunda,
        [Unused] Skill0D5,
        [SupportSkill("Tarukaja")] Tarukaja,
        [SupportSkill("Matarukaja")] Matarukaja,
        [SupportSkill("Sukukaja")] Sukukaja,
        [SupportSkill("Masukukaja")] Masukukaja,
        [SupportSkill("Rakukaja")] Rakukaja,
        [SupportSkill("Marakukaja")] Marakukaja,
        [SupportSkill("Power Charge")] PowerCharge,
        [SupportSkill("Mind Charge")] MindCharge,
        [Unused] Skill0DE,
        [SupportSkill("Dekaja")] Dekaja,
        [SupportSkill("Tetrakarn")] Tetrakarn,
        [SupportSkill("Makarakarn")] Makarakarn,
        [SupportSkill("Rebellion")] Rebellion,
        [SupportSkill("Revolution")] Revolution,
        [Unused] Skill0E4,
        [SupportSkill("Fire Break")] FireBreak,
        [SupportSkill("Ice Break")] IceBreak,
        [SupportSkill("Wind Break")] WindBreak,
        [SupportSkill("Elec Break")] ElecBreak,
        [SupportSkill("Traesto")] Traesto,
        [SupportSkill("Trafuri")] Trafuri,
        [SupportSkill("Healing Wave")] HealingWave,
        [HealSkill("Recarmdra")] Recarmdra,
        [HealSkill("Charmdi")] Charmdi,
        [HealSkill("Enradi")] Enradi,
        [Skill("Junpei Co-Op")] JunpeiCoOp2, // P3P
        [Skill("Yukari Co-Op")] YukariCoOp2, // P3P
        [Skill("Akihiko Co-Op")] AkihikoCoOp2, // P3P
        [Skill("Mitsuru Co-Op")] MitsuruCoOp2, // P3P
        [Skill("Aigis Co-Op")] AigisCoOp2, // P3P
        [Skill("Ken Co-Op")] KenCoOp2, // P3P
        [Skill("Shinjiro Co-Op")] ShinjiroCoOp2, // P3P
        [Skill("Koromaru Co-Op")] KoromaruCoOp2, // P3P
        [Skill("Aigis Co-Op")] AigisCoOp3, // P3P
        [Skill("Aigis Co-Op")] AigisCoOp4, // P3P
        [Skill("Aigis Co-Op")] AigisCoOp5, // P3P
        [Skill("Aigis Co-Op")] AigisCoOp6, // P3P
        [Unused] Skill0FB,
        [Unused] Skill0FC,
        [Unused] Skill0FD,
        [Unused] Skill0FE,
        [Unused] Skill0FF,
        [Skill("Summer Dream")] SummerDream,
        [Skill("Summer Dream")] SummerDream2,
        [Skill("Summer Dream")] SummerDream3,
        [Skill("Summer Dream")] SummerDream4,
        [Skill("Summer Dream")] SummerDream5,
        [Skill("Summer Dream")] SummerDream6,
        [Skill("Summer Dream")] SummerDream7,
        [Skill("Summer Dream")] SummerDream8,
        [Skill("Summer Dream")] SummerDream9,
        [Skill("Summer Dream")] SummerDream10,
        [Skill("Summer Dream")] SummerDream11,
        [Skill("Summer Dream")] SummerDream12,
        [Skill("Summer Dream")] SummerDream13,
        [Skill("Summer Dream")] SummerDream14,
        [Skill("Summer Dream")] SummerDream15,
        [Skill("Summer Dream")] SummerDream16,
        [Skill("Jack Brothers")] JackBrothers,
        [Skill("Ardhanari")] Ardhanari,
        [Skill("Trickster")] Trickster,
        [Skill("Infinity")] Infinity,
        [Skill("Valhalla")] Valhalla,
        [Skill("Summer Dream")] SummerDream17,
        [Skill("Armageddon")] Armageddon,
        [Skill("Cadenza")] Cadenza,
        [Skill("Scarlet Havoc")] ScarletHavoc,
        [Skill("Frolic")] Frolic,
        [Skill("Dreamfest")] Dreamfest,
        [Skill("King and I")] KingandI,
        [Skill("Best Friends")] BestFriends,
        [Skill("Shadow Hound")] ShadowHound,
        [Skill("Thunder Call")] ThunderCall,
        [Skill("Last Judge")] LastJudge,
        [Skill("Raktapaksha")] Raktapaksha,
        [Skill("Justice")] Justice,
        [Skill("Trickster")] Trickster2,
        [Unused] Skill123,
        [Unused] Skill124,
        [Skill("Primal Darkness")] PrimalDarkness, // FES, P3P
        [Skill("Dark Embrace")] DarkEmbrace, // FES, P3P
        [Skill("Primal Darkness")] PrimalDarkness2, // FES, P3P
        [Skill("Primal Darkness")] PrimalDarkness3, // FES, P3P
        [Skill("Heartbreaker")] Heartbreaker, // P3P
        [Skill("Pierce Attack")] PierceAttack6, // P3P
        [Skill("Pierce Attack")] PierceAttack7, // P3P
        [Skill("Giga Spark")] GigaSpark, // P3P
        [Skill("Sacrifice")] Sacrifice, // P3P
        [Unused] Skill12E,
        [Unused] Skill12F,
        [Skill("Pierce Attack")] PierceAttack2,
        [Skill("Fire Attack")] FireAttack2,
        [Skill("Summon")] Summon2,
        [Skill("Summon")] Summon3,
        [Skill("Armed&Ready")] ArmedAndReady,
        [Skill("Sacrifice")] Sacrifice3,
        [Skill("Arcana Shift")] ArcanaShift,
        [Skill("Arcana Shift")] ArcanaShift2,
        [Skill("Arcana Shift")] ArcanaShift3,
        [Skill("Arcana Shift")] ArcanaShift4,
        [Skill("Arcana Shift")] ArcanaShift5,
        [Skill("Arcana Shift")] ArcanaShift6,
        [Skill("Arcana Shift")] ArcanaShift7,
        [Skill("Arcana Shift")] ArcanaShift8,
        [Skill("Arcana Shift")] ArcanaShift9,
        [Skill("Night Queen")] NightQueen,
        [Skill("All-Out 2")] AllOut2,
        [Skill("All-Out 3")] AllOut3,
        [Skill("All-Out 4")] AllOut4,
        [Skill("Plume of Dusk")] PlumeofDusk,
        [Skill("Analyze")] Analyze,
        [Skill("Oracle")] Oracle,
        [Skill("Full Analysis")] FullAnalysis,
        [Skill("Oracle")] Oracle2,
        [Skill("Oracle")] Oracle3,
        [Skill("Oracle")] Oracle4,
        [Skill("Oracle")] Oracle5,
        [Skill("Oracle")] Oracle6,
        [Skill("All-Out 2L")] AllOut2L,
        [Skill("All-Out 3L")] AllOut3L,
        [Skill("All-Out 4L")] AllOut4L,
        [Skill("Support Scan")] SupportScan,
        [Skill("Third Eye")] ThirdEye,
        [Skill("Mind DJ")] MindDJ,
        [Skill("DJ Queen")] DJQueen,
        [Skill("Escape Route")] EscapeRoute,
        [Skill("Healing Wave")] HealingWave2,
        [Skill("Summon")] Summon4,
        [Skill("Orgia Mode")] OrgiaMode,
        [Skill("Great Seal")] GreatSeal,
        [Skill("Great Seal")] GreatSeal2, // P3P
        [Unused] Skill159,
        [IceSkill("Ice Attack")] IceAttack, // FES, P3P
        [WindSkill("Wind Attack")] WindAttack,
        [ThunderSkill("Elec Attack")] ElecAttack,
        [FireSkill("Fire Attack")] FireAttack3,
        [Skill("Pierce Attack")] PierceAttack8,
        [Skill("Strike Attack")] StrikeAttack2,
        [Skill("Summon")] Summon5,
        [Skill("Summon")] Summon6,
        [Skill("Summon")] Summon7,
        [Skill("Prophecy of Ruin")] ProphecyofRuin,
        [Skill("Heartbreaker")] Heartbreaker2,
        [Skill("Unite")] Unite,
        [Skill("Separate")] Separate,
        [Skill("Pierce Attack")] PierceAttack4,
        [Skill("Pierce Attack")] PierceAttack5,
        [Skill("Samarecarm")] Samarecarm2,
        [Skill("Samarecarm")] Samarecarm3,
        [Skill("Charge")] Charge,
        [Skill("Giga Spark")] GigaSpark2,
        [Skill("Wheel of Fortune")] WheelofFortune,
        [Skill("Wheel of Fortune")] WheelofFortune2,
        [Skill("Wheel of Fortune")] WheelofFortune3,
        [Skill("Paradigm Shift")] ParadigmShift,
        [Skill("Wheel of Fortune")] WheelofFortune4,
        [Skill("Wheel of Fortune")] WheelofFortune5,
        [Skill("E Attack Up")] EAttackUp,
        [Skill("P Attack Up")] PAttackUp,
        [Skill("E Attack Down")] EAttackDown,
        [Skill("P Attack Down")] PAttackDown,
        [Skill("E Defense Up")] EDefenseUp,
        [Skill("P Defense Up")] PDefenseUp,
        [Skill("E Defense Down")] EDefenseDown,
        [Skill("P Defense Down")] PDefenseDown,
        [Skill("E Panic")] EPanic,
        [Skill("P Panic")] PPanic,
        [Skill("E Rage")] ERage,
        [Skill("P Rage")] PRage,
        [Skill("E Distress")] EDistress,
        [Skill("P Distress")] PDistress,
        [Skill("E Fear")] EFear,
        [Skill("P Fear")] PFear,
        [Skill("E Damage Low")] EDamageLow,
        [Skill("P Damage Low")] PDamageLow,
        [Skill("E Damage Mid")] EDamageMid,
        [Skill("P Damage Mid")] PDamageMid,
        [Skill("E Damage High")] EDamageHigh,
        [Skill("P Damage High")] PDamageHigh,
        [Skill("E Heal")] EHeal,
        [Skill("P Heal")] PHeal,
        [Skill("Almighty Attack")] AlmightyAttack2,
        [Skill("Arcana Shift")] ArcanaShift10,
        [Skill("Arcana Shift")] ArcanaShift11,
        [Skill("Arcana Shift")] ArcanaShift12,
        [Skill("Arcana Shift")] ArcanaShift13,
        [Consumable("Band Aid")] BandAid,
        [Consumable("Medicine")] Medicine,
        [Consumable("Bead")] Bead,
        [Consumable("Snuff Soul")] SnuffSoul,
        [Consumable("Chewing Soul")] ChewingSoul,
        [Consumable("Precious Egg")] PreciousEgg,
        [Consumable("Soma")] Soma,
        [Unused] Skill197,
        [Unused] Skill198,
        [Unused] Skill199,
        [Unused] Skill19A,
        [Consumable("Muscle Drink")] MuscleDrink,
        [Consumable("Odd Morsel")] OddMorsel,
        [Consumable("Rancid Gravy")] RancidGravy,
        [Consumable("Powerful Drug")] PowerfulDrug,
        [Consumable("Cold Medicine")] ColdMedicine,
        [Consumable("Energy Drink")] EnergyDrink,
        [Unused] Skill1A1,
        [Unused] Skill1A2,
        [Unused] Skill1A3,
        [Unused] Skill1A4,
        [Unused] Skill1A5,
        [Unused] Skill1A6,
        [Unused] Skill1A7,
        [Unused] Skill1A8,
        [Unused] Skill1A9,
        [Unused] Skill1AA,
        [Unused] Skill1AB,
        [Unused] Skill1AC,
        [Unused] Skill1AD,
        [Unused] Skill1AE,
        [Unused] Skill1AF,
        [Unused] Skill1B0,
        [Unused] Skill1B1,
        [Unused] Skill1B2,
        [Unused] Skill1B3,
        [Unused] Skill1B4,
        [Unused] Skill1B5,
        [Skill("Homunculus")] Homunculus,
        [Skill("Plume of Dusk")] PlumeofDusk2,
        [Unused] Skill1B8,
        [Unused] Skill1B9,
        [Unused] Skill1BA,
        [Unused] Skill1BB,
        [Unused] Skill1BC,
        [Unused] Skill1BD,
        [Unused] Skill1BE,
        [Unused] Skill1BF,
        [Unused] Skill1C0,
        [Unused] Skill1C1,
        [Unused] Skill1C2,
        [Unused] Skill1C3,
        [Unused] Skill1C4,
        [Unused] Skill1C5,
        [Unused] Skill1C6,
        [Unused] Skill1C7,
        [Unused] Skill1C8,
        [Unused] Skill1C9,
        [Unused] Skill1CA,
        [Unused] Skill1CB,
        [Unused] Skill1CC,
        [Unused] Skill1CD,
        [Unused] Skill1CE,
        [Unused] Skill1CF,
        [AutoSkill("Resist Slash")] ResistSlash,
        [AutoSkill("Null Slash")] NullSlash,
        [AutoSkill("Repel Slash")] RepelSlash,
        [AutoSkill("Absorb Slash")] AbsorbSlash,
        [AutoSkill("Resist Strike")] ResistStrike,
        [AutoSkill("Null Strike")] NullStrike,
        [AutoSkill("Repel Strike")] RepelStrike,
        [AutoSkill("Absorb Strike")] AbsorbStrike,
        [AutoSkill("Resist Pierce")] ResistPierce,
        [AutoSkill("Null Pierce")] NullPierce,
        [AutoSkill("Repel Pierce")] RepelPierce,
        [AutoSkill("Absorb Pierce")] AbsorbPierce,
        [AutoSkill("Resist Fire")] ResistFire,
        [AutoSkill("Null Fire")] NullFire,
        [AutoSkill("Repel Fire")] RepelFire,
        [AutoSkill("Absorb Fire")] AbsorbFire,
        [AutoSkill("Resist Ice")] ResistIce,
        [AutoSkill("Null Ice")] NullIce,
        [AutoSkill("Repel Ice")] RepelIce,
        [AutoSkill("Absorb Ice")] AbsorbIce,
        [AutoSkill("Resist Elec")] ResistElec,
        [AutoSkill("Null Elec")] NullElec,
        [AutoSkill("Repel Elec")] RepelElec,
        [AutoSkill("Absorb Elec")] AbsorbElec,
        [AutoSkill("Resist Wind")] ResistWind,
        [AutoSkill("Null Wind")] NullWind,
        [AutoSkill("Repel Wind")] RepelWind,
        [AutoSkill("Absorb Wind")] AbsorbWind,
        [AutoSkill("Resist Light")] ResistLight,
        [AutoSkill("Null Light")] NullLight,
        [AutoSkill("Repel Light")] RepelLight,
        [AutoSkill("Resist Dark")] ResistDark,
        [AutoSkill("Null Dark")] NullDark,
        [AutoSkill("Repel Dark")] RepelDark,
        [AutoSkill("Null Charm")] NullCharm,
        [AutoSkill("Null Distress")] NullDistress,
        [AutoSkill("Null Panic")] NullPanic,
        [AutoSkill("Null Fear")] NullFear,
        [AutoSkill("Null Rage")] NullRage,
        [AutoSkill("Null Freeze")] NullFreeze,
        [AutoSkill("Null Shock")] NullShock,
        [AutoSkill("Null Poison")] NullPoison,
        [AutoSkill("Unshaken Will")] UnshakenWill,
        [AutoSkill("Masakados")] Masakados,
        [AutoSkill("Dodge Slash")] DodgeSlash,
        [AutoSkill("Evade Slash")] EvadeSlash,
        [AutoSkill("Dodge Strike")] DodgeStrike,
        [AutoSkill("Evade Strike")] EvadeStrike,
        [AutoSkill("Dodge Pierce")] DodgePierce,
        [AutoSkill("Evade Pierce")] EvadePierce,
        [AutoSkill("Dodge Fire")] DodgeFire,
        [AutoSkill("Evade Fire")] EvadeFire,
        [AutoSkill("Dodge Ice")] DodgeIce,
        [AutoSkill("Evade Ice")] EvadeIce,
        [AutoSkill("Dodge Wind")] DodgeWind,
        [AutoSkill("Evade Wind")] EvadeWind,
        [AutoSkill("Dodge Elec")] DodgeElec,
        [AutoSkill("Evade Elec")] EvadeElec,
        [AutoSkill("Stamina Up 1")] StaminaUp1, // FES, P3P
        [AutoSkill("Stamina Up 2")] StaminaUp2, // FES, P3P
        [AutoSkill("Stamina Up 3")] StaminaUp3, // FES, P3P
        [Unused] Skill20D,
        [AutoSkill("Premonition")] Premonition,
        [AutoSkill("Angelic Grace")] AngelicGrace,
        [AutoSkill("Fire Boost")] FireBoost,
        [AutoSkill("Fire Amp")] FireAmp,
        [AutoSkill("Ice Boost")] IceBoost,
        [AutoSkill("Ice Amp")] IceAmp,
        [AutoSkill("Elec Boost")] ElecBoost,
        [AutoSkill("Elec Amp")] ElecAmp,
        [AutoSkill("Wind Boost")] WindBoost,
        [AutoSkill("Wind Amp")] WindAmp,
        [AutoSkill("Fast Retreat")] FastRetreat,
        [AutoSkill("HP Up 1")] HPUp1,
        [AutoSkill("HP Up 2")] HPUp2,
        [AutoSkill("HP Up 3")] HPUp3,
        [AutoSkill("SP Up 1")] SPUp1,
        [AutoSkill("SP Up 2")] SPUp2,
        [AutoSkill("SP Up 3")] SPUp3,
        [AutoSkill("Raging Tiger")] RagingTiger,
        [AutoSkill("Counter")] Counter,
        [AutoSkill("Counterstrike")] Counterstrike,
        [AutoSkill("High Counter")] HighCounter,
        [AutoSkill("Regenerate 1")] Regenerate1,
        [AutoSkill("Regenerate 2")] Regenerate2,
        [AutoSkill("Regenerate 3")] Regenerate3,
        [AutoSkill("Invigorate 1")] Invigorate1,
        [AutoSkill("Invigorate 2")] Invigorate2,
        [AutoSkill("Invigorate 3")] Invigorate3,
        [AutoSkill("Growth 1")] Growth1,
        [AutoSkill("Growth 2")] Growth2,
        [AutoSkill("Growth 3")] Growth3,
        [Unused] Skill22C,
        [AutoSkill("Auto-Tarukaja")] AutoTarukaja,
        [AutoSkill("Auto-Rakukaja")] AutoRakukaja,
        [AutoSkill("Auto-Sukukaja")] AutoSukukaja,
        [AutoSkill("Alertness")] Alertness,
        [AutoSkill("Sharp Student")] SharpStudent,
        [AutoSkill("Apt Pupil")] AptPupil,
        [AutoSkill("Ali Dance")] AliDance,
        [AutoSkill("Firm Stance")] FirmStance,
        [AutoSkill("Spell Master")] SpellMaster,
        [AutoSkill("Arms Master")] ArmsMaster,
        [AutoSkill("HP Up")] HPUp,
        [AutoSkill("SP Up")] SPUp,
        [Unused] Skill239,
        [AutoSkill("Divine Grace")] DivineGrace,
        [AutoSkill("Endure")] Endure,
        [AutoSkill("Enduring Soul")] EnduringSoul,
        [AutoSkill("Heavy Master")] HeavyMaster,
        [AutoSkill("Magic Skill Up")] MagicSkillUp,
        [AutoSkill("Phys Skill Up")] PhysSkillUp,
        [Unused] Skill240,
        [Unused] Skill241,
        [Unused] Skill242,
        [Unused] Skill243,
        [AutoSkill("Rosary")] Rosary,
        [AutoSkill("Prayer Beads")] PrayerBeads,
        [AutoSkill("Spear Master")] SpearMaster,
        [AutoSkill("Bow Master")] BowMaster,
        [AutoSkill("1hSwd Master")] Skill1hSwdMaster,
        [AutoSkill("2hSwd Master")] Skill2hSwdMaster,
        [AutoSkill("Fist Master")] FistMaster,
        [AutoSkill("Survive Light")] SurviveLight,
        [AutoSkill("Survive Dark")] SurviveDark,
        [AutoSkill("Auto-Maraku")] AutoMaraku,
        [AutoSkill("Auto-Mataru")] AutoMataru,
        [AutoSkill("Auto-Masuku")] AutoMasuku,
        [AutoSkill("Charm Boost")] CharmBoost,
        [AutoSkill("Poison Boost")] PoisonBoost,
        [AutoSkill("Distress Boost")] DistressBoost,
        [AutoSkill("Panic Boost")] PanicBoost,
        [AutoSkill("Fear Boost")] FearBoost,
        [AutoSkill("Rage Boost")] RageBoost,
        [AutoSkill("Ailment Boost")] AilmentBoost,
        [AutoSkill("Hama Boost")] HamaBoost,
        [AutoSkill("Mudo Boost")] MudoBoost,
        [AutoSkill("Endure Light")] EndureLight,
        [AutoSkill("Endure Dark")] EndureDark,
        [AutoSkill("Weapons Master")] WeaponsMaster, // P3P
        [Unused] Skill25C,
        [AutoSkill("Cool Breeze")] CoolBreeze,
        [AutoSkill("Victory Cry")] VictoryCry,
        [AutoSkill("Spring of Life")] SpringofLife,
        [AutoSkill("Spring of Life")] SpringofLife2,
        [Skill("Infinite Endure")] InfiniteEndure, // For Debug in P3 and FES, Infinite Endure in P3P
        [Skill("Fast-Heal")] FastHeal, // FES, P3P
        [Skill("Insta-Heal")] InstaHeal, // FES, P3P
        [AutoSkill("Resist Charm")] ResistCharm, // FES, P3P
        [AutoSkill("Resist Distress")] ResistDistress, // FES, P3P
        [AutoSkill("Resist Panic")] ResistPanic, // FES, P3P
        [AutoSkill("Resist Fear")] ResistFear, // FES, P3P
        [AutoSkill("Resist Rage")] ResistRage, // FES, P3P
        [AutoSkill("Resist Freeze")] ResistFreeze, // FES, P3P
        [AutoSkill("Resist Shock")] ResistShock, // FES, P3P
        [AutoSkill("Resist Poison")] ResistPoison, // FES, P3P
        [AutoSkill("HP Up High")] HPUpHigh, // FES, P3P
        [AutoSkill("SP Up High")] SPUpHigh, // FES, P3P
        [Skill("High Endure")] HighEndure, // P3P
        [Skill("Blank")] Blank, // P3P
    }
}
