// https://pastebin.com/ZH0L3XXi
using KHSave.Attributes;

namespace KHSave.Lib1.Types
{
    public enum AbilityType : byte
    {
        [Info] Empty,
        [Ability("High Jump")] HighJump = 0x01,
        [Ability("Mermaid Kick")] MermaidKick = 0x02,
        [Ability("Glide")] Glide = 0x03,
        [Ability("Superglide")] Superglide = 0x04,
        [Ability("Treasure Magnet")] TreasureMagnet = 0x05,
        [Ability("Combo Plus")] ComboPlus = 0x06,
        [Ability("Air Combo Plus")] AirComboPlus = 0x07,
        [Ability("Critical Plus")] CriticalPlus = 0x08,
        [Ability("Second Wind")] SecondWind = 0x09,
        [Ability("Scan")] Scan = 0x0A,
        [Ability("Sonic Blade")] SonicBlade = 0x0B,
        [Ability("Ars Arcanum")] ArsArcanum = 0x0C,
        [Ability("Strike Raid")] StrikeRaid = 0x0D,
        [Ability("Ragnarok")] Ragnarok = 0x0E,
        [Ability("Trinity Limit")] TrinityLimit = 0x0F,
        [Ability("Cheer")] Cheer = 0x10,
        [Ability("Vortex")] Vortex = 0x11,
        [Ability("Aerial Sweep")] AerialSweep = 0x12,
        [Ability("Counterattack")] Counterattack = 0x13,
        [Ability("Blitz")] Blitz = 0x14,
        [Ability("Guard")] Guard = 0x15,
        [Ability("Dodge Roll")] DodgeRoll = 0x16,
        [Ability("MP Haste")] MPHaste = 0x17,
        [Ability("MP Rage")] MPRage = 0x18,
        [Ability("Second Chance")] SecondChance = 0x19,
        [Ability("Berserk")] Berserk = 0x1A,
        [Ability("Jackpot")] Jackpot = 0x1B,
        [Ability("Lucky Strike")] LuckyStrike = 0x1C,
        [Ability("Charge")] Charge = 0x1D,
        [Ability("Rocket")] Rocket = 0x1E,
        [Ability("Tornado")] Tornado = 0x1F,
        [Ability("MP Gift")] MPGift = 0x20,
        [Ability("Raging Boar")] RagingBoar = 0x21,
        [Ability("Asp's Bite")] AspsBite = 0x22,
        [Ability("Healing Herb")] HealingHerb = 0x23,
        [Ability("Wind Armor")] WindArmor = 0x24,
        [Ability("Crescent")] Crescent = 0x25,
        [Ability("Sandstorm")] Sandstorm = 0x26,
        [Ability("Applause!")] Applause = 0x27,
        [Ability("Blazing Fury")] BlazingFury = 0x28,
        [Ability("Icy Terror")] IcyTerror = 0x29,
        [Ability("Bolts Of Sorrow")] BoltsOfSorrow = 0x2A,
        [Ability("Ghostly Scream")] GhostlyScream = 0x2B,
        [Ability("Hummingbird")] Hummingbird = 0x2C,
        [Ability("Time-Out")] TimeOut = 0x2D,
        [Ability("Storm's Eye")] StormsEye = 0x2E,
        [Ability("Ferocious Lunge")] FerociousLunge = 0x2F,
        [Ability("Furious Bellow")] FuriousBellow = 0x30,
        [Ability("Spiral Wave")] SpiralWave = 0x31,
        [Ability("Thunder Potion")] ThunderPotion = 0x32,
        [Ability("Cure Potion")] CurePotion = 0x33,
        [Ability("Aero Potion")] AeroPotion = 0x34,
        [Ability("Slapshot")] Slapshot = 0x35,
        [Ability("Sliding Dash")] SlidingDash = 0x36,
        [Ability("Hurricane Blast")] HurricaneBlast = 0x37,
        [Ability("Ripple Drive")] RippleDrive = 0x38,
        [Ability("Stun Impact")] StunImpact = 0x39,
        [Ability("Gravity Break")] GravityBreak = 0x3A,
        [Ability("Zantetsuken")] Zantetsuken = 0x3B,
        [Ability("Tech Boost")] TechBoost = 0x3C,
        [Ability("Encounter Plus")] EncounterPlus = 0x3D,
        [Ability("Leaf Bracer")] LeafBracer = 0x3E,
        [Ability("Evolution")] Evolution = 0x3F,
        [Ability("EXP Zero")] EXPZero = 0x40,
        [Ability("Combo Master")] ComboMaster = 0x41,
    }
}
