// https://pastebin.com/dfARF8ui
using KHSave.Attributes;

namespace KHSave.Lib1.Types
{
    public enum EquipmentType : byte
    {
        [Info] Empty,
        [Consumable("Potion")] Potion,
        [Consumable("Hi-Potion")] HiPotion,
        [Consumable("Ether")] Ether,
        [Consumable("Elixir")] Elixir,
        [Unused] BO5,
        [Consumable("Mega-Potion")] MegaPotion,
        [Consumable("Mega-Ether")] MegaEther,
        [Consumable("Megalixir")] Megalixir,
        [Synthesis("Fury Stone")] FuryStone,
        [Synthesis("Power Stone")] PowerStone,
        [Synthesis("Energy Stone")] EnergyStone,
        [Synthesis("Blazing Stone")] BlazingStone,
        [Synthesis("Frost Stone")] FrostStone,
        [Synthesis("Lightning Stone")] LightningStone,
        [Synthesis("Dazzling Stone")] DazzlingStone,
        [Synthesis("Stormy Stone")] StormyStone,
        [Accessory("Protect Chain")] ProtectChain,
        [Accessory("Protera Chain")] ProteraChain,
        [Accessory("Protega Chain")] ProtegaChain,
        [Accessory("Fire Ring")] FireRing,
        [Accessory("Fira Ring")] FiraRing,
        [Accessory("Firaga Ring")] FiragaRing,
        [Accessory("Blizzard Ring")] BlizzardRing,
        [Accessory("Blizzara Ring")] BlizzaraRing,
        [Accessory("Blizzaga Ring")] BlizzagaRing,
        [Accessory("Thunder Ring")] ThunderRing,
        [Accessory("Thundara Ring")] ThundaraRing,
        [Accessory("Thundaga Ring")] ThundagaRing,
        [Accessory("Ability Stud")] AbilityStud,
        [Accessory("Guard Earring")] GuardEarring,
        [Accessory("Master Earring")] MasterEarring,
        [Accessory("Chaos Ring")] ChaosRing,
        [Accessory("Dark Ring")] DarkRing,
        [Accessory("Element Ring")] ElementRing,
        [Accessory("Three Stars")] ThreeStars,
        [Accessory("Power Chain")] PowerChain,
        [Accessory("Golem Chain")] GolemChain,
        [Accessory("Titan Chain")] TitanChain,
        [Accessory("Energy Bangle")] EnergyBangle,
        [Accessory("Angel Bangle")] AngelBangle,
        [Accessory("Gaia Bangle")] GaiaBangle,
        [Accessory("Magic Armlet")] MagicArmlet,
        [Accessory("Rune Armlet")] RuneArmlet,
        [Accessory("Atlas Armlet")] AtlasArmlet,
        [Accessory("Heartguard")] Heartguard,
        [Accessory("Ribbon")] Ribbon,
        [Accessory("Crystal Crown")] CrystalCrown,
        [Accessory("Brave Warrior")] BraveWarrior,
        [Accessory("Ifrit's Horn")] IfritsHorn,
        [Accessory("Inferno Band")] InfernoBand,
        [Accessory("White Fang")] WhiteFang,
        [Accessory("Ray of Light")] RayofLight,
        [Accessory("Holy Circlet")] HolyCirclet,
        [Accessory("Raven's Claw")] RavensClaw,
        [Accessory("Omega Arts")] OmegaArts,
        [Accessory("EXP Earring")] EXPEarring,
        [Unused] A41,
        [Accessory("EXP Ring")] EXPRing,
        [Accessory("EXP Bracelet")] EXPBracelet,
        [Accessory("EXP Necklace")] EXPNecklace,
        [Accessory("Firagun Band")] FiragunBand,
        [Accessory("Blizzagun Band")] BlizzagunBand,
        [Accessory("Thundagun Band")] ThundagunBand,
        [Accessory("Ifrit Belt")] IfritBelt,
        [Accessory("Shiva Belt")] ShivaBelt,
        [Accessory("Ramuh Belt")] RamuhBelt,
        [Accessory("Moogle Badge")] MoogleBadge,
        [Accessory("Cosmic Arts")] CosmicArts,
        [Accessory("Royal Crown")] RoyalCrown,
        [Accessory("Prime Cap")] PrimeCap,
        [Accessory("Obsidian Ring")] ObsidianRing,
        [Unused] A56,
        [Unused] A57,
        [Unused] A58,
        [Unused] A59,
        [Unused] A60,
        [Unused] A61,
        [Unused] A62,
        [Unused] A63,
        [Unused] A64,
        [Keyblade("Kingdom Key")] KingdomKey,
        [Keyblade("Dream Sword")] DreamSword,
        [Keyblade("Dream Shield (Sora)")] DreamShieldSora,
        [Keyblade("Dream Rod (Sora)")] DreamRodSora,
        [Keyblade("Wooden Sword")] WoodenSword,
        [Keyblade("Jungle King")] JungleKing,
        [Keyblade("Three Wishes")] ThreeWishes,
        [Keyblade("Fairy Harp")] FairyHarp,
        [Keyblade("Pumpkinhead")] Pumpkinhead,
        [Keyblade("Crabclaw")] Crabclaw,
        [Keyblade("Divine Rose")] DivineRose,
        [Keyblade("Spellbinder")] Spellbinder,
        [Keyblade("Olympia")] Olympia,
        [Keyblade("Lionheart")] Lionheart,
        [Keyblade("Metal Chocobo")] MetalChocobo,
        [Keyblade("Oathkeeper")] Oathkeeper,
        [Keyblade("Oblivion")] Oblivion,
        [Keyblade("Lady Luck")] LadyLuck,
        [Keyblade("Wishing Star")] WishingStar,
        [Keyblade("Ultima Weapon")] UltimaWeapon,
        [Keyblade("Diamond Dust")] DiamondDust,
        [Keyblade("One-Winged Angel")] OneWingedAngel,
        [Staff("Mage's Staff")] MagesStaff,
        [Staff("Morning Star")] MorningStar,
        [Staff("Shooting Star")] ShootingStar,
        [Staff("Magus Staff")] MagusStaff,
        [Staff("Wisdom Staff")] WisdomStaff,
        [Staff("Warhammer")] Warhammer,
        [Staff("Silver Mallet")] SilverMallet,
        [Staff("Grand Mallet")] GrandMallet,
        [Staff("Lord Fortune")] LordFortune,
        [Staff("Violetta")] Violetta,
        [Staff("Dream Rod (Donald)")] DreamRodDonald,
        [Staff("Save the Queen")] SavetheQueen,
        [Staff("Wizard's Relic")] WizardsRelic,
        [Staff("Meteor Strike")] MeteorStrike,
        [Staff("Fantasista")] Fantasista,
        [Staff("???? (Donald Weapon)")] DonaldWeapon,
        [Shield("Knight's Shield")] KnightsShield,
        [Shield("Mythril Shield")] MythrilShield,
        [Shield("Onyx Shield")] OnyxShield,
        [Shield("Stout Shield")] StoutShield,
        [Shield("Golem Shield")] GolemShield,
        [Shield("Adamant Shield")] AdamantShield,
        [Shield("Smasher")] Smasher,
        [Shield("Gigas Fist")] GigasFist,
        [Shield("Genji Shield")] GenjiShield,
        [Shield("Herc's Shield")] HercsShield,
        [Shield("Dream Shield (Goofy)")] DreamShieldGoofy,
        [Shield("Save the King")] SavetheKing,
        [Shield("Defender")] Defender,
        [Shield("Mighty Shield")] MightyShield,
        [Shield("Seven Elements")] SevenElements,
        [Shield("???? (Goofy Weapon)")] GoofyWeapon,
        [Weapon("Spear")] Spear,
        [Weapon("No Weapon (Pooh)")] NoWeaponPooh,
        [Weapon("Scimitar")] Scimitar,
        [Weapon("No Weapon (Ariel)")] NoWeaponAriel,
        [Weapon("No Weapon (Jack)")] NoWeaponJack,
        [Weapon("Dagger")] Dagger,
        [Weapon("Claws")] Claws,
        [Boost("Tent")] Tent,
        [Boost("Camping Set")] CampingSet,
        [Boost("Cottage")] Cottage,
        [Unused] C04,
        [Unused] C05,
        [Unused] C06,
        [Unused] C07,
        [Report("Ansem's Report 11")] AnsemsReport11,
        [Report("Ansem's Report 12")] AnsemsReport12,
        [Report("Ansem's Report 13")] AnsemsReport13,
        [Boost("Power Up")] PowerUp,
        [Boost("Defense Up")] DefenseUp,
        [Boost("AP Up")] APUp,
        [Synthesis("Serenity Power")] SerenityPower,
        [Synthesis("Dark Matter")] DarkMatter,
        [Synthesis("Mythril Stone")] MythrilStone,
        [Recipe("Fire Arts")] FireArts,
        [Recipe("Blizzard Arts")] BlizzardArts,
        [Recipe("Thunder Arts")] ThunderArts,
        [Recipe("Cure Arts")] CureArts,
        [Recipe("Gravity Arts")] GravityArts,
        [Recipe("Stop Arts")] StopArts,
        [Recipe("Aero Arts")] AeroArts,
        [Recipe("Shiitank Rank")] ShiitankRank,
        [Recipe("Matsutake Rank")] MatsutakeRank,
        [Recipe("Mystery Mold")] MysteryMold,
        [Report("Ansem's Report 1")] AnsemsReport1,
        [Report("Ansem's Report 2")] AnsemsReport2,
        [Report("Ansem's Report 3")] AnsemsReport3,
        [Report("Ansem's Report 4")] AnsemsReport4,
        [Report("Ansem's Report 5")] AnsemsReport5,
        [Report("Ansem's Report 6")] AnsemsReport6,
        [Report("Ansem's Report 7")] AnsemsReport7,
        [Report("Ansem's Report 8")] AnsemsReport8,
        [Report("Ansem's Report 9")] AnsemsReport9,
        [Report("Ansem's Report 10")] AnsemsReport10,
        [KeyItem("Khama Vol. 8")] KhamaVol8,
        [KeyItem("Salegg Vol. 6")] SaleggVol6,
        [KeyItem("Azal Vol. 3")] AzalVol3,
        [KeyItem("Mava Vol. 3")] MavaVol3,
        [KeyItem("Mava Vol. 6")] MavaVol6,
        [KeyItem("Theon Vol. 6")] TheonVol6,
        [KeyItem("Nahara Vol. 5")] NaharaVol5,
        [KeyItem("Hafet Vol. 4")] HafetVol4,
        [KeyItem("Empty Bottle")] EmptyBottle,
        [KeyItem("Old Book")] OldBook,
        [KeyItem("Emblem Piece")] EmblemPiece,
        [KeyItem("Emblem Piece 2")] EmblemPiece2,
        [KeyItem("Emblem Piece 3")] EmblemPiece3,
        [KeyItem("Emblem Piece 4")] EmblemPiece4,
        [KeyItem("Log")] Log,
        [KeyItem("Cloth")] Cloth,
        [KeyItem("Rope")] Rope,
        [KeyItem("Seagull Egg")] SeagullEgg,
        [KeyItem("Fish")] Fish,
        [KeyItem("Mushroom")] Mushroom,
        [KeyItem("Coconut")] Coconut,
        [KeyItem("Drinking Water")] DrinkingWater,
        [KeyItem("Navi-G Piece 1")] NaviGPiece1,
        [KeyItem("Navi-G Piece 2")] NaviGPiece2,
        [KeyItem("Navi-Gummi 1")] NaviGummi1,
        [KeyItem("Navi-G Piece 3")] NaviGPiece3,
        [KeyItem("Navi-G Piece 4")] NaviGPiece4,
        [KeyItem("Navi-Gummi 2")] NaviGummi2,
        [Summon("Watergleam")] Watergleam,
        [Summon("Naturespark")] Naturespark,
        [Summon("Fireglow")] Fireglow,
        [Summon("Earthshine")] Earthshine,
        [KeyItem("Crystal Trident")] CrystalTrident,
        [KeyItem("Postcard")] Postcard,
        [KeyItem("Torn Page 1")] TornPage1,
        [KeyItem("Torn Page 2")] TornPage2,
        [KeyItem("Torn Page 3")] TornPage3,
        [KeyItem("Torn Page 4")] TornPage4,
        [KeyItem("Torn Page 5")] TornPage5,
        [KeyItem("Slide 1")] Slide1,
        [KeyItem("Slide 2")] Slide2,
        [KeyItem("Slide 3")] Slide3,
        [KeyItem("Slide 4")] Slide4,
        [KeyItem("Slide 5")] Slide5,
        [KeyItem("Slide 6")] Slide6,
        [KeyItem("Footprints")] Footprints,
        [KeyItem("Claw Marks")] ClawMarks,
        [KeyItem("Stench")] Stench,
        [KeyItem("Antenna")] Antenna,
        [KeyItem("Forget-Me-Not")] ForgetMeNot,
        [KeyItem("Jack-In-The-Box")] JackInTheBox,
        [KeyItem("Entry Pass")] EntryPass,
        [KeyItem("Hero License")] HeroLicense,
        [Synthesis("Pretty Stone")] PrettyStone,
        [Unused] N41,
        [Synthesis("Lucid Shard")] LucidShard,
        [Synthesis("Lucid Gem")] LucidGem,
        [Synthesis("Lucid Crystal")] LucidCrystal,
        [Synthesis("Spirit Shard")] SpiritShard,
        [Synthesis("Spirit Gem")] SpiritGem,
        [Synthesis("Power Shard")] PowerShard,
        [Synthesis("Power Gem")] PowerGem,
        [Synthesis("Power Crystal")] PowerCrystal,
        [Synthesis("Blaze Shard")] BlazeShard,
        [Synthesis("Blaze Gem")] BlazeGem,
        [Synthesis("Frost Shard")] FrostShard,
        [Synthesis("Frost Gem")] FrostGem,
        [Synthesis("Thunder Shard")] ThunderShard,
        [Synthesis("Thunder Gem")] ThunderGem,
        [Synthesis("Shiny Crystal")] ShinyCrystal,
        [Synthesis("Bright Shard")] BrightShard,
        [Synthesis("Bright Gem")] BrightGem,
        [Synthesis("Bright Crystal")] BrightCrystal,
        [Synthesis("Mystery Goo")] MysteryGoo,
        [Synthesis("Gale")] Gale,
        [Synthesis("Mythril Shard")] MythrilShard,
        [Synthesis("Mythril")] Mythril,
        [Synthesis("Orichalcum")] Orichalcum
    }
}
