using KHSave.Attributes;

namespace KHSave.Lib1.Types
{
    public enum GummiBlocksType: byte
    {
        [GummiBlock("Cure-G")] CureG = 0x1,
        [GummiBlock("Curaga-G")] CuragaG,
        [GummiBlock("Life-G")] LifeG,
        [GummiBlock("Full-Life-G")] FullLifeG,
        [GummiBlock("Fire-G")] FireG,
        [GummiBlock("Fira-G")] FiraG,
        [GummiBlock("Firaga-G")] FiragaG,
        [GummiBlock("Flara-G")] FlaraG,
        [GummiBlock("Holy-G")] HolyG,
        [GummiBlock("Protect-G (cube)")] ProtectGCube,
        [GummiBlock("Protect-G (slope)")] ProtectGSlope,
        [GummiBlock("Protect-G (triangle)")] ProtectGTriangle,
        [GummiBlock("Protect-G (cilinder)")] ProtectGCilinder,
        [GummiBlock("Protect-G (round corner)")] ProtectGCorner,
        [GummiBlock("Protect-G (quarter ball)")] ProtectGBall,
        [GummiBlock("Protect-G (1)")] ProtectG1,
        [GummiBlock("Protect-G (2)")] ProtectG2,
        [GummiBlock("Shell-G (cube)")] ShellGCube,
        [GummiBlock("Shell-G (slope)")] ShellGSlope,
        [GummiBlock("Shell-G (triangle)")] ShellGTriangle,
        [GummiBlock("Shell-G (cilinder)")] ShellGCilinder,
        [GummiBlock("Shell-G (round corner)")] ShellGCorner,
        [GummiBlock("Shell-G (quarter ball)")] ShellGBall,
        [GummiBlock("Shell-G (1)")] ShellG1,
        [GummiBlock("Shell-G (2)")] ShellG2,
        [GummiBlock("Dispel-G (cube)")] DispelGCube,
        [GummiBlock("Dispel-G (slope)")] DispelGSlope,
        [GummiBlock("Dispel-G (triangle)")] DispelGTriangle,
        [GummiBlock("Dispel-G (cilinder)")] DispelGCilinder,
        [GummiBlock("Dispel-G (round corner)")] DispelGCorner,
        [GummiBlock("Dispel-G (quarter ball)")] DispelGBall,
        [GummiBlock("Dispel-G (1)")] DispelG1,
        [GummiBlock("Dispel-G (2)")] DispelG2,
        [GummiBlock("Aerora-G (L)")] AeroraGL,
        [GummiBlock("Aerora-G (R)")] AeroraGR,
        [GummiBlock("Aeroga-G (L)")] AerogaGL,
        [GummiBlock("Aeroga-G (R)")] AerogaGR,
        [GummiBlock("Tornado-G (L)")] TornadoGL,
        [GummiBlock("Tornado-G (R)")] TornadoGR,
        [GummiBlock("Float-G (L)")] FloatGL,
        [GummiBlock("Float-G (R)")] FloatGR,
        [GummiBlock("Aero-G (L)")] AeroGL,
        [GummiBlock("Aero-G (R)")] AeroGR,
        [GummiBlock("Aero-G (Square)")] AeroGS,
        [GummiBlock("Drain-G (L)")] DrainGL,
        [GummiBlock("Drain-G (R)")] DrainGR,
        [GummiBlock("Osmose-G (L)")] OsmoseGL,
        [GummiBlock("Osmose-G (R)")] OsmoseGR,
        [GummiBlock("Transform-G")] TransformG,
        [GummiBlock("Warp-G (You can't select this block in the editor normally)")] WarpG,
        [GummiBlock("Scan-G (Front)")] ScanG1,
        [GummiBlock("Scan-G (Full)")] ScanG2,
        [GummiBlock("Haste-G")] HasteG,
        [GummiBlock("Haste2-G")] Haste2G,
        [GummiBlock("Shield-G")] ShieldG,
        [GummiBlock("Shield2-G")] Shield2G,
        [GummiBlock("Ensuna-G (Round)")] EnsunaGR,
        [GummiBlock("Ensuna-G (Square)")] EnsunaGS,
        [GummiBlock("Thunder-G")] ThunderG,
        [GummiBlock("Thundara-G")] ThundaraG,
        [GummiBlock("Thundaga-G")] ThundagaG,
        [GummiBlock("Comet-G")] CometG,
        [GummiBlock("Meteor-G")] MeteorG,
        [GummiBlock("Ultima-G")] UltimaG,


        //Other Gummi items that aren't blocks
        [Info("Spray (Adds color to gummi blocks)")] Spray,
        [Info("Pallete (Provides a variety of paint colors.)")] Pallete,
    }
}
