using KHSave.Attributes;

namespace KHSave.Lib1.Types
{
    public enum GummiBlocksType: byte
    {
        [GummiBlock("Cure-G")] CureG = 0x1,
        [GummiBlock("Curaga-G")] CuragaG,
        [GummiBlock("Life-G")] LifeG,
        [GummiBlock("Full-Life-G")] FullLifeG,
        [GummiBlock("Fire-G")] FireG,
        [GummiBlock("Fira-G")] FiraG,
        [GummiBlock("Firaga-G")] FiragaG,
        [GummiBlock("Flara-G")] FlaraG,
        [GummiBlock("Holy-G")] HolyG,
        [GummiBlock("Protect-G (Cube)")] ProtectGCube,
        [GummiBlock("Protect-G (Triangular Prism)")] ProtectGTriangularPrism,
        [GummiBlock("Protect-G (Pyramid)")] ProtectGPyramid,
        [GummiBlock("Protect-G (Cylinder)")] ProtectGCylinder,
        [GummiBlock("Protect-G (Half-Cylinder)")] ProtectGHalfCylinder,
        [GummiBlock("Protect-G (Quarter-Sphere)")] ProtectGQuarterSphere,
        [GummiBlock("Protect-G (Unproportional Cylinder)")] ProtectGUnproportionalCylinder,
        [GummiBlock("Protect-G (Half-Sphere)")] ProtectGHalfSphere,
        [GummiBlock("Shell-G (Cube)")] ShellGCube,
        [GummiBlock("Shell-G (Triangular Prism)")] ShellGTriangularPrism,
        [GummiBlock("Shell-G (Pyramid)")] ShellGPyramid,
        [GummiBlock("Shell-G (Cylinder)")] ShellGCylinder,
        [GummiBlock("Shell-G (Half-Cylinder)")] ShellGHalfCylinder,
        [GummiBlock("Shell-G (Quarter-Sphere)")] ShellGQuarterSphere,
        [GummiBlock("Shell-G (Unproportional Cylinder)")] ShellG1UnproportionalCylinder
        [GummiBlock("Shell-G (Half-Sphere)")] ShellGHalfSphere,
        [GummiBlock("Dispel-G (Cube)")] DispelGCube,
        [GummiBlock("Dispel-G (Triangular Prism)")] DispelGTriangularPrism,
        [GummiBlock("Dispel-G (Pyramid)")] DispelGPyramid,
        [GummiBlock("Dispel-G (Cylinder)")] DispelGCylinder,
        [GummiBlock("Dispel-G (Half-Cylinder)")] DispelGHalfCylinder,
        [GummiBlock("Dispel-G (Quarter-Sphere)")] DispelGQuarterSphere,
        [GummiBlock("Dispel-G (Unproportional Cylinder)")] DispelGUnproportionalCylinder,
        [GummiBlock("Dispel-G (Half-Sphere)")] DispelGHalfSphere,
        [GummiBlock("Aerora-G (L)")] AeroraGL,
        [GummiBlock("Aerora-G (R)")] AeroraGR,
        [GummiBlock("Aeroga-G (L)")] AerogaGL,
        [GummiBlock("Aeroga-G (R)")] AerogaGR,
        [GummiBlock("Tornado-G (L)")] TornadoGL,
        [GummiBlock("Tornado-G (R)")] TornadoGR,
        [GummiBlock("Float-G (L)")] FloatGL,
        [GummiBlock("Float-G (R)")] FloatGR,
        [GummiBlock("Aero-G (L)")] AeroGL,
        [GummiBlock("Aero-G (R)")] AeroGR,
        [GummiBlock("Aero-G (Square)")] AeroGS,
        [GummiBlock("Drain-G (L)")] DrainGL,
        [GummiBlock("Drain-G (R)")] DrainGR,
        [GummiBlock("Osmose-G (L)")] OsmoseGL,
        [GummiBlock("Osmose-G (R)")] OsmoseGR,
        [GummiBlock("Transform-G")] TransformG,
        [GummiBlock("Warp-G (You can't select this block in the editor normally)")] WarpG,
        [GummiBlock("Scan-G (Front)")] ScanG1,
        [GummiBlock("Scan-G (Full)")] ScanG2,
        [GummiBlock("Haste-G")] HasteG,
        [GummiBlock("Haste2-G")] Haste2G,
        [GummiBlock("Shield-G")] ShieldG,
        [GummiBlock("Shield2-G")] Shield2G,
        [GummiBlock("Ensuna-G (Round)")] EnsunaGR,
        [GummiBlock("Ensuna-G (Square)")] EnsunaGS,
        [GummiBlock("Thunder-G")] ThunderG,
        [GummiBlock("Thundara-G")] ThundaraG,
        [GummiBlock("Thundaga-G")] ThundagaG,
        [GummiBlock("Comet-G")] CometG,
        [GummiBlock("Meteor-G")] MeteorG,
        [GummiBlock("Ultima-G")] UltimaG,


        //Other Gummi items that aren't blocks
        [Info("Spray (Adds color to gummi blocks)")] Spray,
        [Info("Pallete (Provides a variety of paint colors.)")] Pallete,
        [Info("Sys.UP1")] SysUP1,
        [Info("Sys.UP2")] SysUP2,
        [Info("Com. LV1")] ComLV1,
        [Info("Com. LV2")] ComLV2,
        [Info("Com. LV3")] ComLV3,
        [Info("Kingdom")] Kingdom,
        [Info("Hyperion")] Hyperion,
        [Info("Geppetto")] Geppetto,
        [Info("Cid")] Cid,
        [Info("Leon")] Leon,
        [Info("Yuffie")] Yuffie,
        [Info("Aerith")] Aerith,
        [Info("Cactuar")] Cactuar,
        [Info("Chocobo")] Chocobo,
        [Info("Cindy")] Cindy,
        [Info("Shiva")] Shiva,
        [Info("Lamia")] Lamia,
        [Info("Sandy")] Sandy,
        [Info("Sylph")] Sylph,
        [Info("Carbuncle")] Carbuncle,
        [Info("Mindy")] Mindy,
        [Info("0x58 Unknown")] Unknown1,
        [Info("Bomb")] Bomb,
        [Info("Remora")] Remora,
        [Info("Ahriman")] Ahriman,
        [Info("Imp")] Imp,
        [Info("Siren")] Siren,
        [Info("Stingray")] Stingray,
        [Info("0x5F Unknown")] Unknown2,
        [Info("Adamant")] Adamant,
        [Info("0x61 Unknown")] Unknown3,
        [Info("Ifrit")] Ifrit,
        [Info("0x63 Unknown")] Unknown4,
        [Info("0x64 Unknown")] Unknown5,
        [Info("0x65 Unknown")] Unknown6,
        [Info("0x66 Unknown")] Unknown7,
        [Info("Deathguise")] Deathguise
    }
}
