/*
    Kingdom Hearts Save Editor
    Copyright (C) 2019 Luciano Ciccariello

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using KHSave.Attributes;

namespace KHSave.Trssv.Types
{
    public enum SpawnType
    {
        [Info] dw_01_Lv_AutoSave_01,
        [Info] dw_01_Lv_AutoSave_02,
        [Info] dw_01_Lv_AutoSave_03,
        [Info] dw_01_Lv_AutoSave_04,
        [Info] dw_01_Lv_AutoSave_05,
        [Info] dw_01_Lv_AutoSave_06,
        [Info] dw_01_Lv_Debug_01,
        [Info] dw_01_Lv_Debug_02,
        [Info] dw_01_Lv_Debug_03,
        [Info] dw_01_Lv_Skip_dw004,
        [Info] dw_01_Lv_Skip_dw005,
        [Info] dw_01_Lv_Skip_dw006,
        [Info] dw_01_Lv_Skip_dw007,
        [Info] dw_01_Lv_Skip_dw008,
        [Info] dw_01_Lv_Start_01,
        [Info] dw_01_Lv_Start_04,
        [Info] dw_01_Lv_Start_05,
        [Info] dw_02_Lv_AutoSave_01,
        [Info] dw_02_Lv_AutoSave_02,
        [Info] dw_02_Lv_AutoSave_03,
        [Info] dw_02_Lv_AutoSave_04,
        [Info] dw_02_Lv_AutoSave_05,
        [Info] dw_02_Lv_AutoSave_06,
        [Info] dw_02_Lv_AutoSave_07,
        [Info] dw_02_Lv_Debug_01,
        [Info] dw_02_Lv_Debug_02,
        [Info] dw_02_Lv_Debug_03,
        [Info] dw_02_Lv_Debug_04,
        [Info] dw_02_Lv_Debug_ReStart,
        [Info] dw_02_Lv_Retry_01,
        [Info] dw_02_Lv_Save_01,
        [Info] dw_02_Lv_Skip_dw011,
        [Info] dw_02_Lv_Skip_dw012,
        [Info] dw_02_Lv_Start_01,
        [Info] dw_02_Lv_Start_02,
        [Info] dw_02_Lv_Start_03,
        [Info] dw_03_Lv_AutoSave,
        [Info] dw_03_Lv_AutoSave_01,
        [Info] dw_03_Lv_AutoSave_02,
        [Info] dw_03_Lv_AutoSave_03,
        [Info] dw_03_Lv_AutoSave_04,
        [Info] dw_03_Lv_AutoSave_05,
        [Info] dw_03_Lv_AutoSave_06,
        [Info] dw_03_Lv_AutoSave_07,
        [Info] dw_03_Lv_AutoSave_08,
        [Info] dw_03_Lv_AutoSave_09,
        [Info] dw_03_Lv_ChallengeClear,
        [Info] dw_03_Lv_Clear_dw_04,
        [Info] dw_03_Lv_Clear_dw_05,
        [Info] dw_03_Lv_Clear_dw_06,
        [Info] dw_03_Lv_Debug_01,
        [Info] dw_03_Lv_Save_01,
        [Info] dw_03_Lv_Start,
        [Info] dw_03_Lv_Start_01,
        [Info] dw_03_Lv_Start_02,
        [Info] dw_03_Lv_Start_03,
        [Info] dw_03_Lv_Start_04,
        [Info] dw_03_Lv_Start_05,
        [Info] dw_03_Lv_Start_06,
        [Info] dw_03_Lv_Start_07,
        [Info] dw_03_Lv_Start_08,
        [Info] dw_03_Lv_Start_09,
        [Info] dw_04_Lv_AutoSave_01,
        [Info] dw_04_Lv_AutoSave_02,
        [Info] dw_04_Lv_Start_01,
        [Info] dw_04_Lv_Start_02,
        [Info] dw_04_Lv_Start_03,
        [Info] dw_04_Lv_Start_04,
        [Info] dw_05_Lv_AutoSave_01,
        [Info] dw_05_Lv_AutoSave_02,
        [Info] dw_05_Lv_Returned_01,
        [Info] dw_05_Lv_Returned_02,
        [Info] dw_05_Lv_Returned_03,
        [Info] dw_05_Lv_Returned_04,
        [Info] dw_05_Lv_Start_01,
        [Info] dw_05_Lv_Start_02,
        [Info] dw_05_Lv_Start_03,
        [Info] dw_05_Lv_Start_04,
        [Info] dw_05_Normal,
        [Info] dw_06_Lv_AutoSave_01,
        [Info] dw_06_Lv_AutoSave_02,
        [Info] dw_06_Lv_AutoSave_03,
        [Info] dw_06_Lv_Restart_A1,
        [Info] dw_06_Lv_Restart_A2,
        [Info] dw_06_Lv_Restart_B,
        [Info] dw_06_Lv_Restart_C,
        [Info] dw_06_Lv_Restart_D,
        [Info] dw_06_Lv_Restart_E,
        [Info] dw_06_Lv_Restart_F,
        [Info] dw_06_Lv_Start_01,
        [Info] dw_08_debug_Start_01,
        [Info] dw_08_debug_Start_02,
        [Info] dw_08_debug_Start_03,
        [Info] dw_08_debug_Start_04,
        // [Info] dw_08_Lv_Save_03,
        [Info] dw_09_Lv_AutoSave_02,
        [Info] dw_09_Lv_Retry_01,
        [Info] dw_09_Lv_Save_01,
        [Info] dw_09_Lv_skip_dw025,
        [Info] dw_09_Lv_skip_dw026,
        [Info] dw_09_Lv_Start_01,
        [Info] dw_09_Lv_Start_02,
        [Info] dw_10_Bt_Start_02,
        [Info] dw_11_Lv_Start_01,
        [Info] dw_12_Lv_Start_01,
        [Info] dw_52_Lv_Start_01,
        [Info] dw_53_Lv_Start_01,
        [Info] dw_59_Lv_Start_01,
    }
}
