/*
    Kingdom Hearts Save Editor
    Copyright (C) 2019 Luciano Ciccariello

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using KHSave.Attributes;

namespace KHSave.Lib3.Types
{
	public enum ArmorType : byte
	{
		[Info] Empty,
		[Armor("Hero's Belt")] HerosBelt,
		[Armor("Hero's Glove")] HerosGlove,
		[Armor("Shield Belt")] ShieldBelt,
		[Armor("DefenseBelt")] DefenseBelt,
		[Armor("Guardian Belt")] GuardianBelt,
		[Armor("Power Band")] PowerBand,
		[Armor("Buster Band")] BusterBand,
		[Armor("Buster Band+")] BusterBandPlus,
		[Armor("Cosmic Belt")] CosmicBelt,
		[Armor("Cosmic Belt+")] CosmicBeltPlus,
		[Armor("Fire Bangle")] FireBangle,
		[Armor("Firaga Bangle")] FiragaBangle,
		[Armor("Firaza Bangle")] FirazaBangle,
		[Armor("Fire Chain")] FireChain,
		[Armor("Blizzard Choker")] BlizzardChoker,
		[Armor("Blizzara Choker")] BlizzaraChoker,
		[Armor("Blizzaga Choker")] BlizzagaChoker,
		[Armor("Blizzard Chain")] BlizzardChain,
		[Armor("Thunder Trinket")] ThunderTrinket,
		[Armor("Thundaga Trinket")] ThundagaTrinket,
		[Armor("Thundaza Trinket")] ThundazaTrinket,
		[Armor("Thunder Chain")] ThunderChain,
		[Armor("Dark Anklet")] DarkAnklet,
		[Armor("Midnight Anklet")] MidnightAnklet,
		[Armor("Chaos Anklet")] ChaosAnklet,
		[Armor("Dark Chain")] DarkChain,
		[Armor("Divine Bandanna")] DivineBandanna,
		[Armor("Elven Bandanna")] ElvenBandanna,
		[Armor("Aqua Chaplet")] AquaChaplet,
		[Armor("Wind Fan")] WindFan,
		[Armor("Storm Fan")] StormFan,
		[Armor("Aero Armlet")] AeroArmlet,
		[Armor("Aegis Chain")] AegisChain,
		[Armor("Acrisius")] Acrisius,
		[Armor("Cosmic Chain")] CosmicChain,
		[Armor("Petite Ribbon")] PetiteRibbon,
		[Armor("Ribbon")] Ribbon,
		[Armor("Fira Bangle")] FiraBangle,
		[Armor("Blizzaza Choker")] BlizzazaChoker,
		[Armor("Thundara Trinket")] ThundaraTrinket,
		[Armor("Shadow Anklet")] ShadowAnklet,
		[Armor("Abas Chain")] AbasChain,
		[Armor("Acrisius+")] AcrisiusPlus,
		[Armor("Royal Ribbon")] RoyalRibbon,
    [Armor("Firefighter Rosette")] FirefighterRosette,
    [Armor("Umbrella Rosette")] UmbrellaRosette,
    [Armor("Snowman Rosette")] SnowmanRosette,
        [Armor("Insulator Rosette")] InsulatorRosette,
		Item30,
	    [Armor("Power Weight")] en,
	    [Armor("Magic Weight")] en2,
	    [Armor("Master Belt")] en3,
		Item35,
		Item36,
		Item37,
		Item38,
		Item39,
		Item3a,
		Item3b,
		Item3c,
		Item3d,
		Item3e,
		Item3f,
		Item40,
		Item41,
		Item42,
		Item43,
		Item44,
		Item45,
		Item46,
		Item47,
		Item48,
		Item49,
		Item4a,
		Item4b,
		Item4c,
		Item4d,
		Item4e,
		Item4f,
		Item50,
		Item51,
		Item52,
		Item53,
		Item54,
		Item55,
		Item56,
		Item57,
		Item58,
		Item59,
		Item5a,
		Item5b,
		Item5c,
		Item5d,
		Item5e,
		Item5f,
		Item60,
		Item61,
		Item62,
		Item63,
		Item64,
		Item65,
		Item66,
		Item67,
		Item68,
		Item69,
		Item6a,
		Item6b,
		Item6c,
		Item6d,
		Item6e,
		Item6f,
		Item70,
		Item71,
		Item72,
		Item73,
		Item74,
		Item75,
		Item76,
		Item77,
		Item78,
		Item79,
		Item7a,
		Item7b,
		Item7c,
		Item7d,
		Item7e,
		Item7f,
		Item80,
		Item81,
		Item82,
		Item83,
		Item84,
		Item85,
		Item86,
		Item87,
		Item88,
		Item89,
		Item8a,
		Item8b,
		Item8c,
		Item8d,
		Item8e,
		Item8f,
		Item90,
		Item91,
		Item92,
		Item93,
		Item94,
		Item95,
		Item96,
		Item97,
		Item98,
		Item99,
		Item9a,
		Item9b,
		Item9c,
		Item9d,
		Item9e,
		Item9f,
		Itema0,
		Itema1,
		Itema2,
		Itema3,
		Itema4,
		Itema5,
		Itema6,
		Itema7,
		Itema8,
		Itema9,
		Itemaa,
		Itemab,
		Itemac,
		Itemad,
		Itemae,
		Itemaf,
		Itemb0,
		Itemb1,
		Itemb2,
		Itemb3,
		Itemb4,
		Itemb5,
		Itemb6,
		Itemb7,
		Itemb8,
		Itemb9,
		Itemba,
		Itembb,
		Itembc,
		Itembd,
		Itembe,
		Itembf,
		Itemc0,
		Itemc1,
		Itemc2,
		Itemc3,
		Itemc4,
		Itemc5,
		Itemc6,
		Itemc7,
		Itemc8,
		Itemc9,
		Itemca,
		Itemcb,
		Itemcc,
		Itemcd,
		Itemce,
		Itemcf,
		Itemd0,
		Itemd1,
		Itemd2,
		Itemd3,
		Itemd4,
		Itemd5,
		Itemd6,
		Itemd7,
		Itemd8,
		Itemd9,
		Itemda,
		Itemdb,
		Itemdc,
		Itemdd,
		Itemde,
		Itemdf,
		Iteme0,
		Iteme1,
		Iteme2,
		Iteme3,
		Iteme4,
		Iteme5,
		Iteme6,
		Iteme7,
		Iteme8,
		Iteme9,
		Itemea,
		Itemeb,
		Itemec,
		Itemed,
		Itemee,
		Itemef,
		Itemf0,
		Itemf1,
		Itemf2,
		Itemf3,
		Itemf4,
		Itemf5,
		Itemf6,
		Itemf7,
		Itemf8,
		Itemf9,
		Itemfa,
		Itemfb,
		Itemfc,
		Itemfd,
		Itemfe,
		Itemff,
	}
}
