using KHSave.Attributes;

namespace KHSave.LibPersona5.Types
{
    public class SkillAttribute : InfoAttribute
    {
        public SkillAttribute(string name = null) : base(name) { }
    }
    public class HitSkillAttribute : SkillAttribute
    {
        public HitSkillAttribute(string name = null) : base(name) { }
    }
    public class GunSkillAttribute : SkillAttribute
    {
        public GunSkillAttribute(string name = null) : base(name) { }
    }
    public class FireSkillAttribute : SkillAttribute
    {
        public FireSkillAttribute(string name = null) : base(name) { }
    }
    public class IceSkillAttribute : SkillAttribute
    {
        public IceSkillAttribute(string name = null) : base(name) { }
    }
    public class WindSkillAttribute : SkillAttribute
    {
        public WindSkillAttribute(string name = null) : base(name) { }
    }
    public class ThunderSkillAttribute : SkillAttribute
    {
        public ThunderSkillAttribute(string name = null) : base(name) { }
    }
    public class BlessSkillAttribute : SkillAttribute
    {
        public BlessSkillAttribute(string name = null) : base(name) { }
    }
    public class DeathSkillAttribute : SkillAttribute
    {
        public DeathSkillAttribute(string name = null) : base(name) { }
    }
    public class AlmightySkillAttribute : SkillAttribute
    {
        public AlmightySkillAttribute(string name = null) : base(name) { }
    }
    public class NuclearSkillAttribute : SkillAttribute
    {
        public NuclearSkillAttribute(string name = null) : base(name) { }
    }
    public class PsychoSkillAttribute : SkillAttribute
    {
        public PsychoSkillAttribute(string name = null) : base(name) { }
    }
    public class SupportSkillAttribute : SkillAttribute
    {
        public SupportSkillAttribute(string name = null) : base(name) { }
    }
    public class AutoSkillAttribute : SkillAttribute
    {
        public AutoSkillAttribute(string name = null) : base(name) { }
    }
    public class PoisonSkillAttribute : SkillAttribute
    {
        public PoisonSkillAttribute(string name = null) : base(name) { }
    }
    public class HealSkillAttribute : SkillAttribute
    {
        public HealSkillAttribute(string name = null) : base(name) { }
    }
    public class SpecialSkillAttribute : SkillAttribute
    {
        public SpecialSkillAttribute(string name = null) : base(name) { }
    }

    public enum Skill : short
    {
        [Skill("-")] Empty,
        [Unused] Skill1,
        [Unused] Skill2,
        [Unused] Skill3,
        [Unused] Skill4,
        [Unused] Skill5,
        [Unused] Skill6,
        [Unused] Skill7,
        [Unused] Skill8,
        [Unused] Skill9,
        [FireSkill("Agi")] Skill10,
        [FireSkill("Agilao")] Skill11,
        [FireSkill("Agidyne")] Skill12,
        [FireSkill("Maragi")] Skill13,
        [FireSkill("Maragion")] Skill14,
        [FireSkill("Maragidyne")] Skill15,
        [FireSkill("Agi")] Skill16,
        [FireSkill("Maragi")] Skill17,
        [Unused] Skill18,
        [Unused] Skill19,
        [IceSkill("Bufu")] Skill20,
        [IceSkill("Bufula")] Skill21,
        [IceSkill("Bufudyne")] Skill22,
        [IceSkill("Mabufu")] Skill23,
        [IceSkill("Mabufula")] Skill24,
        [IceSkill("Mabufudyne")] Skill25,
        [IceSkill("Bufu")] Skill26,
        [IceSkill("Mabufu")] Skill27,
        [Unused] Skill28,
        [Unused] Skill29,
        [WindSkill("Garu")] Skill30,
        [WindSkill("Garula")] Skill31,
        [WindSkill("Garudyne")] Skill32,
        [WindSkill("Magaru")] Skill33,
        [WindSkill("Magarula")] Skill34,
        [WindSkill("Magarudyne")] Skill35,
        [WindSkill("Garu")] Skill36,
        [Unused] Skill37,
        [Unused] Skill38,
        [Unused] Skill39,
        [ThunderSkill("Zio")] Skill40,
        [ThunderSkill("Zionga")] Skill41,
        [ThunderSkill("Ziodyne")] Skill42,
        [ThunderSkill("Mazio")] Skill43,
        [ThunderSkill("Mazionga")] Skill44,
        [ThunderSkill("Maziodyne")] Skill45,
        [ThunderSkill("Zio")] Skill46,
        [ThunderSkill("Mazio")] Skill47,
        [Unused] Skill48,
        [Unused] Skill49,
        [BlessSkill("Hama")] Skill50,
        [BlessSkill("Hamaon")] Skill51,
        [BlessSkill("Mahama")] Skill52,
        [BlessSkill("Mahamaon")] Skill53,
        [BlessSkill("Kouha")] Skill54,
        [BlessSkill("Kouga")] Skill55,
        [BlessSkill("Kougaon")] Skill56,
        [BlessSkill("Makouha")] Skill57,
        [BlessSkill("Makouga")] Skill58,
        [BlessSkill("Makougaon")] Skill59,
        [DeathSkill("Mudo")] Skill60,
        [DeathSkill("Mudoon")] Skill61,
        [DeathSkill("Mamudo")] Skill62,
        [DeathSkill("Mamudoon")] Skill63,
        [DeathSkill("Eiha")] Skill64,
        [DeathSkill("Eiga")] Skill65,
        [DeathSkill("Eigaon")] Skill66,
        [DeathSkill("Maeiha")] Skill67,
        [DeathSkill("Maeiga")] Skill68,
        [DeathSkill("Maeigaon")] Skill69,
        [AlmightySkill("Megido")] Skill70,
        [AlmightySkill("Megidola")] Skill71,
        [AlmightySkill("Megidolaon")] Skill72,
        [NuclearSkill("Frei")] Skill73,
        [NuclearSkill("Freila")] Skill74,
        [NuclearSkill("Freidyne")] Skill75,
        [NuclearSkill("Mafrei")] Skill76,
        [NuclearSkill("Mafreila")] Skill77,
        [NuclearSkill("Mafreidyne")] Skill78,
        [Unused] Skill79,
        [PoisonSkill("Dazzler")] Skill80,
        [PoisonSkill("Nocturnal Flash")] Skill81,
        [PoisonSkill("Pulinpa")] Skill82,
        [PoisonSkill("Tentarafoo")] Skill83,
        [PoisonSkill("Evil Touch")] Skill84,
        [PoisonSkill("Evil Smile")] Skill85,
        [PoisonSkill("Makajama")] Skill86,
        [PoisonSkill("Makajamaon")] Skill87,
        [PoisonSkill("Famine's Breath")] Skill88,
        [PoisonSkill("Famine's Scream")] Skill89,
        [PoisonSkill("Dormina")] Skill90,
        [PoisonSkill("Lullaby")] Skill91,
        [PoisonSkill("Taunt")] Skill92,
        [PoisonSkill("Wage War")] Skill93,
        [PoisonSkill("Ominous Words")] Skill94,
        [PoisonSkill("Abysmal Surge")] Skill95,
        [PoisonSkill("Marin Karin")] Skill96,
        [PoisonSkill("Brain Jack")] Skill97,
        [AlmightySkill("Trapped Rat")] Skill98,
        [Unused] Skill99,
        [AlmightySkill("Self-destruct")] Skill100,
        [AlmightySkill("Self-destruct")] Skill101,
        [AlmightySkill("Self-destruct")] Skill102,
        [AlmightySkill("Life Drain")] Skill103,
        [AlmightySkill("Spirit Drain")] Skill104,
        [AlmightySkill("Life Leech")] Skill105,
        [AlmightySkill("Spirit Leech")] Skill106,
        [AlmightySkill("Spirit Drain")] Skill107,
        [Unused] Skill108,
        [Unused] Skill109,
        [AlmightySkill("Foul Breath")] Skill110,
        [AlmightySkill("Stagnant Air")] Skill111,
        [AlmightySkill("Reverse Rub")] Skill112,
        [AlmightySkill("Ghastly Wail")] Skill113,
        [Unused] Skill114,
        [Unused] Skill115,
        [Unused] Skill116,
        [Unused] Skill117,
        [Unused] Skill118,
        [Unused] Skill119,
        [FireSkill("Inferno")] Skill120,
        [FireSkill("Blazing Hell")] Skill121,
        [AutoSkill("Low Burn")] Skill122,
        [AutoSkill("Mid Burn")] Skill123,
        [AutoSkill("High Burn")] Skill124,
        [AutoSkill("Low Freeze")] Skill125,
        [AutoSkill("Mid Freeze")] Skill126,
        [AutoSkill("High Freeze")] Skill127,
        [AutoSkill("Low Shock")] Skill128,
        [AutoSkill("Mid Shock")] Skill129,
        [IceSkill("Diamond Dust")] Skill130,
        [IceSkill("Ice Age")] Skill131,
        [AutoSkill("High Shock")] Skill132,
        [AutoSkill("Low Dizzy")] Skill133,
        [AutoSkill("Mid Dizzy")] Skill134,
        [AutoSkill("High Dizzy")] Skill135,
        [AutoSkill("Low Confuse")] Skill136,
        [AutoSkill("Mid Confuse")] Skill137,
        [AutoSkill("High Confuse")] Skill138,
        [AutoSkill("Low Fear")] Skill139,
        [WindSkill("Panta Rhei")] Skill140,
        [WindSkill("Vacuum Wave")] Skill141,
        [AutoSkill("Mid Fear")] Skill142,
        [AutoSkill("High Fear")] Skill143,
        [AutoSkill("Low Forget")] Skill144,
        [AutoSkill("Mid Forget")] Skill145,
        [AutoSkill("High Forget")] Skill146,
        [AutoSkill("Low Brainwash")] Skill147,
        [AutoSkill("Mid Brainwash")] Skill148,
        [AutoSkill("High Brainwash")] Skill149,
        [ThunderSkill("Thunder Reign")] Skill150,
        [ThunderSkill("Wild Thunder")] Skill151,
        [AutoSkill("Low Sleep")] Skill152,
        [AutoSkill("Mid Sleep")] Skill153,
        [AutoSkill("High Sleep")] Skill154,
        [AutoSkill("Low Rage")] Skill155,
        [AutoSkill("Mid Rage")] Skill156,
        [AutoSkill("High Rage")] Skill157,
        [AutoSkill("Low Despair")] Skill158,
        [AutoSkill("Mid Despair")] Skill159,
        [BlessSkill("Divine Judgment")] Skill160,
        [BlessSkill("Samsara")] Skill161,
        [AutoSkill("High Despair")] Skill162,
        [AutoSkill("Low All Ail")] Skill163,
        [AutoSkill("Mid All Ail")] Skill164,
        [AutoSkill("High All Ail")] Skill165,
        [Unused] Skill166,
        [Unused] Skill167,
        [Unused] Skill168,
        [Unused] Skill169,
        [DeathSkill("Demonic Decree")] Skill170,
        [DeathSkill("Die For Me!")] Skill171,
        [Unused] Skill172,
        [Unused] Skill173,
        [Unused] Skill174,
        [Unused] Skill175,
        [NuclearSkill("Atomic Flare")] Skill176,
        [NuclearSkill("Cosmic Flare")] Skill177,
        [Unused] Skill178,
        [Unused] Skill179,
        [AlmightySkill("Black Viper")] Skill180,
        [AlmightySkill("Morning Star")] Skill181,
        [Unused] Skill182,
        [Unused] Skill183,
        [Unused] Skill184,
        [Unused] Skill185,
        [Unused] Skill186,
        [Unused] Skill187,
        [Unused] Skill188,
        [Unused] Skill189,
        [PsychoSkill("Psi")] Skill190,
        [PsychoSkill("Psio")] Skill191,
        [PsychoSkill("Psiodyne")] Skill192,
        [PsychoSkill("Mapsi")] Skill193,
        [PsychoSkill("Mapsio")] Skill194,
        [PsychoSkill("Mapsiodyne")] Skill195,
        [Unused] Skill196,
        [PsychoSkill("Psycho Force")] Skill197,
        [PsychoSkill("Psycho Blast")] Skill198,
        [Unused] Skill199,
        [HitSkill("Lunge")] Skill200,
        [HitSkill("Assault Dive")] Skill201,
        [HitSkill("Megaton Raid")] Skill202,
        [HitSkill("God's Hand")] Skill203,
        [HitSkill("Lunge")] Skill204,
        [HitSkill("Lucky Punch")] Skill205,
        [HitSkill("Miracle Punch")] Skill206,
        [Unused] Skill207,
        [Unused] Skill208,
        [Unused] Skill209,
        [HitSkill("Cleave")] Skill210,
        [HitSkill("Giant Slice")] Skill211,
        [HitSkill("Brave Blade")] Skill212,
        [HitSkill("Sword Dance")] Skill213,
        [Unused] Skill214,
        [HitSkill("Hassou Tobi")] Skill215,
        [HitSkill("Ayamur")] Skill216,
        [Unused] Skill217,
        [Unused] Skill218,
        [Unused] Skill219,
        [HitSkill("Cornered Fang")] Skill220,
        [HitSkill("Rising Slash")] Skill221,
        [HitSkill("Deadly Fury")] Skill222,
        [Unused] Skill223,
        [GunSkill("Snap")] Skill224,
        [GunSkill("Triple Down")] Skill225,
        [GunSkill("One-shot Kill")] Skill226,
        [GunSkill("Riot Gun")] Skill227,
        [Unused] Skill228,
        [Unused] Skill229,
        [HitSkill("Vajra Blast")] Skill230,
        [HitSkill("Vorpal Blade")] Skill231,
        [Unused] Skill232,
        [Unused] Skill233,
        [Unused] Skill234,
        [HitSkill("Vicious Strike")] Skill235,
        [HitSkill("Heat Wave")] Skill236,
        [HitSkill("Gigantomachia")] Skill237,
        [Unused] Skill238,
        [Unused] Skill239,
        [Unused] Skill240,
        [HitSkill("Rampage")] Skill241,
        [HitSkill("Swift Strike")] Skill242,
        [HitSkill("Deathbound")] Skill243,
        [HitSkill("Agneyastra")] Skill244,
        [Unused] Skill245,
        [Unused] Skill246,
        [HitSkill("Rising Slash")] Skill247,
        [HitSkill("Deadly Fury")] Skill248,
        [Unused] Skill249,
        [HitSkill("Double Fangs")] Skill250,
        [Unused] Skill251,
        [Unused] Skill252,
        [HitSkill("Tempest Slash")] Skill253,
        [HitSkill("Myriad Slashes")] Skill254,
        [Unused] Skill255,
        [Unused] Skill256,
        [Unused] Skill257,
        [Unused] Skill258,
        [Unused] Skill259,
        [HitSkill("Sledgehammer")] Skill260,
        [HitSkill("Skull Cracker")] Skill261,
        [HitSkill("Terror Claw")] Skill262,
        [HitSkill("Headbutt")] Skill263,
        [HitSkill("Stomach Blow")] Skill264,
        [HitSkill("Dream Needle")] Skill265,
        [HitSkill("Hysterical Slap")] Skill266,
        [HitSkill("Negative Pile")] Skill267,
        [HitSkill("Brain Shake")] Skill268,
        [Unused] Skill269,
        [HitSkill("Flash Bomb")] Skill270,
        [HitSkill("Mind Slice")] Skill271,
        [HitSkill("Bloodbath")] Skill272,
        [HitSkill("Memory Blow")] Skill273,
        [HitSkill("Insatiable Strike")] Skill274,
        [HitSkill("Dormin Rush")] Skill275,
        [HitSkill("Oni-Kagura")] Skill276,
        [HitSkill("Bad Beat")] Skill277,
        [HitSkill("Brain Buster")] Skill278,
        [Unused] Skill279,
        [GunSkill("Handgun")] Skill280,
        [GunSkill("Shotgun")] Skill281,
        [GunSkill("Slingshot")] Skill282,
        [GunSkill("Machine Gun")] Skill283,
        [GunSkill("Assault Rifle")] Skill284,
        [GunSkill("Revolver")] Skill285,
        [GunSkill("Grenade Launcher")] Skill286,
        [GunSkill("Laser Gun")] Skill287,
        [Unused] Skill288,
        [Unused] Skill289,
        [Unused] Skill290,
        [Unused] Skill291,
        [Unused] Skill292,
        [Unused] Skill293,
        [Unused] Skill294,
        [Unused] Skill295,
        [Unused] Skill296,
        [Unused] Skill297,
        [Unused] Skill298,
        [Unused] Skill299,
        [HealSkill("Dia")] Skill300,
        [HealSkill("Diarama")] Skill301,
        [HealSkill("Diarahan")] Skill302,
        [Unused] Skill303,
        [Unused] Skill304,
        [HealSkill("Media")] Skill305,
        [HealSkill("Mediarama")] Skill306,
        [HealSkill("Mediarahan")] Skill307,
        [Unused] Skill308,
        [Unused] Skill309,
        [HealSkill("Recarm")] Skill310,
        [HealSkill("Samarecarm")] Skill311,
        [HealSkill("Recarmdra")] Skill312,
        [Unused] Skill313,
        [Unused] Skill314,
        [HealSkill("Amrita Drop")] Skill315,
        [HealSkill("Amrita Shower")] Skill316,
        [HealSkill("BLANK")] Skill317,
        [HealSkill("Salvation")] Skill318,
        [Unused] Skill319,
        [Unused] Skill320,
        [Unused] Skill321,
        [Unused] Skill322,
        [Unused] Skill323,
        [Unused] Skill324,
        [HealSkill("Patra")] Skill325,
        [HealSkill("BLANK")] Skill326,
        [HealSkill("Energy Shower")] Skill327,
        [HealSkill("Energy Drop")] Skill328,
        [HealSkill("Baisudi")] Skill329,
        [HealSkill("Me Patra")] Skill330,
        [HealSkill("Mabaisudi")] Skill331,
        [Unused] Skill332,
        [Unused] Skill333,
        [Unused] Skill334,
        [SupportSkill("Tarukaja")] Skill335,
        [SupportSkill("Rakukaja")] Skill336,
        [SupportSkill("Sukukaja")] Skill337,
        [SupportSkill("Heat Riser")] Skill338,
        [Unused] Skill339,
        [SupportSkill("Matarukaja")] Skill340,
        [SupportSkill("Marakukaja")] Skill341,
        [SupportSkill("Masukukaja")] Skill342,
        [SupportSkill("Thermopylae")] Skill343,
        [Unused] Skill344,
        [SupportSkill("Tarunda")] Skill345,
        [SupportSkill("Rakunda")] Skill346,
        [SupportSkill("Sukunda")] Skill347,
        [SupportSkill("Debilitate")] Skill348,
        [Unused] Skill349,
        [SupportSkill("Matarunda")] Skill350,
        [SupportSkill("Marakunda")] Skill351,
        [SupportSkill("Masukunda")] Skill352,
        [Unused] Skill353,
        [Unused] Skill354,
        [SupportSkill("Dekunda")] Skill355,
        [SupportSkill("Dekaja")] Skill356,
        [Unused] Skill357,
        [Unused] Skill358,
        [Unused] Skill359,
        [SupportSkill("Charge")] Skill360,
        [SupportSkill("Concentrate")] Skill361,
        [Unused] Skill362,
        [Unused] Skill363,
        [Unused] Skill364,
        [SupportSkill("Rebellion")] Skill365,
        [SupportSkill("Revolution")] Skill366,
        [Unused] Skill367,
        [Unused] Skill368,
        [Unused] Skill369,
        [SupportSkill("Tetrakarn")] Skill370,
        [SupportSkill("Makarakarn")] Skill371,
        [SupportSkill("Tetraja")] Skill372,
        [Unused] Skill373,
        [Unused] Skill374,
        [SupportSkill("Tetra Break")] Skill375,
        [SupportSkill("Makara Break")] Skill376,
        [Unused] Skill377,
        [Unused] Skill378,
        [Unused] Skill379,
        [SupportSkill("Fire Wall")] Skill380,
        [SupportSkill("Ice Wall")] Skill381,
        [SupportSkill("Elec Wall")] Skill382,
        [SupportSkill("Wind Wall")] Skill383,
        [Unused] Skill384,
        [SupportSkill("Fire Break")] Skill385,
        [SupportSkill("Ice Break")] Skill386,
        [SupportSkill("Wind Break")] Skill387,
        [SupportSkill("Elec Break")] Skill388,
        [Unused] Skill389,
        [SupportSkill("Trafuri")] Skill390,
        [SupportSkill("Traesto")] Skill391,
        [Unused] Skill392,
        [SupportSkill("Nuke Wall")] Skill393,
        [SupportSkill("Psy Wall")] Skill394,
        [SupportSkill("Nuke Break")] Skill395,
        [SupportSkill("Psy Break")] Skill396,
        [Unused] Skill397,
        [Unused] Skill398,
        [Unused] Skill399,
        [AlmightySkill("All-out Lv 1")] Skill400,
        [AlmightySkill("All-out Lv 2")] Skill401,
        [AlmightySkill("All-out Lv 3")] Skill402,
        [SupportSkill("Emergency Escape")] Skill403,
        [Unused] Skill404,
        [AlmightySkill("Down Shot")] Skill405,
        [SpecialSkill("Summon")] Skill406,
        [SpecialSkill("Call for Backup")] Skill407,
        [Unused] Skill408,
        [SpecialSkill("Barrage")] Skill409,
        [AlmightySkill("Follow Crush")] Skill410,
        [AlmightySkill("Follow Claw")] Skill411,
        [AlmightySkill("Follow Whip")] Skill412,
        [AlmightySkill("Follow Blade")] Skill413,
        [AlmightySkill("Follow Knuckle")] Skill414,
        [AlmightySkill("Follow Axe")] Skill415,
        [AlmightySkill("Follow Saber")] Skill416,
        [SpecialSkill("Dispose Item")] Skill417,
        [SpecialSkill("Heal Enemy")] Skill418,
        [AlmightySkill("Death (Despair)")] Skill419,
        [AlmightySkill("Ally1 Follow-Up")] Skill420,
        [AlmightySkill("Ally2 Follow-Up")] Skill421,
        [AlmightySkill("Ally3 Follow-Up")] Skill422,
        [AlmightySkill("Ally4 Follow-Up")] Skill423,
        [AlmightySkill("Ally5 Follow-Up")] Skill424,
        [AlmightySkill("Ally6 Follow-Up")] Skill425,
        [AlmightySkill("Ally7 Follow-Up")] Skill426,
        [SpecialSkill("Power Up Enemy")] Skill427,
        [SpecialSkill("Power Up Enemy")] Skill428,
        [SpecialSkill("Power Up Enemy")] Skill429,
        [SupportSkill("Steal Info")] Skill430,
        [SpecialSkill("Sup Matarukaja")] Skill431,
        [SpecialSkill("Sup Marakukaja")] Skill432,
        [SpecialSkill("Sup Masukukaja")] Skill433,
        [SpecialSkill("Sup All Kaja")] Skill434,
        [SpecialSkill("Sup Charge")] Skill435,
        [SpecialSkill("Sup HP +30%")] Skill436,
        [SpecialSkill("Sup SP +10%")] Skill437,
        [SpecialSkill("Sup Escape Route")] Skill438,
        [SpecialSkill("Sup Third Eye")] Skill439,
        [SpecialSkill("Subrecover HP")] Skill440,
        [SpecialSkill("Subrecover SP")] Skill441,
        [SpecialSkill("Analysis")] Skill442,
        [SpecialSkill("Deep Analysis")] Skill443,
        [SpecialSkill("Full Analysis")] Skill444,
        [AlmightySkill("All-Out Attack")] Skill445,
        [WindSkill("Dust Flurry")] Skill446,
        [HitSkill("Tongue Whip")] Skill447,
        [HitSkill("Whip Strike")] Skill448,
        [SupportSkill("Lustful Slurp")] Skill449,
        [HealSkill("Libido Boost")] Skill450,
        [HitSkill("Golden Knife")] Skill451,
        [HitSkill("Lick")] Skill452,
        [AlmightySkill("Gold Medal Spike")] Skill453,
        [HitSkill("Volleyball Assault")] Skill454,
        [WindSkill("Maelstrom")] Skill455,
        [FireSkill("Flame Dance")] Skill456,
        [IceSkill("Silent Snowscape")] Skill457,
        [ThunderSkill("Thunderclap")] Skill458,
        [DeathSkill("Maeiga")] Skill459,
        [PoisonSkill("Hunger All")] Skill460,
        [GunSkill("Ocular Vulcan")] Skill461,
        [FireSkill("Missile Party")] Skill462,
        [PoisonSkill("Fear Gas")] Skill463,
        [SpecialSkill("Super VIP Form")] Skill464,
        [AlmightySkill("March of the Piggy")] Skill465,
        [HitSkill("Sphinx Swipe")] Skill466,
        [WindSkill("Wing Blast")] Skill467,
        [SpecialSkill("Rapid Ascent")] Skill468,
        [HitSkill("Sphinx Dive")] Skill469,
        [AlmightySkill("Dreadful Scream")] Skill470,
        [HitSkill("Bite")] Skill471,
        [SupportSkill("Restore")] Skill472,
        [AlmightySkill("The Artist's Grace")] Skill473,
        [SpecialSkill("Work Order")] Skill474,
        [SpecialSkill("Sacrifice Order")] Skill475,
        [AlmightySkill("Selfless Devotion")] Skill476,
        [AlmightySkill("Penalty")] Skill477,
        [HitSkill("Coin Attack")] Skill478,
        [HitSkill("Severing Slash")] Skill479,
        [GunSkill("Gatling Gun")] Skill480,
        [AlmightySkill("Berserker Dance")] Skill481,
        [AlmightySkill("Roulette: HP")] Skill482,
        [AlmightySkill("Roulette: SP")] Skill483,
        [SpecialSkill("Roulette: Money")] Skill484,
        [SupportSkill("Roulette: Aid 1")] Skill485,
        [SupportSkill("Roulette: Aid 2")] Skill486,
        [SupportSkill("Roulette: Aid 3")] Skill487,
        [HitSkill("Beast King's Wrath")] Skill488,
        [SupportSkill("Hunting Stance")] Skill489,
        [AlmightySkill("Arm of Destruction")] Skill490,
        [SupportSkill("Gryphon's Breath")] Skill491,
        [AlmightySkill("Royal Wing Beam")] Skill492,
        [AlmightySkill("Cannon Fire")] Skill493,
        [AlmightySkill("Cannon Barrage")] Skill494,
        [SupportSkill("Unholy Convergence")] Skill495,
        [AlmightySkill("Pyramid Blast")] Skill496,
        [HitSkill("Tyrant's Fist")] Skill497,
        [SupportSkill("Tyrant's Glare")] Skill498,
        [AlmightySkill("Tyrant's Wave")] Skill499,
        [HealSkill("Fig Seed")] Skill500,
        [HealSkill("Medicine")] Skill501,
        [HealSkill("Ointment")] Skill502,
        [HealSkill("Antibiotic Gel")] Skill503,
        [HealSkill("Life Stone")] Skill504,
        [HealSkill("Bead")] Skill505,
        [HealSkill("Value Medicine")] Skill506,
        [HealSkill("Medical Kit")] Skill507,
        [HealSkill("Maka Leaf")] Skill508,
        [HealSkill("Bead Chain")] Skill509,
        [HealSkill("Soul Drop")] Skill510,
        [HealSkill("Snuff Soul")] Skill511,
        [HealSkill("Chewing Soul")] Skill512,
        [HealSkill("Soul Food")] Skill513,
        [HealSkill("Revival Bead")] Skill514,
        [HealSkill("Balm of Life")] Skill515,
        [HealSkill("Royel Jelly")] Skill516,
        [HealSkill("Organic Herb")] Skill517,
        [HealSkill("Disclose")] Skill518,
        [HealSkill("Tranquilizer")] Skill519,
        [HealSkill("Kopi Luwak")] Skill520,
        [SupportSkill("Goho-M")] Skill521,
        [SupportSkill("Vanish Ball")] Skill522,
        [HealSkill("Soma")] Skill523,
        [HealSkill("Amrita Soda")] Skill524,
        [HealSkill("Hiranya")] Skill525,
        [HealSkill("Muscle Drink")] Skill526,
        [HealSkill("Odd Morsel")] Skill527,
        [HealSkill("Rancid Gravy")] Skill528,
        [HealSkill("Plume of Dusk")] Skill529,
        [SupportSkill("Magic Mirror")] Skill530,
        [SupportSkill("Physical Mirror")] Skill531,
        [SupportSkill("Universe Ring")] Skill532,
        [SupportSkill("Sleipnir")] Skill533,
        [SupportSkill("Obsidian Mirror")] Skill534,
        [SupportSkill("Purifying Water")] Skill535,
        [SupportSkill("Purifying Salt")] Skill536,
        [FireSkill("Firecracker")] Skill537,
        [FireSkill("San-zun Tama")] Skill538,
        [IceSkill("Ice Cube")] Skill539,
        [IceSkill("Dry Ice")] Skill540,
        [WindSkill("Pinwheel")] Skill541,
        [WindSkill("Yashichi")] Skill542,
        [ThunderSkill("Ball Lightning")] Skill543,
        [ThunderSkill("Tesla Coil")] Skill544,
        [AlmightySkill("Smart Bomb")] Skill545,
        [BlessSkill("Segami Rice")] Skill546,
        [DeathSkill("Curse Paper")] Skill547,
        [FireSkill("Flame Magatama")] Skill548,
        [WindSkill("Wind Magatama")] Skill549,
        [IceSkill("Freeze Magatama")] Skill550,
        [ThunderSkill("Bolt Magatama")] Skill551,
        [HealSkill("Homunculus")] Skill552,
        [HealSkill("Removal Potion")] Skill553,
        [BlessSkill("Kouga Ball")] Skill554,
        [BlessSkill("Makouha Ball")] Skill555,
        [DeathSkill("Eiga Ball")] Skill556,
        [DeathSkill("Maeiga Ball")] Skill557,
        [PsychoSkill("Psio Ball")] Skill558,
        [PsychoSkill("Mapsi Ball")] Skill559,
        [NuclearSkill("Freila Ball")] Skill560,
        [NuclearSkill("Mafrei Ball")] Skill561,
        [NuclearSkill("Nuke Magatama")] Skill562,
        [PsychoSkill("Psy Magatama")] Skill563,
        [BlessSkill("Bless Magatama")] Skill564,
        [DeathSkill("Curse Magatama")] Skill565,
        [HealSkill("Cooking")] Skill566,
        [HealSkill("Snack")] Skill567,
        [HealSkill("Shoes 1")] Skill568,
        [HealSkill("Shoes 2")] Skill569,
        [HealSkill("Shoes 3")] Skill570,
        [HealSkill("Juice Bar 1")] Skill571,
        [HealSkill("Juice Bar 2")] Skill572,
        [HealSkill("Juice Bar 3")] Skill573,
        [HealSkill("Juice Bar 4")] Skill574,
        [HealSkill("Energy Drink 1")] Skill575,
        [HealSkill("Energy Drink 2")] Skill576,
        [HealSkill("Energy Drink 3")] Skill577,
        [HealSkill("Soda 1")] Skill578,
        [HealSkill("Soda 2")] Skill579,
        [HealSkill("Soda 3")] Skill580,
        [HealSkill("Soda 4")] Skill581,
        [HealSkill("Ration 1 ")] Skill582,
        [HealSkill("Ration 2")] Skill583,
        [HealSkill("Ration 3")] Skill584,
        [HealSkill("Drug Store 1")] Skill585,
        [HealSkill("Drug Store 2")] Skill586,
        [HealSkill("Drug Store 3")] Skill587,
        [HealSkill("Drug Store 4")] Skill588,
        [HealSkill("Drug Store 5")] Skill589,
        [HealSkill("Drug Store 6")] Skill590,
        [HealSkill("Drug Store 7")] Skill591,
        [HealSkill("Drug Store 8")] Skill592,
        [HealSkill("Drug Store 9")] Skill593,
        [HealSkill("Drug Store 10")] Skill594,
        [HealSkill("Drug Store 11")] Skill595,
        [HealSkill("Drug Store 12")] Skill596,
        [HealSkill("Coffee 1")] Skill597,
        [SupportSkill("Coffee 2")] Skill598,
        [Unused] Skill599,
        [AlmightySkill("Twins Down Attack")] Skill600,
        [HitSkill("Caro Rod")] Skill601,
        [HitSkill("Caro Attack")] Skill602,
        [AlmightySkill("Megidolaon")] Skill603,
        [AlmightySkill("Rays of Control")] Skill604,
        [AlmightySkill("Rays of Control")] Skill605,
        [AlmightySkill("Rays of Control")] Skill606,
        [AlmightySkill("Rays of Control")] Skill607,
        [AlmightySkill("Arrow of Light")] Skill608,
        [AlmightySkill("Diffraction Arrow")] Skill609,
        [AlmightySkill("Light Edge")] Skill610,
        [SupportSkill("Gathering Light")] Skill611,
        [AlmightySkill("Eternal Light")] Skill612,
        [SupportSkill("Holy Change")] Skill613,
        [AlmightySkill("Distortion Wave")] Skill614,
        [SupportSkill("Tough Law")] Skill615,
        [SupportSkill("Frail Law")] Skill616,
        [SupportSkill("New Creation")] Skill617,
        [AlmightySkill("Distortion Surge")] Skill618,
        [AlmightySkill("Arrow of Light")] Skill619,
        [SupportSkill("Manifest Sword")] Skill620,
        [SupportSkill("Manifest Gun")] Skill621,
        [SupportSkill("Manifest Bell")] Skill622,
        [HitSkill("Sword of Judgment")] Skill623,
        [GunSkill("Capital Punishment")] Skill624,
        [SupportSkill("Manifest Book")] Skill625,
        [AlmightySkill("Distorted Lust")] Skill626,
        [AlmightySkill("Gospel")] Skill627,
        [AlmightySkill("Distorted Wrath")] Skill628,
        [AlmightySkill("Distorted Vanity")] Skill629,
        [SupportSkill("Song of Salvation")] Skill630,
        [AlmightySkill("Wrath of God")] Skill631,
        [AlmightySkill("Distorted Gluttony")] Skill632,
        [AlmightySkill("Distorted Envy")] Skill633,
        [SupportSkill("Song of Placation")] Skill634,
        [SupportSkill("Divine Apex")] Skill635,
        [AlmightySkill("Rays of Control")] Skill636,
        [AlmightySkill("Distorted Avarice")] Skill637,
        [HealSkill("Will of the People")] Skill638,
        [AlmightySkill("Rays of Control")] Skill639,
        [SpecialSkill("Moral Support")] Skill640,
        [SpecialSkill("Active Support")] Skill641,
        [SpecialSkill("Mental Hack")] Skill642,
        [SpecialSkill("Emergency Shift")] Skill643,
        [SpecialSkill("Final Guard")] Skill644,
        [SpecialSkill("Position Hack")] Skill645,
        [SpecialSkill("High Analyze")] Skill646,
        [SpecialSkill("Treasure Skimmer")] Skill647,
        [SpecialSkill("Subrecover HP EX")] Skill648,
        [SpecialSkill("Subrecover SP EX")] Skill649,
        [Unused] Skill650,
        [Unused] Skill651,
        [Unused] Skill652,
        [Unused] Skill653,
        [SupportSkill("Big Bang Order")] Skill654,
        [AlmightySkill("Roulette Time")] Skill655,
        [AlmightySkill("Trip-Upper")] Skill656,
        [AlmightySkill("Lust Sphere")] Skill657,
        [AlmightySkill("Down Shot 2")] Skill658,
        [AlmightySkill("Down Shot 3")] Skill659,
        [AlmightySkill("Down Shot 4")] Skill660,
        [GunSkill("Electro Attack")] Skill661,
        [AlmightySkill("Sinful Shell")] Skill662,
        [AlmightySkill("Follow Black")] Skill663,
        [Unused] Skill664,
        [AlmightySkill("Madara-Megido")] Skill665,
        [HealSkill("Curry Raku")] Skill666,
        [HealSkill("Enemy Benefit")] Skill667,
        [HealSkill("Diarahan")] Skill668,
        [HealSkill("Curry Suku")] Skill669,
        [SupportSkill("Decoy Ball")] Skill670,
        [SupportSkill("Super Decoy Ball")] Skill671,
        [HitSkill("Metabolic Wave")] Skill672,
        [AlmightySkill("Laevateinn")] Skill673,
        [SupportSkill("Desperation")] Skill674,
        [SupportSkill("Call of Chaos")] Skill675,
        [AlmightySkill("Big Bang Challenge")] Skill676,
        [AlmightySkill("Grail Light 2")] Skill677,
        [AlmightySkill("Megidola")] Skill678,
        [PoisonSkill("Rage Transmission")] Skill679,
        [HitSkill("Hundred Slaps")] Skill680,
        [AlmightySkill("Distorted Pride")] Skill681,
        [AlmightySkill("Divine Punishment")] Skill682,
        [HealSkill("Will of the People")] Skill683,
        [HitSkill("Wind Cutter")] Skill684,
        [GunSkill("Shoot Up")] Skill685,
        [HitSkill("Executive Punch")] Skill686,
        [AlmightySkill("Megidolaon")] Skill687,
        [HitSkill("Vorpal Blade")] Skill688,
        [AlmightySkill("Megidolaon")] Skill689,
        [HealSkill("Big Bang Burger")] Skill690,
        [HealSkill("Earth Burger")] Skill691,
        [HealSkill("Mars Burger")] Skill692,
        [HealSkill("Moon Burger")] Skill693,
        [HealSkill("Saturn Burger")] Skill694,
        [AlmightySkill("Justine Attack")] Skill695,
        [AlmightySkill("Caroline Attack")] Skill696,
        [HealSkill("Curry Makara")] Skill697,
        [HealSkill("Curry Tetra")] Skill698,
        [HealSkill("Curry Endure")] Skill699,
        [HealSkill("Curry Charge")] Skill700,
        [HealSkill("Curry Concentrate")] Skill701,
        [HealSkill("Curry Heat Riser")] Skill702,
        [Unused] Skill703,
        [HealSkill("Cadenza")] Skill704,
        [HitSkill("Cross Slash")] Skill705,
        [AlmightySkill("Door of Hades")] Skill706,
        [DeathSkill("Magatsu Mandala")] Skill707,
        [BlessSkill("Shining Arrows")] Skill708,
        [HitSkill("Beast Weaver")] Skill709,
        [FireSkill("Titanomachia")] Skill710,
        [DeathSkill("Abyssal Wings")] Skill711,
        [HealSkill("Oratario")] Skill712,
        [Unused] Skill713,
        [Unused] Skill714,
        [Unused] Skill715,
        [Unused] Skill716,
        [Unused] Skill717,
        [Unused] Skill718,
        [Unused] Skill719,
        [AlmightySkill("Megido")] Skill720,
        [AlmightySkill("Megidola")] Skill721,
        [AlmightySkill("Megidolaon")] Skill722,
        [HitSkill("Slam")] Skill723,
        [AlmightySkill("Megaton Raid")] Skill724,
        [AlmightySkill("One-shot Kill")] Skill725,
        [AlmightySkill("Inferno")] Skill726,
        [AlmightySkill("Diamond Dust")] Skill727,
        [Unused] Skill728,
        [Unused] Skill729,
        [HealSkill("Curry 1")] Skill730,
        [HealSkill("Curry 2")] Skill731,
        [HealSkill("Reviv-All")] Skill732,
        [HealSkill("Reviv-All Z")] Skill733,
        [Unused] Skill734,
        [Unused] Skill735,
        [SpecialSkill("Wild Talk")] Skill736,
        [SpecialSkill("Baton Pass")] Skill737,
        [SpecialSkill("Punk Talk")] Skill738,
        [SpecialSkill("Pickpocket")] Skill739,
        [SpecialSkill("Harisen Recovery")] Skill740,
        [SpecialSkill("Protect")] Skill741,
        [SpecialSkill("Girl Talk")] Skill742,
        [SpecialSkill("Crocodile Tears")] Skill743,
        [SpecialSkill("Sexy Technique")] Skill744,
        [SpecialSkill("Detective Talk")] Skill745,
        [SpecialSkill("Artist Talk")] Skill746,
        [SpecialSkill("Negotiating")] Skill747,
        [SpecialSkill("Fundraising")] Skill748,
        [SpecialSkill("Manipulation")] Skill749,
        [SpecialSkill("Mind Control")] Skill750,
        [SpecialSkill("Charisma Speech")] Skill751,
        [SpecialSkill("Brainiac Talk")] Skill752,
        [SpecialSkill("Sabaki")] Skill753,
        [SpecialSkill("Kakoi Kuzushi ")] Skill754,
        [SpecialSkill("Touryou")] Skill755,
        [SpecialSkill("Togo System")] Skill756,
        [SpecialSkill("Bullet Hail")] Skill757,
        [SpecialSkill("Warning Shot")] Skill758,
        [SpecialSkill("Celeb Talk")] Skill759,
        [SpecialSkill("Kitty Talk")] Skill760,
        [Unused] Skill761,
        [Unused] Skill762,
        [Unused] Skill763,
        [Unused] Skill764,
        [Unused] Skill765,
        [Unused] Skill766,
        [Unused] Skill767,
        [HitSkill("Brave Blade")] Skill768,
        [HitSkill("Assault Dive")] Skill769,
        [HitSkill("Terror Claw")] Skill770,
        [IceSkill("Bufudyne")] Skill771,
        [PsychoSkill("Psiodyne")] Skill772,
        [ThunderSkill("Mazionga")] Skill773,
        [ThunderSkill("Maziodyne")] Skill774,
        [DeathSkill("Maeiga")] Skill775,
        [DeathSkill("Maeigaon")] Skill776,
        [Unused] Skill777,
        [Unused] Skill778,
        [Unused] Skill779,
        [Unused] Skill780,
        [Unused] Skill781,
        [Unused] Skill782,
        [Unused] Skill783,
        [Unused] Skill784,
        [Unused] Skill785,
        [Unused] Skill786,
        [Unused] Skill787,
        [Unused] Skill788,
        [Unused] Skill789,
        [Unused] Skill790,
        [Unused] Skill791,
        [Unused] Skill792,
        [Unused] Skill793,
        [Unused] Skill794,
        [Unused] Skill795,
        [Unused] Skill796,
        [Unused] Skill797,
        [Unused] Skill798,
        [Unused] Skill799,
        [AutoSkill("Counter")] Skill800,
        [AutoSkill("Counterstrike")] Skill801,
        [AutoSkill("High Counter")] Skill802,
        [Unused] Skill803,
        [Unused] Skill804,
        [AutoSkill("Endure")] Skill805,
        [AutoSkill("Enduring Soul")] Skill806,
        [AutoSkill("BLANK")] Skill807,
        [AutoSkill("BLANK")] Skill808,
        [AutoSkill("Survival Trick")] Skill809,
        [AutoSkill("Dodge Fire")] Skill810,
        [AutoSkill("Evade Fire")] Skill811,
        [AutoSkill("Dodge Ice")] Skill812,
        [AutoSkill("Evade Ice")] Skill813,
        [AutoSkill("Dodge Wind")] Skill814,
        [AutoSkill("Evade Wind")] Skill815,
        [AutoSkill("Dodge Elec")] Skill816,
        [AutoSkill("Evade Elec")] Skill817,
        [AutoSkill("Dodge Phys")] Skill818,
        [AutoSkill("Evade Phys")] Skill819,
        [AutoSkill("Fire Boost")] Skill820,
        [AutoSkill("Fire Amp")] Skill821,
        [AutoSkill("Ice Boost")] Skill822,
        [AutoSkill("Ice Amp")] Skill823,
        [AutoSkill("Wind Boost")] Skill824,
        [AutoSkill("Wind Amp")] Skill825,
        [AutoSkill("Elec Boost")] Skill826,
        [AutoSkill("Elec Amp")] Skill827,
        [AutoSkill("Angelic Grace")] Skill828,
        [AutoSkill("Divine Grace")] Skill829,
        [AutoSkill("Regenerate 1")] Skill830,
        [AutoSkill("Regenerate 2")] Skill831,
        [AutoSkill("Regenerate 3")] Skill832,
        [AutoSkill("Dodge Bless")] Skill833,
        [AutoSkill("Dodge Curse")] Skill834,
        [AutoSkill("Invigorate 1")] Skill835,
        [AutoSkill("Invigorate 2")] Skill836,
        [AutoSkill("Invigorate 3")] Skill837,
        [AutoSkill("Evade Bless")] Skill838,
        [AutoSkill("Evade Curse")] Skill839,
        [AutoSkill("Attack Master")] Skill840,
        [AutoSkill("Auto-Mataru")] Skill841,
        [Unused] Skill842,
        [AutoSkill("Defense Master")] Skill843,
        [AutoSkill("Auto-Maraku")] Skill844,
        [Unused] Skill845,
        [AutoSkill("Speed Master")] Skill846,
        [AutoSkill("Auto-Masuku")] Skill847,
        [Unused] Skill848,
        [Unused] Skill849,
        [AutoSkill("Fast Heal")] Skill850,
        [AutoSkill("Insta-Heal")] Skill851,
        [AutoSkill("Arms Master")] Skill852,
        [AutoSkill("Spell Master")] Skill853,
        [Unused] Skill854,
        [AutoSkill("Sharp Student")] Skill855,
        [AutoSkill("Apt Pupil")] Skill856,
        [AutoSkill("Ali Dance")] Skill857,
        [AutoSkill("Firm Stance")] Skill858,
        [Unused] Skill859,
        [AutoSkill("Life Aid")] Skill860,
        [AutoSkill("Victory Cry")] Skill861,
        [AutoSkill("Growth 1")] Skill862,
        [AutoSkill("Growth 2")] Skill863,
        [AutoSkill("Growth 3")] Skill864,
        [AutoSkill("Unshaken Will")] Skill865,
        [AutoSkill("BLANK")] Skill866,
        [AutoSkill("Baton Pass")] Skill867,
        [AutoSkill("Soul Touch")] Skill868,
        [AutoSkill("Kakoi Kuzushi")] Skill869,
        [AutoSkill("Resist Fire")] Skill870,
        [AutoSkill("Null Fire")] Skill871,
        [AutoSkill("Repel Fire")] Skill872,
        [AutoSkill("Drain Fire")] Skill873,
        [Unused] Skill874,
        [AutoSkill("Resist Ice")] Skill875,
        [AutoSkill("Null Ice")] Skill876,
        [AutoSkill("Repel Ice")] Skill877,
        [AutoSkill("Drain Ice")] Skill878,
        [Unused] Skill879,
        [AutoSkill("Resist Wind")] Skill880,
        [AutoSkill("Null Wind")] Skill881,
        [AutoSkill("Repel Wind")] Skill882,
        [AutoSkill("Drain Wind")] Skill883,
        [Unused] Skill884,
        [AutoSkill("Resist Elec")] Skill885,
        [AutoSkill("Null Elec")] Skill886,
        [AutoSkill("Repel Elec")] Skill887,
        [AutoSkill("Drain Elec")] Skill888,
        [Unused] Skill889,
        [AutoSkill("Resist Bless")] Skill890,
        [AutoSkill("Null Bless")] Skill891,
        [AutoSkill("Repel Bless")] Skill892,
        [AutoSkill("Drain Bless")] Skill893,
        [Unused] Skill894,
        [AutoSkill("Resist Curse")] Skill895,
        [AutoSkill("Null Curse")] Skill896,
        [AutoSkill("Repel Curse")] Skill897,
        [AutoSkill("Drain Curse")] Skill898,
        [Unused] Skill899,
        [AutoSkill("Resist Phys")] Skill900,
        [AutoSkill("Null Phys")] Skill901,
        [AutoSkill("Repel Phys")] Skill902,
        [AutoSkill("Drain Phys")] Skill903,
        [Unused] Skill904,
        [AutoSkill("Ailment Boost")] Skill905,
        [AutoSkill("Hama Boost")] Skill906,
        [AutoSkill("Mudo Boost")] Skill907,
        [Unused] Skill908,
        [Unused] Skill909,
        [AutoSkill("Dizzy Boost")] Skill910,
        [AutoSkill("Confuse Boost")] Skill911,
        [AutoSkill("Fear Boost")] Skill912,
        [AutoSkill("Forget Boost")] Skill913,
        [AutoSkill("Sleep Boost")] Skill914,
        [AutoSkill("Rage Boost")] Skill915,
        [AutoSkill("Despair Boost")] Skill916,
        [AutoSkill("BLANK")] Skill917,
        [AutoSkill("Brainwash Boost")] Skill918,
        [Unused] Skill919,
        [AutoSkill("Resist Dizzy")] Skill920,
        [AutoSkill("Resist Confuse")] Skill921,
        [AutoSkill("Resist Fear")] Skill922,
        [AutoSkill("Resist Forget")] Skill923,
        [AutoSkill("Resist Sleep")] Skill924,
        [AutoSkill("Resist Rage")] Skill925,
        [AutoSkill("Resist Despair")] Skill926,
        [AutoSkill("BLANK")] Skill927,
        [AutoSkill("Resist Brainwash")] Skill928,
        [Unused] Skill929,
        [AutoSkill("Null Dizzy")] Skill930,
        [AutoSkill("Null Confuse")] Skill931,
        [AutoSkill("Null Fear")] Skill932,
        [AutoSkill("Null Forget")] Skill933,
        [AutoSkill("Null Sleep")] Skill934,
        [AutoSkill("Null Rage")] Skill935,
        [AutoSkill("Null Despair")] Skill936,
        [AutoSkill("BLANK")] Skill937,
        [AutoSkill("Null Brainwash")] Skill938,
        [Unused] Skill939,
        [AutoSkill("Burn Boost")] Skill940,
        [AutoSkill("Freeze Boost")] Skill941,
        [AutoSkill("Shock Boost")] Skill942,
        [AutoSkill("BLANK")] Skill943,
        [AutoSkill("Fortified Moxy")] Skill944,
        [AutoSkill("Adverse Resolve")] Skill945,
        [AutoSkill("Last Stand")] Skill946,
        [AutoSkill("Heat Up")] Skill947,
        [Unused] Skill948,
        [AutoSkill("Touch n' Go")] Skill949,
        [AutoSkill("Climate Decorum")] Skill950,
        [AutoSkill("Ambient Aid")] Skill951,
        [AutoSkill("RESERVE")] Skill952,
        [AutoSkill("Snipe")] Skill953,
        [AutoSkill("Cripple")] Skill954,
        [AutoSkill("Trigger Happy")] Skill955,
        [AutoSkill("Resist Nuke")] Skill956,
        [AutoSkill("Null Nuke")] Skill957,
        [AutoSkill("Repel Nuke")] Skill958,
        [AutoSkill("Drain Nuke")] Skill959,
        [AutoSkill("RESERVE")] Skill960,
        [AutoSkill("Resist Psy")] Skill961,
        [AutoSkill("Null Psy")] Skill962,
        [AutoSkill("Repel Psy")] Skill963,
        [AutoSkill("Drain Psy")] Skill964,
        [AutoSkill("RESERVE")] Skill965,
        [AutoSkill("Nuke Boost")] Skill966,
        [AutoSkill("Nuke Amp")] Skill967,
        [AutoSkill("RESERVE")] Skill968,
        [AutoSkill("Psy Boost")] Skill969,
        [AutoSkill("Psy Amp")] Skill970,
        [AutoSkill("RESERVE")] Skill971,
        [AutoSkill("Dodge Nuke")] Skill972,
        [AutoSkill("Evade Nuke")] Skill973,
        [AutoSkill("RESERVE")] Skill974,
        [AutoSkill("Dodge Psy")] Skill975,
        [AutoSkill("Evade Psy")] Skill976,
        [AutoSkill("RESERVE")] Skill977,
        [AutoSkill("Bless Boost")] Skill978,
        [AutoSkill("Bless Amp")] Skill979,
        [AutoSkill("RESERVE")] Skill980,
        [AutoSkill("Curse Boost")] Skill981,
        [AutoSkill("Curse Amp")] Skill982,
        [AutoSkill("RESERVE")] Skill983,
        [AutoSkill("Magic Ability")] Skill984,
        [AutoSkill("Fortify Spirit")] Skill985,
        [AutoSkill("Almighty Boost")] Skill986,
        [AutoSkill("Almighty Amp")] Skill987,
        [AutoSkill("Zenith Defense")] Skill988,
        [AutoSkill("Soul Chain")] Skill989,
        [AutoSkill("Vanity Copy")] Skill990,
        [AutoSkill("Gluttonous Snuff")] Skill991,
        [AutoSkill("Sloth Defense")] Skill992,
        [Unused] Skill993,
        [Unused] Skill994,
        [Unused] Skill995,
        [Unused] Skill996,
        [Unused] Skill997,
        [Unused] Skill998,
        [Unused] Skill999,
    }
}
