using KHSave.Attributes;

namespace KHSave.LibPersona5.Types
{
    public class SkillAttribute : InfoAttribute
    {
        public SkillAttribute(string name = null) : base(name) { }
    }
    public class HitSkillAttribute : SkillAttribute
    {
        public HitSkillAttribute(string name = null) : base(name) { }
    }
    public class GunSkillAttribute : SkillAttribute
    {
        public GunSkillAttribute(string name = null) : base(name) { }
    }
    public class FireSkillAttribute : SkillAttribute
    {
        public FireSkillAttribute(string name = null) : base(name) { }
    }
    public class IceSkillAttribute : SkillAttribute
    {
        public IceSkillAttribute(string name = null) : base(name) { }
    }
    public class WindSkillAttribute : SkillAttribute
    {
        public WindSkillAttribute(string name = null) : base(name) { }
    }
    public class ThunderSkillAttribute : SkillAttribute
    {
        public ThunderSkillAttribute(string name = null) : base(name) { }
    }
    public class BlessSkillAttribute : SkillAttribute
    {
        public BlessSkillAttribute(string name = null) : base(name) { }
    }
    public class DeathSkillAttribute : SkillAttribute
    {
        public DeathSkillAttribute(string name = null) : base(name) { }
    }
    public class AlmightySkillAttribute : SkillAttribute
    {
        public AlmightySkillAttribute(string name = null) : base(name) { }
    }
    public class NuclearSkillAttribute : SkillAttribute
    {
        public NuclearSkillAttribute(string name = null) : base(name) { }
    }
    public class PsychoSkillAttribute : SkillAttribute
    {
        public PsychoSkillAttribute(string name = null) : base(name) { }
    }
    public class SupportSkillAttribute : SkillAttribute
    {
        public SupportSkillAttribute(string name = null) : base(name) { }
    }
    public class AutoSkillAttribute : SkillAttribute
    {
        public AutoSkillAttribute(string name = null) : base(name) { }
    }
    public class PoisonSkillAttribute : SkillAttribute
    {
        public PoisonSkillAttribute(string name = null) : base(name) { }
    }
    public class HealSkillAttribute : SkillAttribute
    {
        public HealSkillAttribute(string name = null) : base(name) { }
    }

    public enum Skill : short
    {
        [Skill] None,

        [FireSkill] Agi = 10,
        [FireSkill] Agilao,
        [FireSkill] Agidyne,
        [FireSkill] Maragi,
        [FireSkill] Maragion,
        [FireSkill] Maragidyne,

        [IceSkill] Bufu = 20,
        [IceSkill] Bufula,
        [IceSkill] Bufudyne,
        [IceSkill] Mabufu,
        [IceSkill] Mabufula,
        [IceSkill] Mabufudyne,

        [WindSkill] Garu = 30,
        [WindSkill] Garula,
        [WindSkill] Garudyne,
        [WindSkill] Magaru,
        [WindSkill] Magarula,
        [WindSkill] Magarudyne,

        [ThunderSkill] Zio = 40,
        [ThunderSkill] Ziola,
        [ThunderSkill] Ziodyne,
        [ThunderSkill] Mazio,
        [ThunderSkill] Maziola,
        [ThunderSkill] Maziodyne,

        [BlessSkill] Hama = 50,
        [BlessSkill] Hamaom,
        [BlessSkill] Mahama,
        [BlessSkill] Mahamaon,
        [BlessSkill] Kouha,
        [BlessSkill] Kouga,
        [BlessSkill] Kougaon,
        [BlessSkill] Makouha,
        [BlessSkill] Makouga,
        [BlessSkill] Makougaon,

        [DeathSkill] Mudo,
        [DeathSkill] Mudoon,
        [DeathSkill] Mamudo,
        [DeathSkill] Mamudoon,
        [DeathSkill] Eiha,
        [DeathSkill] Eiga,
        [DeathSkill] Eigaon,
        [DeathSkill] Maeiha,
        [DeathSkill] Maeiga,
        [DeathSkill] Maeigaon,

        [AlmightySkill] Megido,
        [AlmightySkill] Megidola,
        [AlmightySkill] Megidolaon,
        [NuclearSkill] Frei,
        [NuclearSkill] Freila,
        [NuclearSkill] Freidyne,
        [NuclearSkill] Mafrei,
        [NuclearSkill] Mafreila,
        [NuclearSkill] Mafreidyne,

        [PoisonSkill] Dazzler = 80,
        [PoisonSkill("Nocturnal Flash")] NocturnalFlash,
        [PoisonSkill] Pulinpa,
        [PoisonSkill] Tentarafoo,
        [PoisonSkill("Evil Touch")] EvilTouch,
        [PoisonSkill("Evil Smile")] EvilSmile,
        [PoisonSkill] Makajama,
        [PoisonSkill] Makajamaon,
        [PoisonSkill("Famine's Breath")] FamineBreath,
        [PoisonSkill("Famine's Scream")] FamineScream,
        [PoisonSkill] Dormina,
        [PoisonSkill] Lullaby,
        [PoisonSkill] Taunt,
        [PoisonSkill("Wage War")] WageWar,
        [PoisonSkill("Ominous Words")] OminousWords,
        [PoisonSkill("Abysmal Surge")] AbysmalSurge,
        [PoisonSkill("Marin Karin")] MarinKarin,
        [PoisonSkill("Brain Jack")] BrainJack,
        [AlmightySkill("Trapped Rat")] TrappedRat,

        [AlmightySkill("Self-Destruct")] SefDestruct1 = 100,
        [AlmightySkill("Self-Destruct")] SefDestruct2,
        [AlmightySkill("Self-Destruct")] SefDestruct3,
        [AlmightySkill("Life Drain")] LifeDrain,
        [AlmightySkill("Spirit Drain")] SpiritDrain,
        [AlmightySkill("Life Leech")] LifeLeech,
        [AlmightySkill("Spirit Leech")] SpiritLeech,
        [AlmightySkill("Spirit Drain")] SpiritDrain2,

        [AlmightySkill("Foul Breath")] FoulBreath = 110,
        [AlmightySkill("Stagnant Air")] StagnantAir,
        [AlmightySkill("Reverse Rub")] ReverseRub,
        [AlmightySkill("Ghastly Wail")] GhastlyWail,

        [FireSkill] Inferno = 120,
        [FireSkill("Blazing Hell")] BlazingHell,
        [AutoSkill("Low Burn")] LowBurn,
        [AutoSkill("Mid Burn")] MidBurn,
        [AutoSkill("High Burn")] HighBurn,
        [AutoSkill("Low Freeze")] LowFreeze,
        [AutoSkill("Mid Freeze")] MidFreeze,
        [AutoSkill("High Freeze")] HighFreeze,
        [AutoSkill("Low Shock")] LowShock,
        [AutoSkill("Mid Shock")] MidShock,
        [IceSkill("Diamond Dust")] DiamondDust,
        [IceSkill("Ice Age")] IceAge,
        [AutoSkill("High Shock")] HighShock,
        [AutoSkill("Low Dizzy")] LowDizzy,
        [AutoSkill("Mid Dizzy")] MidDizzy,
        [AutoSkill("High Dizzy")] HighDizzy,
        [AutoSkill("Low Confuse")] LowConfuse,
        [AutoSkill("Mid Confuse")] MidConfuse,
        [AutoSkill("High Confuse")] HighConfuse,
        [AutoSkill("Low Fear")] LowFear,
        [WindSkill("Panta Rhei")] PantaRhei,
        [WindSkill("Vacuum Wave")] VacuumWave,
        [AutoSkill("Mid Fear")] MidFear,
        [AutoSkill("High Fear")] HighFear,
        [AutoSkill("Low Forget")] LowForget,
        [AutoSkill("Mid Forget")] MidForget,
        [AutoSkill("High Forget")] HighForget,
        [AutoSkill("Low Brainwash")] LowBrainwash,
        [AutoSkill("Mid Brainwash")] MidBrainwash,
        [AutoSkill("High Brainwash")] HighBrainwash,
        [ThunderSkill("Thunder Reign")] ThunderReign,
        [ThunderSkill("Wild Thunder")] WildThunder,
        [AutoSkill("Low Sleep")] LowSleep,
        [AutoSkill("Mid Sleep")] MidSleep,
        [AutoSkill("High Sleep")] HighSleep,
        [AutoSkill("Low Rage")] LowRage,
        [AutoSkill("Mid Rage")] MidRage,
        [AutoSkill("High Rage")] HighRage,
        [AutoSkill("Low Despair")] LowDespair,
        [AutoSkill("Mid Despair")] MidDespair,
        [BlessSkill("Divine Judgment")] DivineJudgment,
        [BlessSkill] Samsara,
        [AutoSkill("High Despair")] HighDespair,
        [AutoSkill("Low All Ail")] LowAllAil,
        [AutoSkill("Mid All Ail")] MidAllAil,
        [AutoSkill("High All Ail")] HighAllAil,
        [DeathSkill("Demonic Decree")] DemonicDecree = 170,
        [DeathSkill("Die For Me!")] DieForMe,

        [NuclearSkill("Atomic Flare")] AtomicFlare = 176,
        [NuclearSkill("Cosmic Flare")] CosmicFlare,

        [AlmightySkill("Black Viper")] BlackViper = 180,
        [AlmightySkill("Morning Star")] MorningStar,

        [PsychoSkill] Psi = 190,
        [PsychoSkill] Psio,
        [PsychoSkill] Psiodyne,
        [PsychoSkill] Mapsi,
        [PsychoSkill] Mapsio,
        [PsychoSkill] Mapsiodyne,
        [PsychoSkill("Psycho Force")] PsychoForce = 197,
        [PsychoSkill("Psycho Blast")] PsychoBlast,

        [HitSkill] Lunge = 200,
        [HitSkill("Assault Dive")] AssaultDive,
        [HitSkill("Megaton Raid")] MegatonRaid,
        [HitSkill("God's Hand")] GodHand,
        [HitSkill("Lunge")] Lunge2,
        [HitSkill("Lucky Punch")] LuckyPunch,
        [HitSkill("Miracle Punch")] MiraclePunch,

        [HitSkill("Cleave")] Cleave = 210,
        [HitSkill("Giant Slice")] GiantSlice,
        [HitSkill("Brave Blade")] BraveBlade,
        [HitSkill("Sword Dance")] SwordDance,
        [HitSkill("Hassou Tobi")] HassouTobi = 215,
        [HitSkill] Ayamur,
        [HitSkill("Cornered Fang")] CorneredFang = 220,
        [HitSkill("Rising Slash")] RisingSlash,
        [HitSkill("Deadly Fury")] DeadlyFury,

        [GunSkill] Snap = 224,
        [GunSkill("Triple Down")] TripleDown,
        [GunSkill("One-shot Kill")] OneShotKill,
        [GunSkill("Riot Gun")] RiotGun,

        [HitSkill("Vajra Blast")] VajraBlast = 230,
        [HitSkill("Vorpal Blade")] VorpalBlade,

        [HitSkill("ViciousStrike")] ViciousStrike = 235,
        [HitSkill("Heat Wave")] HeatWave,
        [HitSkill] Gigantomachia,

        [HitSkill] Rampage = 241,
        [HitSkill("Swift Strike")] SwiftStrike,
        [HitSkill] Deathbound,
        [HitSkill] Agneyastra,
        [HitSkill("Rising Slash (2)")] RisingSlash2 = 247,
        [HitSkill("Deadly Fury (2)")] DeadlyFury2,
        [HitSkill("Double Fangs")] DoubleFangs = 250,
        [HitSkill("Tempest Slash")] TempestSlash = 253,
        [HitSkill("Myriad Slashes")] MyriadSlashes,

        [HitSkill] Sledgehammer = 260,
        [HitSkill("Skull Cracker")] SkullCracker,
        [HitSkill("Terror Claw")] TerrorClaw,
        [HitSkill("Headbutt")] Headbutt,
        [HitSkill("Stomach Blow")] StomachBlow,
        [HitSkill("Dream Needle")] DreamNeedle,
        [HitSkill("Hysterical Slap")] HystericalSlap,
        [HitSkill("Negative Pile")] NegativePile,
        [HitSkill("Brain Shake")] BrainShake,

        [HitSkill("Flash Bomb")] FlashBomb = 270,
        [HitSkill("Mind Slice")] MindSlice,
        [HitSkill("Bloodybath")] Bloodybath,
        [HitSkill("Memory Blow")] MemoryBlow,
        [HitSkill("Insatiable Strike")] InsatiableStrike,
        [HitSkill("Dormin Rush")] DorminRush,
        [HitSkill("Oni-Kagura")] OniKagura,
        [HitSkill("Bad Beat")] BadBeat,
        [HitSkill("Brain Buster")] BrainBuster,
        [GunSkill] Handgun = 280,
        [GunSkill] Shotgun,
        [GunSkill] Slingshot,
        [GunSkill("Machine Gun")] MachineGun,
        [GunSkill("Assault Rifle")] AssaultRifle,
        [GunSkill] Revolver,
        [GunSkill("Grenade Launcher")] GrenadeLauncher,
        [GunSkill("Laser Gun")] LaserGun,

        [Skill] AttackSupport = 299,
        [HealSkill] Dia,
        [HealSkill] Diarama,
        [HealSkill] Diarahan,
        [HealSkill] Media = 305,
        [HealSkill] Mediarama,
        [HealSkill] Mediarahan,
        [HealSkill] Recarm = 310,
        [HealSkill] Samarecarm,
        [HealSkill] Recarmdra,
        [HealSkill("Amrita Drop")] AmritaDrop = 315,
        [HealSkill("Amrita Shower")] AmritaShower,
        [HealSkill("BLANK")] Blank317,
        [HealSkill("Salvation")] Salvation,
        [HealSkill("Patra")] Patra = 325,
        [HealSkill("BLANK")] Blank326,
        [HealSkill("Energy Shower")] EnergyShower,
        [HealSkill("Energy Drop")] EnergyDrop,
        [HealSkill("Baisudi")] Baisudi,
        [HealSkill("Me Patra")] MePatra,
        [HealSkill("Mabaisudi")] Mabaisudi,

        [SupportSkill] Tarukaja = 335,
        [SupportSkill] Rakukaja,
        [SupportSkill] Sukukaja,
        [SupportSkill("Heat Riser")] HeatRiser,
        [SupportSkill] Matarukaja = 340,
        [SupportSkill] Marakukaja,
        [SupportSkill] Masukukaja,
        [SupportSkill] Thermopylae,
        [SupportSkill] Tarunda = 345,
        [SupportSkill] Rakunda,
        [SupportSkill] Sukunda,
        [SupportSkill] Debilitate,
        [SupportSkill] Matarunda = 350,
        [SupportSkill] Marukunda,
        [SupportSkill] Masukunda,
        [SupportSkill] Dekunda = 355,
        [SupportSkill] Dekaja,
        [SupportSkill] Charge = 360,
        [SupportSkill] Concentrate,
        [SupportSkill] Rebellion = 365,
        [SupportSkill] Revolution,
        [SupportSkill] Tetrakarn = 370,
        [SupportSkill] Makarakarn,
        [SupportSkill] Tetraja,
        [SupportSkill("Tetra Break")] TetraBreak = 375,
        [SupportSkill("Makara Break")] MakaraBreak,
        [SupportSkill("Fire Wall")] FireWall = 380,
        [SupportSkill("Ice Wall")] IceWall,
        [SupportSkill("Elec Wall")] ElecWall,
        [SupportSkill("Wind Wall")] WindWall,

        [SupportSkill("Fire Break")] FireBreak = 385,
        [SupportSkill("Ice Break")] IceBreak,
        [SupportSkill("Wind Break")] WindBreak,
        [SupportSkill("Elec Break")] ElecBreak,
        [SupportSkill] Trafuri = 390,
        [SupportSkill] Traesto,
        [SupportSkill("Nuke Wall")] NukeWall = 393,
        [SupportSkill("Psy Wall")] PsyWall,
        [SupportSkill("Nuke Break")] NukeBreak,
        [SupportSkill("Psy Break")] PsyBreak,
        [AlmightySkill("All-out Lv 1")] AllOutLv1 = 400,
        [AlmightySkill("All-out Lv 2")] AllOutLv2,
        [AlmightySkill("All-out Lv 3")] AllOutLv3,
        [SupportMateria("Emergency Escape")] EmergencyEscape,
        [HitSkill] Attack,
        [AlmightySkill("Down Shot")] DownShot,
        [SupportMateria] Support,
        [SupportMateria("Call for Backup")] CallForBackup,
        [SupportMateria("Outlaw Attack")] OutlawAttack,
        [SupportMateria("Barrage")] Barrage,
        [AlmightySkill("Follow Crush")] FollowCrush,
        [AlmightySkill("Follow Claw")] FollowClaw,
        [AlmightySkill("Follow Whip")] FollowWhip,
        [AlmightySkill("Follow Blade")] FollowBlade,
        [AlmightySkill("Follow Knuckle")] FollowKnuckle,
        [AlmightySkill("Follow Axe")] FollowAxe,
        [AlmightySkill("Follow Saber")] FollowSaber,
        [SupportSkill("Dispose Item")] DisposeItem,
        [SupportSkill("Heal Enemy")] HealEnemy,
        [AlmightySkill("Death (Despair)")] DeathDespair,
        [AlmightySkill("Ally1 Follow-Up")] Ally1FollowUp,
        [AlmightySkill("Ally2 Follow-Up")] Ally2FollowUp,
        [AlmightySkill("Ally3 Follow-Up")] Ally3FollowUp,
        [AlmightySkill("Ally4 Follow-Up")] Ally4FollowUp,
        [AlmightySkill("Ally5 Follow-Up")] Ally5FollowUp,
        [AlmightySkill("Ally6 Follow-Up")] Ally6FollowUp,
        [AlmightySkill("Ally7 Follow-Up")] Ally7FollowUp,
        [SupportSkill("Power Up Enemy")] PowerUpEnemy,
        [SupportSkill("Power Up Enemy (2)")] PowerUpEnemy2,
        [SupportSkill("Power Up Enemy (3)")] PowerUpEnemy3,
        [SupportSkill("Steal Info")] StealInfo,
        [AutoSkill("Sup Matarukaja")] SupMatarukaja,
        [AutoSkill("Sup Marakukaja")] SupMarakukaja,
        [AutoSkill("Sup Masukukaja")] SupMasukukaja,
        [AutoSkill("Sup All Kaja")] SupAllKaja,
        [AutoSkill("Sup Charge")] SupCharge,
        [AutoSkill("Sup HP +30%")] SupHp30,
        [AutoSkill("Sup SP +10%")] SupSp10,
        [AutoSkill("Sup Escape Route")] SupEscapeRoute,
        [AutoSkill("Sup Third Eye")] SupThirdEye,
        [AutoSkill("Subrecover HP")] SubrecoverHP,
        [AutoSkill("Subrecover SP")] SubrecoverSP,
        [AutoSkill("Analysis")] Analysis,
        [AutoSkill("Deep Analysis")] DeepAnalysis,
        [AutoSkill("Full Analysis")] FullAnalysis,
        [AlmightySkill("All-Out Attack")] AllOutAttack,
        [WindSkill("Dust Flurry")] DustFlurry,
        [HitSkill("Tongue Whip")] TongueWhip,
        [HitSkill("Whip Strike")] WhipStrike,
        [SupportSkill("Lustful Slurp")] LustfulSlurp,
        [HealSkill("Libido Boost")] LibidoBoost,
        [HitSkill("Golden Knife")] GoldenKnife,
        [HitSkill("Lick")] Lick,
        [AlmightySkill("Gold Medal Spike")] GoldMedalSpike,
        [HitSkill("Volleyball Assault")] VolleyballAssault,
        [WindSkill("Maelstrom")] Maelstrom,
        [FireSkill("Flame Dance")] FlameDance,
        [IceSkill("Silent Snowscape")] SilentSnowscape,
        [ThunderSkill("Thunderclap")] Thunderclap,
        [DeathSkill("Maeiga (2)")] Maeiga2,
        [PoisonSkill("Hunger All")] HungerAll,
        [GunSkill("Ocular Vulcan")] OcularVulcan,
        [FireSkill("Missile Party")] MissileParty,
        [PoisonSkill("Fear Gas")] FearGas,
        [SupportSkill("Super VIP Form")] SuperVipForm,
        [AlmightySkill("March of the Piggy")] MarchPiggy,
        [HitSkill("Sphinx Swipe")] SphinxSwipe,
        [WindSkill("Wing Blast")] WingBlast,
        [SupportSkill("Rapid Ascent")] RapidAscent,
        [HitSkill("Sphinx Dive")] SphinxDive,
        [AlmightySkill("Dreadful Scream")] DreadfulScream,
        [HitSkill("Bite")] Bite,
        [SupportSkill("Restore")] Restore,
        [AlmightySkill("The Artist's Grace")] TheArtistGrace,
        [SupportSkill("Work Order")] WorkOrder,
        [SupportSkill("Sacrifice Order")] SacrificeOrder,
        [AlmightySkill("Selfless Devotion")] SelflessDevotion,
        [AlmightySkill("Penalty")] Penalty,
        [HitSkill("Coin Attack")] CoinAttack,
        [HitSkill("Severing Slash")] SeveringSlash,
        [GunSkill("Gatilg Gun")] GatilgGun, // 480... sono stanco.

        // MISSING: [481..799]

        [HitSkill("Cross Slash")] CrossSlash = 705,

        [AutoSkill("Counter")] Counter = 800,
        [AutoSkill("Counterstrike")] Counterstrike,
        [AutoSkill("High Counter")] HighCounter,

        [AutoSkill("Endure")] Endure = 805,
        [AutoSkill("Enduring Soul")] EnduringSoul = 806,
        [AutoSkill("Survival Trick")] SurvivalTrick = 809,
        [AutoSkill("Dodge Fire")] DodgeFire,
        [AutoSkill("Evade Fire")] EvadeFire,
        [AutoSkill("Dodge Ice")] DodgeIce,
        [AutoSkill("Evade Ice")] EvadeIce,
        [AutoSkill("Dodge Wind")] DodgeWind,
        [AutoSkill("Evade Wind")] EvadeWind,
        [AutoSkill("Dodge Elec")] DodgeElec,
        [AutoSkill("Evade Elec")] EvadeElec,
        [AutoSkill("Dodge Phys")] DodgePhys,
        [AutoSkill("Evade Phys")] EvadePhys,
        [AutoSkill("Fire Boost")] FireBoost,
        [AutoSkill("Fire Amp")] FireAmp,
        [AutoSkill("Ice Boost")] IceBoost,
        [AutoSkill("Ice Amp")] IceAmp,
        [AutoSkill("Wind Boost")] WindBoost,
        [AutoSkill("Wind Amp")] WindAmp,
        [AutoSkill("Elec Boost")] ElecBoost,
        [AutoSkill("Elec Amp")] ElecAmp,
        [AutoSkill("Angelic Grace")] AngelicGrace,
        [AutoSkill("Divine Grace")] DivineGrace,
        [AutoSkill("Regenerate 1")] Regenerate1,
        [AutoSkill("Regenerate 2")] Regenerate2,
        [AutoSkill("Regenerate 3")] Regenerate3,
        [AutoSkill("Dodge Bless")] DodgeBless,
        [AutoSkill("Dodge Curse")] DodgeCurse,
        [AutoSkill("Invigorate 1")] Invigorate1,
        [AutoSkill("Invigorate 2")] Invigorate2,
        [AutoSkill("Invigorate 3")] Invigorate3,
        [AutoSkill("Evade Bless")] EvadeBless,
        [AutoSkill("Evade Curse")] EvadeCurse,
        [AutoSkill("Attack Master")] AttackMaster,
        [AutoSkill("Auto-Mataru")] AutoMataru,
        [AutoSkill("Defense Master")] DefenseMaster = 843,
        [AutoSkill("Auto-Maraku")] AutoMaraku,
        [AutoSkill("Speed Master")] SpeedMaster = 846,
        [AutoSkill("Auto-Masuku")] AutoMasuku,
        [AutoSkill("Fast Heal")] FastHeal = 850,
        [AutoSkill("Insta-Heal")] InstaHeal,
        [AutoSkill("Arms Master")] ArmsMaster,
        [AutoSkill("Spell Master")] SpellMaster,
        [AutoSkill("Sharp Student")] SharpStudent = 855,
        [AutoSkill("Apt Pupil")] AptPupil,
        [AutoSkill("Ali Dance")] AliDance,
        [AutoSkill("Firm Stance")] FirmStance,
        [AutoSkill("Life Aid")] LifeAid = 860,
        [AutoSkill("Victor Cry")] VictorCry,
        [AutoSkill("Growth 1")] Growth1,
        [AutoSkill("Growth 2")] Growth2,
        [AutoSkill("Growth 3")] Growth3,
        [AutoSkill("Unshaken Will")] UnshakenWill,
        [AutoSkill("Baton Pass")] BatonPass = 867,
        [AutoSkill("Soul Touch")] SoulTouch,
        [AutoSkill("Kakoi Kuzushi")] KakoiKuzushi,
        [AutoSkill("Resist Fire")] ResistFire,
        [AutoSkill("Null Fire")] NullFire,
        [AutoSkill("Repel Fire")] RepelFire,
        [AutoSkill("Drain Fire")] DrainFire,
        [AutoSkill("Resist Ice")] ResistIce = 875,
        [AutoSkill("Null Ice")] NullIce,
        [AutoSkill("Repel Ice")] RepelIce,
        [AutoSkill("Drain Ice")] DrainIce,
        [AutoSkill("Resist Wind")] ResistWind = 880,
        [AutoSkill("Null Wind")] NullWind,
        [AutoSkill("Repel Wind")] RepelWind,
        [AutoSkill("Drain Wind")] DrainWind,
        [AutoSkill("Resist Elec")] ResistElec = 885,
        [AutoSkill("Null Elec")] NullElec,
        [AutoSkill("Repel Elec")] RepelElec,
        [AutoSkill("Drain Elec")] DrainElec,
        [AutoSkill("Resist Bless")] ResistBless = 890,
        [AutoSkill("Null Bless")] NullBless,
        [AutoSkill("Repel Bless")] RepelBless,
        [AutoSkill("Drain Bless")] DrainBless,
        [AutoSkill("Resist Curse")] ResistCurse = 895,
        [AutoSkill("Null Curse")] NullCurse,
        [AutoSkill("Repel Curse")] RepelCurse,
        [AutoSkill("Drain Curse")] DrainCurse,
        [AutoSkill("Resist Phys")] ResistPhys = 900,
        [AutoSkill("Null Phys")] NullPhys,
        [AutoSkill("Repel Phys")] RepelPhys,
        [AutoSkill("Drain Phys")] DrainPhys,
        [AutoSkill("Aliment Boost")] AlimentBoost = 905,
        [AutoSkill("Hama Boost")] HamaBoost,
        [AutoSkill("Mudo Boost")] MudoBoost,
        [AutoSkill("Dizzy Boost")] DizzyBoost = 910,
        [AutoSkill("Confuse Boost")] ConfuseBoost,
        [AutoSkill("Fear Boost")] FearBoost,
        [AutoSkill("Forget Boost")] ForgetBoost,
        [AutoSkill("Sleep Boost")] SleepBoost,
        [AutoSkill("Rage Boost")] RageBoost,
        [AutoSkill("Despair Boost")] DespairBoost,
        [AutoSkill("Brainwash Boost")] BrainwashBoost = 918,
        [AutoSkill("Resist Dizzy")] DizzyResist = 920,
        [AutoSkill("Resist Confuse")] ConfuseResist,
        [AutoSkill("Resist Fear")] FearResist,
        [AutoSkill("Resist Forget")] ForgetResist,
        [AutoSkill("Resist Sleep")] SleepResist,
        [AutoSkill("Resist Rage")] RageResist,
        [AutoSkill("Resist Despair")] DespairResist,
        [AutoSkill("Resist Brainwash")] BrainwashResist = 928,
        [AutoSkill("Null Dizzy")] DizzyNull = 930,
        [AutoSkill("Null Confuse")] ConfuseNull,
        [AutoSkill("Null Fear")] FearNull,
        [AutoSkill("Null Forget")] ForgetNull,
        [AutoSkill("Null Sleep")] SleepNull,
        [AutoSkill("Null Rage")] RageNull,
        [AutoSkill("Null Despair")] DespairNull,
        [AutoSkill("Null Brainwash")] BrainwashNull = 938,
        [AutoSkill("Burn Boost")] BurnBoost = 940,
        [AutoSkill("Freeze Boost")] FreezeBoost,
        [AutoSkill("Shock Boost")] ShockBoost,
        [AutoSkill("Fortified Moxy")] FortifiedMoxy = 944,
        [AutoSkill("Adverse Resolve")] AdverseResolve,
        [AutoSkill("Last Stand")] LastStand,
        [AutoSkill("Heat Up")] HeatUp,
        [AutoSkill("Touch n' Go")] TouchnGo = 949,
        [AutoSkill("Climate Decorum")] ClimateDecorum,
        [AutoSkill("Ambient Aid")] AmbientAid,
        [AutoSkill("Snipe")] Snipe = 953,
        [AutoSkill("Cripple")] Cripple,
        [AutoSkill("Trigger Happy")] TriggerHappy,
        [AutoSkill("Resist Nuke")] ResistNuke,
        [AutoSkill("Null Nuke")] NullNuke,
        [AutoSkill("Repel Nuke")] RepelNuke,
        [AutoSkill("Drain Nuke")] DrainNuke,
        [AutoSkill("Resist Psy")] ResistPsy = 961,
        [AutoSkill("Null Psy")] NullPsy,
        [AutoSkill("Repel Psy")] RepelPsy,
        [AutoSkill("Drain Psy")] DrainPsy,
        [AutoSkill("Nuke Boost")] NukeBoost = 966,
        [AutoSkill("Nuke Amp")] NukeAmp,
        [AutoSkill("Psy Boost")] PsyBoost = 969,
        [AutoSkill("Psy Amp")] PsyAmp,
        [AutoSkill("Dodge Nuke")] DodgeNuke = 972,
        [AutoSkill("Evade Nuke")] EvadeNuke,
        [AutoSkill("Dodge Psy")] DodgePsy = 975,
        [AutoSkill("Evade Psy")] EvadePsy,
        [AutoSkill("Bless Boost")] BlessBoost = 978,
        [AutoSkill("Bless Amp")] BlessAmp,
        [AutoSkill("Curse Boost")] CurseBoost = 981,
        [AutoSkill("Curse Amp")] CurseAmp,

        [AutoSkill("Magic Ability")] MagicAbility = 984,
        [AutoSkill("Fortify Spirit")] FortifySpirit,
        [AutoSkill("Almighty Boost")] AlmightyBoost,
        [AutoSkill("Almighty Amp")] AlmightyAmp,
        [AutoSkill("Zenith Defense")] ZenithDefense,
        [AutoSkill("Soul Chain")] SoulChain,
        [AutoSkill("Vanity Copy")] VanityCopy,
        [AutoSkill("Gluttonous Snuff")] GluttonousSnuff,
        [AutoSkill("Sloth Defense")] SlothDefense,
    }
}
