using KHSave.Attributes;

namespace KHSave.LibDDD.Types
{
    public enum DreamEaterType : byte
    {
        [Info("Not Used")] NotUsed,
        [Info("Meow Wow")] MeomWow,
        [Info("Tama Sheep")] TamaSheep,
        [Info("Yoggy Ram")] YoggyRam,
        [Info("Komory Bat")] KomoryBat,
        [Info("Pricklemane")] Pricklemane,
        [Info("Hebby Repp")] HebbyRepp,
        [Info("Sir Kyroo")] SirKyroo,
        [Info("Toximander")] Toximander,
        [Info("Fin Fatale")] FinFatale,
        [Info("Tatsu Steed")] TatsuSteed,
        [Info("Necho Cat")] NechoCat,
        [Info("Thunderaffe")] Thunderaffe,
        [Info("Kooma Panda")] KoomaPanda,
        [Info("Pegaslick")] Pegaslick,
        [Info("Iceguin Ace")] IceguinAce,
        [Info("Peepsta Hoo")] PeepstaHoo,
        [Info("Escarglow")] Escarglow,
        [Info("KO Kabuto")] KOKabuto,
        [Info("Wheeflower")] Wheeflower,
        [Info("Ghostabocky")] Ghostabocky,
        [Info("Zolephant")] Zolephant,
        [Info("Juggle Pup")] JugglePup,
        [Info("Halbird")] Halbird,
        [Info("Staggerceps")] Staggerceps,
        [Info("Fishbone")] Fishbone,
        [Info("Flowbermeow")] Flowbermeow,
        [Info("Cyber Yog")] CyberYog,
        [Info("Chef Kyroo")] ChefKyroo,
        [Info("Lord Kyroo")] LordKyroo,
        [Info("Tatsu Blaze")] TatsuBlaze,
        [Info("Electricorn")] Electricorn,
        [Info("Woeflower")] Woeflower,
        [Info("Jestabocky")] Jestabocky,
        [Info("Eaglider")] Eaglider,
        [Info("Me Me Bunny")] MemeBunny,
        [Info("Drill Sye")] DrillSye,
        [Info("Tyranto Rex")] TyrantoRex,
        [Info("Majik Lapin")] MajikLapin,
        [Info("Cera Terror")] CeraTerror,
        [Info("Skelterwild")] Skelterwild,
        [Info("Ducky Goose")] DuckyGoose,
        [Info("Aura Lion")] AuraLion,
        [Info("Ryu Dragon")] RyuDragon,
        [Info("Drak Quack")] DrakQuack,
        [Info("Keeba Tiger")] KeebaTiger,
        [Info("Meowjesty")] Meowjesty,
        [Info("Sudo Neku")] SudoNeku,
        [Info("Frootz Cat")] FrootzCat,
        [Info("Ursa Circus")] UrsaCircus,
        [Info("Kab Kannon")] KabKannon,
        [Info("R & R Seal")] RRSeal,
        [Info("Spellican [Disabled, becomes R & R Seal.]")] Spellican,
        [Info("Commantis [Disabled, becomes R & R Seal.]")] Commantis,
        [Info("Char Clawbster [Disabled, becomes R & R Seal.]")] CharClawbster,
        [Info("Chill Clawbster [Disabled, becomes R & R Seal.]")] ChillClawbster,
        [Info("Hockomonkey [Disabled, becomes R & R Seal.]")] Hockomonkey,
        [Info("Holey Moley [Disabled, becomes R & R Seal.]")] HoleyMoley,
        [Info("Wargoyle [Disabled, becomes R & R Seal.]")] Wargoyle,
        [Info("Brawlamari [Disabled, becomes R & R Seal.]")] Brawlamari,
        [Info("Queen Buzzerfly [Disabled, becomes R & R Seal.]")] QueenBuzzerfly,
        [Info("Anti Black Coat [Disabled, becomes R & R Seal.]")] AntiBlackCoat
    }
}
