using KHSave.Attributes;

namespace KHSave
{
	public enum InventoryType
	{
		KupoCoin,
		Potion,
		HiPotion,
		MegaPotion,
		Ether,
		MegaEther,
		Elixir,
		Megalixir,
		Refocuser,
		HiRefocuser,
		Panacea,
		HiEther,
		[Unused] UnusedItem0d,
		[Unused] UnusedItem0e,
		[Unused] UnusedItem0f,
		[Unused] UnusedItem10,
		[Unused] UnusedItem11,
		Tent,
		StrengthBoost,
		MagicBoost,
		DefenseBoost,
		ApBoost,
		[Unused] UnusedBoost17,
		[Unused] UnusedBoost18,
		[Unused] UnusedBoost19,
		[Info("Kingdom Key")] KingdomKey,
		[Info("Hero's Origin")] HeroOrigin,
		ShootingStar,
		FavoriteDeputy,
		EvenAfter,
		HappyGear,
		CrystalSnow,
		HunnySpout,
		NanoGear,
		WheelOfFate,
		GrandChef,
		ClassicTone,
		[Unused] UnusedKeyblade26,
		[Unused] UnusedKeyblade27,
		UltimaWeapon,
		[Unused] UnusedKeyblade29,
		[Unused] UnusedKeyblade2a,
		Starlight,
		[Unused] UnusedKeyblade2c,
		[Unused] UnusedKeyblade2b,
		MageStaff,
		MageStaffPlus,
		Warhammer,
		WarhammerPlus,
		MagicianWand,
		MagicianWandPlus,
		Nirvana,
		NirvanaPlus,
		Astrolabe,
		AstrolabePlus,
		HeartlessMaul,
		HeartlessMaulPlus,
		SaveTheQueen,
		SaveTheQueenPlus,
		[Unused] UnusedStaff3c,
		[Unused] UnusedStaff3d,
		[Unused] UnusedStaff3e,
		[Unused] UnusedStaff3f,
		[Unused] UnusedStaff40,
		[Unused] UnusedStaff41,
		KnightShield,
		KnightShieldPlus,
		ClockworkShield,
		ClockworkShieldPlus,
		StarShield,
		StarShieldPlus,
		AegisShield,
		AegisShieldPlus,
		StormAnchor,
		StormAnchorPlus,
		NobodyGuard,
		NobodyGuardPlus,
		SaveTheKing,
		SaveTheKingPlus,
		[Unused] Unused50,
		[Unused] Unused51,
		[Unused] Unused52,
		[Unused] Unused53,
		[Unused] Unused54,
		[Unused] Unused55,
		[Unused] Unused56,
		[Unused] Unused57,
		[Unused] Unused58,
		[Unused] Unused59,
		[Unused] Unused5a,
		[Unused] Unused5b,
		[Unused] Unused5c,
		[Unused] Unused5d,
		HeartOfHero,
		CowboyPride,
		SpaceRangerSuit,
		GoldenHair,
		FryingPan,
		SkillAndCrossbones,
		IceClaws,
		PoweredSuit,
		Claws,
		KnockoutBody
	}
}
