/*
    Kingdom Hearts 0.2 and 3 Save Editor
    Copyright (C) 2019  Luciano Ciccariello

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using KHSave.Attributes;

namespace KHSave.Types
{
	public enum InventoryType
	{
		Empty,
		[Consumable("Potion")] Potion,
		[Consumable("Hi-Potion")] HiPotion,
		[Consumable("Mega-Potion")] MegaPotion,
		[Consumable("Ether")] Ether,
		[Consumable("Mega-Ether")] MegaEther,
		[Consumable("Elixir")] Elixir,
		[Consumable("Megalixir")] Megalixir,
		[Consumable("Refocuser")] Refocuser,
		[Consumable("Hi-Refocuser")] HiRefocuser,
		[Consumable("Panacea")] Panacea,
		[Consumable("Hi-Ether")] HiEther,
		[Unused] UnusedItem0d,
		[Unused] UnusedItem0e,
		[Unused] UnusedItem0f,
		[Unused] UnusedItem10,
		[Unused] UnusedItem11,
		[Consumable("Tent")] Tent,
		[Consumable("Strength boost")] StrengthBoost,
		[Consumable("Magic boost")] MagicBoost,
		[Consumable("Defense boost")] DefenseBoost,
		[Consumable("AP boost")] ApBoost,
		[Unused] UnusedBoost17,
		[Unused] UnusedBoost18,
		[Unused] UnusedBoost19,
		[Keyblade("Kingdom Key")] KingdomKey,
		[Keyblade("Hero's Origin")] HeroOrigin,
		[Keyblade("Shooting Star")] ShootingStar,
		[Keyblade("Favorite Deputy")] FavoriteDeputy,
		[Keyblade("Even After")] EvenAfter,
		[Keyblade("Happy Gear")] HappyGear,
		[Keyblade("Crystal Snow")] CrystalSnow,
		[Keyblade("Hunny Spout")] HunnySpout,
		[Keyblade("Nano Gear")] NanoGear,
		[Keyblade("Wheel of Fate")] WheelOfFate,
		[Keyblade("Grand Chef")] GrandChef,
		[Keyblade("Classic Tone")] ClassicTone,
		[Unused] UnusedKeyblade26,
		[Unused] UnusedKeyblade27,
		[Keyblade("Ultima Weapon")] UltimaWeapon,
		[Keyblade("Midnight Blue")] MidnightBlue,
		[Unused] UnusedKeyblade2a,
		[Keyblade("Starlight")] Starlight,
		[Keyblade("Dawn Till Dusk")] DawnTillDusk,
		[Unused] UnusedKeyblade2b,
		[Staff("Mage's Staff")] Weapon15,
		[Staff("Mage's Staff+")] Weapon16,
		[Staff("Warhammer")] Weapon17,
		[Staff("Warhammer+")] Weapon18,
		[Staff("Magician's Wand")] Weapon19,
		[Staff("Magician's Wand+")] Weapon1a,
		[Staff("Nirvana")] Weapon1b,
		[Staff("Nirvana+")] Weapon1c,
		[Staff("Astroblade")] Weapon1d,
		[Staff("Astroblade+")] Weapon1e,
		[Staff("Heartless Maul")] Weapon1f,
		[Staff("Heartless Maul+")] Weapon20,
		[Staff("Save the Queen")] Weapon21,
		[Staff("Save the Queen+")] SaveTheQueenPlus,
		[Unused] UnusedStaff3c,
		[Unused] UnusedStaff3d,
		[Unused] UnusedStaff3e,
		[Unused] UnusedStaff3f,
		[Unused] UnusedStaff40,
		[Unused] UnusedStaff41,
		[Shield("Knight Shield")] Weapon29,
		[Shield("Knight Shield+")] Weapon2a,
		[Shield("Clockwork Shield")] Weapon2b,
		[Shield("Clockwork Shield+")] Weapon2c,
		[Shield("Star Shield")] Weapon2d,
		[Shield("Star Shield+")] Weapon2e,
		[Shield("Aegis Shield")] Weapon2f,
		[Shield("Aegis Shield+")] Weapon30,
		[Shield("Storm Anchor")] Weapon31,
		[Shield("Storm Anchor+")] Weapon32,
		[Shield("Nobody Guard")] Weapon33,
		[Shield("Nobody Guard+")] Weapon34,
		[Shield("Save the King")] Weapon35,
		[Shield("Save the King+")] SaveTheKingPlus,
		[Unused] Unused50,
		[Unused] Unused51,
		[Unused] Unused52,
		[Unused] Unused53,
		[Unused] Unused54,
		[Unused] Unused55,
		[Unused] Unused56,
		[Unused] Unused57,
		[Unused] Unused58,
		[Unused] Unused59,
		[Unused] Unused5a,
		[Unused] Unused5b,
		[Unused] Unused5c,
		[Unused] Unused5d,
		[Weapon("Heart of Hero")] HeartOfHero,
		[Weapon("Cowboy's Pride")] CowboyPride,
		[Weapon("Space Ranger Suit")] SpaceRangerSuit,
		[Weapon("Golden Hair")] GoldenHair,
		[Weapon("Frying Pan")] FryingPan,
		[Weapon("Skill & Crossbones")] SkillAndCrossbones,
		[Weapon("Ice Claws")] IceClaws,
		[Weapon("Powered Suit")] PoweredSuit,
		[Weapon("Claws")] Claws,
		[Weapon("Knockout Body")] KnockoutBody,

		[Armor("Hero's Belt")] HeroBelt = 125,
		[Armor("Hero's Glove")] HeroGlove,
		[Armor("Shield Belt")] ShieldBelt,
		[Armor("Defense Belt")] DefensedBelt,
		[Armor("Guardian's Belt")] GuardianBelt,
		[Armor("Power Band")] PowerBand,
		[Armor("Buster Band")] BusterBand,
		[Armor("Buster Band+")] BusterBandPlus,
		[Armor("Cosmic Belt")] CosmicBelt,
		[Armor("Cosmic Belt+")] CosmicBeltPlus,
		[Armor("Fire Bangle")] FireBangle,
		[Armor("Firaga Bangle")] FiragaBangle,
		[Armor("Firaza Bangle")] FirazaBangle,
		[Armor("Fire Chain")] FireChain,
		[Armor("Blizzard Chocker")] BlizzardChocker,
		[Armor("Blizzara Chocker")] BlizzaraChocker,
		[Armor("Blizzaga Chocker")] BlizzagaChocker,
		[Armor("Blizzard Chain")] BlizzardChain,
		[Armor("Thunder Trinker")] ThunderTrinker,
		[Armor("Thundaga Trinker")] ThundagaTrinker,
		[Armor("Thundaza Trinker")] ThundazaTrinker,
		[Armor("Thunder Chain")] ThunderChain,
		[Armor("Dark Anklet")] DarkAnklet,
		[Armor("Midnight Anklet")] MidnightAnklet,
		[Armor("Chaos Anklet")] ChaosAnklet,
		[Armor("Dark Chain")] DarkChain,
		[Armor("Divine Bandanna")] DivineBandanna,
		[Armor("Elven Bandanna")] ElvenBandanna,
		[Armor("Aqua Chaplet")] AquaChaplet,
		[Armor("Wind Fan")] WindFan,
		[Armor("Storm Fan")] StormFan,
		[Armor("Aero Armlet")] AeroArmlet,
		[Armor("Aegis Chain")] AegisChain,
		[Armor("Acrisius")] Acrisius,
		[Armor("Cosmic Chain")] CosmicChain,
		[Armor("Petite Ribbon")] PetiteRibbon,
		[Armor("Ribbon")] Ribbon,
		[Armor("Fira Bangle")] FiraBangle,
		[Armor("Blizzaza Chocker")] BlizzazaChocker,
		[Armor("Thundara Trinker")] BlizzazaTrinker,
		[Armor("Shadow Anklet")] ShadowAnklet,
		[Armor("Abas Chain")] AbasChain,
		[Armor("Acrisius+")] AcrisiusPlus,
		[Armor("Royal Ribbon")] RoyalRibbon,
		[Armor("Firefighter Rosette")] FirefighterRosette,
		[Armor("Umbrella Rosette")] UmbrellaRosette,
		[Armor("Mask Rosette")] MaskRosette,
		[Armor("Snowman Rosette")] SnowmanRosette,
		[Armor("Insulator Rosette")] InsulatorRosette,

		[Accessory("Ability Ring")] AbilityRing = 227,
		[Accessory("Ability Ring+")] AbilityRingPlus,
		[Accessory("Star Medal")] StarMedal = 154,
		[Accessory("Star Medal")] StarMedal217 = 217,
		[Accessory("Star Medal")] StarMedal228 = 228,
	}
}
