using KHSave.Attributes;

namespace KHSave.Types
{
	public enum RecordUsageType
	{
		[Info("Kingdom Key / King of Hearts Total Uses")] Usage00,
		[Info("Kingdom Key / Ragnarok Total Uses")] Usage01,
		[Info("Hero's Origin / Drain Shock Total Uses")] Usage02,
		[Info("Hero's Origin / Atomic Deluge Total Uses")] Usage03,
		[Info("Shooting Star / Meteor Shower Total Uses")] Usage04,
		[Info("Shooting Star / Diving Barrage Total Uses")] Usage05,
		[Info("Shooting Star / Cluster Cannonade Total Uses")] Usage06,
		[Info("Favorite Deputy / Ghost Horde Total Uses")] Usage07,
		[Info("Favorite Deputy / Drill Dive Total Uses")] Usage08,
		[Info("Ever After / Shimmering Drops Total Uses")] Usage09,
		[Info("Ever After / Spectral Rays Total Uses")] Usage0a,
		[Info("Happy Gear / Snakebite Total Uses")] Usage0b,
		[Info("Happy Gear / Warp Trick Total Uses")] Usage0c,
		[Info("Crystal Snow / Diamond Dust Total Uses")] Usage0d,
		[Info("Crystal Snow / Frozen Crescents Total Uses")] Usage0e,
		[Info("Wheel of Fate / Blade Storm Total Uses")] Usage0f,
		[Info("Wheel of Fate / Flag Rampage Total Uses")] Usage10,
		[Info("Nano Gear / Cubic Stream Total Uses")] Usage11,
		[Info("Nano Gear / Zone Connector Total Uses")] Usage12,
		[Info("Hunny Spout / Hunny Burst Total Uses")] Usage13,
		[Info("Hunny Spout / Hunny Drizzle Total Uses")] Usage14,
		[Info("Hunny Spout / Sweet Surprise Total Uses")] Usage15,
		[Info("Grand Chef / Steam Spiral Total Uses")] Usage16,
		[Info("Grand Chef / Fruit Crusher Total Uses")] Usage17,
		[Info("Classic Tone / Phantom Rush Total Uses")] Usage18,
		[Info("Classic Tone / Noise Flux Total Uses")] Usage19,
		[Info("Starlight / Knights of the Round Total Uses")] Usage1a,
		[Info("Starlight / Union Ragnarok Total Uses")] Usage1b,
		[Info("Ultima Weapon / Infinity Circle Total Uses")] Usage1c,
		[Info("")] Usage1d,
		[Info("")] Usage1e,
		[Info("")] Usage1f,
		[Info("")] Usage20,
		[Info("")] Usage21,
		[Info("")] Usage22,
		[Info("")] Usage23,
		[Info("")] Usage24,
		[Info("")] Usage25,
		[Info("")] Usage26,
		[Info("")] Usage27,
		[Info("")] Usage28,
		[Info("")] Usage29,
		[Info("")] Usage2a,
		[Info("")] Usage2b,
		[Info("")] Usage2c,
		[Info("")] Usage2d,
		[Info("")] Usage2e,
		[Info("")] Usage2f,
		[Info("")] Usage30,
		[Info("")] Usage31,
		[Info("")] Usage32,
		[Info("")] Usage33,
		[Info("")] Usage34,
		[Info("")] Usage35,
		[Info("")] Usage36,
		[Info("")] Usage37,
		[Info("")] Usage38,
		[Info("")] Usage39,
		[Info("")] Usage3a,
		[Info("")] Usage3b,
		[Info("")] Usage3c,
		[Info("")] Usage3d,
		[Info("")] Usage3e,
		[Info("")] Usage3f,
		[Info("")] Usage40,
		[Info("")] Usage41,
		[Info("")] Usage42,
		[Info("")] Usage43,
		[Info("")] Usage44,
		[Info("")] Usage45,
		[Info("")] Usage46,
		[Info("")] Usage47,
		[Info("")] Usage48,
		[Info("")] Usage49,
		[Info("")] Usage4a,
		[Info("")] Usage4b,
		[Info("")] Usage4c,
		[Info("")] Usage4d,
		[Info("")] Usage4e,
		[Info("")] Usage4f,
		[Info("")] Usage50,
		[Info("")] Usage51,
		[Info("")] Usage52,
		[Info("")] Usage53,
		[Info("")] Usage54,
		[Info("")] Usage55,
		[Info("")] Usage56,
		[Info("")] Usage57,
		[Info("")] Usage58,
		[Info("")] Usage59,
		[Info("")] Usage5a,
		[Info("")] Usage5b,
		[Info("")] Usage5c,
		[Info("")] Usage5d,
		[Info("")] Usage5e,
		[Info("")] Usage5f,
		[Info("")] Usage60,
		[Info("")] Usage61,
		[Info("")] Usage62,
		[Info("")] Usage63,
		[Info("")] Usage64,
		[Info("")] Usage65,
		[Info("")] Usage66,
		[Info("")] Usage67,
	}
}
