using KHSave.Attributes;

namespace KHSave.Types
{
	public enum StoryFlagType
	{
		[Info("Scala ad Caelum")] ScalaAdCaelum,
		[Info("San Fransokyo")] SanFransokyo,
		[Info("Caribbean")] Caribbean,
		[Info("")] Story03,
		[Info("")] Story04,
		[Info("")] Story05,
		[Info("")] Story06,
		[Info("Destiny Island")] DestinyIsland,
		[Info("Land of Departure")] LandOfDeparture,
		[Info("Dark World")] DarkWorld,
		[Info("")] Story0A,
		[Info("The Final World")] TheFinalWorld,
		[Info("")] Story0C,
		[Info("")] Story0D,
		[Info("")] Story0E,
		[Info("")] Story0F,
		[Info("")] Story10,
		[Info("")] Story11,
		[Info("")] Story12,
		[Info("")] Story13,
		[Info("Arendelle")] Arendelle,
		[Info("Arendelle Avalanche")] ArendelleAvalanche,
		[Info("Gummi")] Gummi,
		[Info("")] Story17,
		[Info("")] Story18,
		[Info("")] Story19,
		[Info("")] Story1A,
		[Info("")] Story1B,
		[Info("")] Story1C,
		[Info("Olympus")] Hercules,
		[Info("")] Story1E,
		[Info("Keyblade Graveyard")] KeybladeGraveyard,
		[Info("KG | Dark Riku, Xigbar")] Story20,
		[Info("KG | Luxord, Marluxia, Larxene")] Story21,
		[Info("KG | Vanitas, Terra-Xehanort")] Story22,
		[Info("KG | Xion, Saix")] Story23,
		[Info("Monstropolis")] Monstropolis,
		[Info("")] Story25,
		[Info("100 Acre Wood")] Pooh,
		[Info("Kingdom of Corona")] KingdomOfCorona,
		[Info("")] Story28,
		[Info("")] Story29,
		[Info("")] Story2A,
		[Info("")] Story2B,
		[Info("Radiant Garden")] RadiantGarden,
		[Info("Secret Forest")] SecretForest,
		[Info("Toy Box")] ToyBox,
		[Info("")] Story2F,
		[Info("Twilight Town")] TwilightTown,
		[Info("")] Story31,
		[Info("")] Story32,
		[Info("")] Story33,
		[Info("")] Story34,
		[Info("")] Story35,
		[Info("")] Story36,
		[Info("")] Story37,
		[Info("")] Story38,
		[Info("")] Story39,
		[Info("")] Story3A,
		[Info("")] Story3B,
		[Info("")] Story3C,
		[Info("World Map")] WorldMap,
		[Info("The Mysterious Tower")] MysteriousTower,
		[Info("")] Story3F,
		[Info("")] Story40,
		[Info("")] Story41,
		[Info("")] Story42,
		[Info("")] Story43,
		[Info("")] Story44,
		[Info("")] Story45,
		[Info("")] Story46,
		[Info("")] Story47,
		[Info("")] Story48,
		[Info("")] Story49,
		[Info("")] Story4A,
		[Info("")] Story4B,
		[Info("")] Story4C,
		[Info("")] Story4D,
		[Info("")] Story4E,
		[Info("")] Story4F,
		[Info("")] Story50,
		[Info("")] Story51,
		[Info("")] Story52,
		[Info("")] Story53,
		[Info("")] Story54,
		[Info("")] Story55,
		[Info("")] Story56,
		[Info("")] Story57,
		[Info("")] Story58,
		[Info("")] Story59,
		[Info("")] Story5A,
		[Info("")] Story5B,
		[Info("")] Story5C,
		[Info("")] Story5D,
		[Info("")] Story5E,
		[Info("")] Story5F,
		[Info("")] Story60,
		[Info("")] Story61,
		[Info("")] Story62,
		[Info("")] Story63,
		[Info("")] Story64,
		[Info("")] Story65,
		[Info("")] Story66,
		[Info("")] Story67,
		[Info("")] Story68,
		[Info("")] Story69,
		[Info("")] Story6A,
		[Info("")] Story6B,
		[Info("")] Story6C,
		[Info("")] Story6D,
		[Info("")] Story6E,
		[Info("")] Story6F,
		[Info("")] Story70,
		[Info("")] Story71,
		[Info("")] Story72,
		[Info("")] Story73,
		[Info("")] Story74,
		[Info("")] Story75,
		[Info("")] Story76,
		[Info("")] Story77,
		[Info("")] Story78,
		[Info("")] Story79,
		[Info("")] Story7A,
		[Info("")] Story7B,
		[Info("")] Story7C,
		[Info("")] Story7D,
		[Info("")] Story7E,
		[Info("")] Story7F,
	}
}
